### ISSUE TITLE
Projects export or backup/restore

### ISSUE THREAD

**Issue by colossus-digital** [ansible-semaphore/semaphore#1024]
Is there a way to export (or backup and restore) all projects from a working machine to another ?

thank you very much

**Comment by Richardswe** [comment]
@colossus-digital the only thing i can come up with is to do a "dump" of the database, i know the users and tasks are stored there.

**Comment by fiftin** [comment]
@colossus-digital 
I agree it is useful feature.

**Comment by colossus-digital** [comment]
> @colossus-digital the only thing i can come up with is to do a "dump" of the database, i know the users and tasks are stored there.

i'm trying right now, there are 2 DBs:

```
+--------------------+
| Database           |
+--------------------+
| information_schema |
| semaphore          |
+--------------------+
```

Should i export both or just the semaphore ?

**Comment by fiftin** [comment]
Just semaphore

**Comment by colossus-digital** [comment]
just fyi

db backup (sql):

`mysqldump  -h localhost -P 3306 --protocol=tcp -u semaphore --password --databases semaphore --column-statistics=0 --no-tablespaces > ./semaphore_db_backup.sql`

db restore (sql):

`mysql  -h localhost -P 3306 --protocol=tcp --password -p semaphore < ./semaphore_db_backup.sql`

**Comment by remkolems** [comment]
FWIW I'm running semaphore in a docker(-compose) container (PostgreSQL). 

I'm going to use [Minio ](https://min.io) and https://github.com/offen/docker-volume-backup as a separate backup solution. If I figure the latter one correctly out, including battle testing, I'll report back here.

> just fyi
> 
> db backup (sql):
> 
> `mysqldump -h localhost -P 3306 --protocol=tcp -u semaphore --password --databases semaphore --column-statistics=0 --no-tablespaces > ./semaphore_db_backup.sql`
> 
> db restore (sql):
> 
> `mysql -h localhost -P 3306 --protocol=tcp --password -p semaphore < ./semaphore_db_backup.sql`

See also https://github.com/offen/docker-volume-backup#run-custom-commands-during-the-backup-lifecycle

**Comment by remkolems** [comment]
## **Create a backup of Ansible-Semaphore with (offen) docker-volume-backup on a S3 storage platform (MinIO)** 

- Notice the labels (mandatory for correct functioning of the docker-volume-backup container)

### Example given: docker-compose.yml
```yaml
version: '3.8'
services:
# =============================
# PostGreSQL
# -------------------------------------------------
# https://hub.docker.com/_/postgres
# https://github.com/docker-library/postgres
# https://www.postgresql.org
# =============================
  postgres_db:
    ports:
      - 5432:5432
    # Compatibility matrix of semaphore?
    # 14.5.x is a safe bet.
    # 15.1-alphine is latest as is.
    image: postgres:14.5-alpine
    hostname: postgres
    restart: always
    volumes: 
     - ansible_semaphore_data:/var/lib/postgresql/data
    environment:
     POSTGRES_USER: <database username>
     POSTGRES_PASSWORD: <database password>
     POSTGRES_DB: semaphore
    labels:
    # labels for offen/docker-volume-backup
    # https://github.com/offen/docker-volume-backup#run-custom-commands-during-the-backup-lifecycle
    # Notice the inner container mapping vs volumes
      - docker-volume-backup.archive-pre=/bin/sh -c 'pg_dumpall -c -U ansemaphore > /var/lib/postgresql/data/pgdumpall.sql'
      - docker-volume-backup.archive-post=/bin/sh -c 'rm /var/lib/postgresql/data/pgdumpall.sql'
      - docker-volume-backup.exec-label=postgres_db
# =============================
# Ansible-Semaphore
# -------------------------------------------------
# https://ansible-semaphore.com
# https://hub.docker.com/r/semaphoreui/semaphore/
# https://github.com/ansible-semaphore/semaphore
# =============================
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:v2.8.76 # v2.8.77 throws database schema errors
    restart: always
    environment:
      SEMAPHORE_DB_USER: <postgres user>
      SEMAPHORE_DB_PASS: <postgress password>
      SEMAPHORE_DB_HOST: postgres # for either postgres_db or timescale_db
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore?sslmode=disable # for postgres
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN: <admin username>      
      SEMAPHORE_ADMIN_PASSWORD: <admin user>
      SEMAPHORE_ADMIN_NAME: <admin full name>
      SEMAPHORE_ADMIN_EMAIL: <email@>
      # in cli: head -c32 /dev/urandom | base64
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: <generate key via cli>
      # SEMAPHORE_LDAP_ACTIVATED: 'no' # set to yes if you wish to use ldap
      # SEMAPHORE_LDAP_HOST: dc01.local.example.com
      # SEMAPHORE_LDAP_PORT: '636'
      # SEMAPHORE_LDAP_NEEDTLS: 'yes'
      # SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      # SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      # SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      # SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
      ANSIBLE_HOST_KEY_CHECKING: False
    labels:
    # labels for offen/docker-volume-backup
      - docker-volume-backup.stop-during-backup=semaphore
    depends_on:
      - postgres_db
# =============================
# docker-volume-backup
# -------------------------------------------------
# https://github.com/offen/docker-volume-backup#run-custom-commands-during-the-backup-lifecycle
# https://github.com/offen/docker-volume-backup
# https://hub.docker.com/r/offen/docker-volume-backup/tags
# =============================
  backup:
    image: offen/docker-volume-backup:v2.22.2
    restart: always
    environment:
      EXEC_LABEL: postgres_db # execute cli only on postgres_db
      BACKUP_STOP_CONTAINER_LABEL: semaphore
      BACKUP_FILENAME: daily-backup-%Y-%m-%dT%H-%M-%S.tar.gz
      # runs every day at 5am
      BACKUP_CRON_EXPRESSION: "0 5 * * *"
      BACKUP_PRUNING_PREFIX: daily-backup-
      BACKUP_RETENTION_DAYS: 7
      AWS_ENDPOINT: <https end point MinIO>
      AWS_S3_BUCKET_NAME: <bucket name>
      AWS_ACCESS_KEY_ID: <MinIO access key>
      AWS_SECRET_ACCESS_KEY: <MinIO secret access key>
      # https://github.com/offen/docker-volume-backup#use-special-characters-in-notification-urls
      # To get an encoded version of your URL, enter and follow instructions
      # docker run --rm -it containrrr/shoutrrr generate telegram
      NOTIFICATION_URLS: <telegram>
    volumes:
      - ansible_semaphore_data:/backup/ansible-semaphore-backup:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # run your cron rules in your local timezone
      # sudo timedatectl set-timezone Europe/Amsterdam
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

# Volumes for persisting data, see https://docs.docker.com/engine/admin/volumes/volumes/
volumes:
  ansible_semaphore_data:
    driver: local

networks:
  ansible:
```

### Result in MinIO
![image](https://user-images.githubusercontent.com/45675902/203410924-b86115c4-a76f-4017-a1f1-94b109c733f1.png)

### Contents of "daily-backup-2022-11-22T20-42-00.tar.gz\daily-backup-2022-11-22T20-42-00.tar\\backup\ansible-semaphore-backup\"
![image](https://user-images.githubusercontent.com/45675902/203411171-1c50432b-2222-4e81-aade-c34b47b47a04.png)


## Check/List volume contents (to check the backup file/folder contents)
```bash
sudo ls -las $(docker volume inspect as_ansible_semaphore_data | grep Mountpoint | cut -d\" -f 4)
```
### Result
Note: as expected the pgdumpall.sql has been removed from the volume.
```bash
total 136
 4 drwx------ 19   70   70  4096 Nov 23 05:05 .
 4 drwx-----x  3 root root  4096 Nov  8 12:29 ..
 4 drwx------  6   70   70  4096 Nov  8 12:29 base
 4 drwx------  2   70   70  4096 Nov 22 20:42 global
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_commit_ts
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_dynshmem
 8 -rw-------  1   70   70  4821 Nov  8 12:29 pg_hba.conf
 4 -rw-------  1   70   70  1636 Nov  8 12:29 pg_ident.conf
 4 drwx------  4   70   70  4096 Nov 22 20:46 pg_logical
 4 drwx------  4   70   70  4096 Nov  8 12:29 pg_multixact
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_notify
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_replslot
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_serial
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_snapshots
 4 drwx------  2   70   70  4096 Nov 22 20:41 pg_stat
 4 drwx------  2   70   70  4096 Nov 23 14:12 pg_stat_tmp
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_subtrans
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_tblspc
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_twophase
 4 -rw-------  1   70   70     3 Nov  8 12:29 PG_VERSION
 4 drwx------  3   70   70  4096 Nov 14 16:58 pg_wal
 4 drwx------  2   70   70  4096 Nov  8 12:29 pg_xact
 4 -rw-------  1   70   70    88 Nov  8 12:29 postgresql.auto.conf
32 -rw-------  1   70   70 28718 Nov  8 12:29 postgresql.conf
 4 -rw-------  1   70   70    24 Nov 22 20:41 postmaster.opts
 4 -rw-------  1   70   70    94 Nov 22 20:41 postmaster.pid
```

Next reply will be the restore procedure
