### ISSUE TITLE
Running in Docker container "nc: bad address"

### ISSUE THREAD

**Issue by bverkron** [ansible-semaphore/semaphore#1037]
Attempting to run Semaphore via a docker-compose file and can't seem to get it to work. The examples in the doc are focused on mysql and postgres and it's unclear to me how to get boltdb to work.

This is the docker-compose file. I tried with both bind mounts and volumes. Same issue. I wrote it based on a combination of [the doc](https://docs.ansible-semaphore.com/administration-guide/installation#docker) and the config.json that is generated when you run `semaphore setup` and tell it to use boltdb (more on that below)

```Dockerfile
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore
    volumes:
#      - /home/master/semaphore/mount_home:/home:rw
#      - /home/master/semaphore/mount_tmp:/tmp:rw
      - semaphore-home:/home
      - semaphore-tmp:/tmp      
    restart: unless-stopped
    ports:
      - 3000:3000      
    environment:
      SEMAPHORE_DB_HOST: /home/semaphore/database.boltdb
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
volumes:
  semaphore-home:
  semaphore-tmp:
```

When I start up I get this error:

```
2022-09-29T20:08:27.534381430Z Attempting to connect to database semaphore on /home/semaphore/database.boltdb:3306 with user semaphore ...
2022-09-29T20:08:27.554000646Z nc: bad address '/home/semaphore/database.boltdb'
2022-09-29T20:08:28.579505955Z nc: bad address '/home/semaphore/database.boltdb'
2022-09-29T20:08:29.600448407Z nc: bad address '/home/semaphore/database.boltdb'
...
```

I was able to connect into the container and manually run `semaphore setup` and it created the bolt db file and a config file but still gives those bad address errors when I start the container.

```
 You are all setup semaphore!
 Re-launch this program pointing to the configuration file

./semaphore server --config /home/semaphore/config.json

 To run as daemon:

nohup ./semaphore server --config /home/semaphore/config.json &

 You can login with  or semaphore.
```

```
bash-5.1$ ls -l /home/semaphore/
total 36
-rw-r--r--    1 semaphor root          1197 Sep 29 20:06 config.json
-rw-r--r--    1 semaphor root         65536 Sep 29 20:06 database.boltdb
```

This is the output of the config file it generated and that's what I tried to mimic in the docker file. Only a handful fo config settings are populated like bolt.host, dialect, tmp_path

```
bash-5.1$ cat /home/semaphore/config.json
{
 	"mysql": {
 		"host": "",
 		"user": "",
 		"pass": "",
 		"name": "",
 		"options": null
 	},
 	"bolt": {
 		"host": "/home/semaphore/database.boltdb",
 		"user": "",
 		"pass": "",
 		"name": "",
 		"options": null
 	},
 	"postgres": {
 		"host": "",
 		"user": "",
 		"pass": "",
 		"name": "",
 		"options": null
 	},
 	"dialect": "bolt",
 	"port": "",
 	"interface": "",
 	"tmp_path": "/tmp/semaphore",
 	"cookie_hash": "prsyeuAJUq7S48ZfJ6wiQ0wyBDY9JwICbuqua6Y4nCg=",
 	"cookie_encryption": "+KEKIM8NnSuzyhm2U2mYm/J/vBe1GUD3JLZfChomwuI=",
 	"access_key_encryption": "gch/Nph1Mi2kfmw87g/mbGeYLHVM30TxyPUQfqpqWW0=",
 	"email_sender": "",
 	"email_host": "",
 	"email_port": "",
 	"email_username": "",
 	"email_password": "",
 	"web_host": "",
 	"ldap_binddn": "",
 	"ldap_bindpassword": "",
 	"ldap_server": "",
 	"ldap_searchdn": "",
 	"ldap_searchfilter": "",
 	"ldap_mappings": {
 		"dn": "",
 		"mail": "",
 		"uid": "",
 		"cn": ""
 	},
 	"telegram_chat": "",
 	"telegram_token": "",
 	"max_parallel_tasks": 0,
 	"email_alert": false,
 	"email_secure": false,
 	"telegram_alert": false,
 	"ldap_enable": false,
 	"ldap_needtls": false,
 	"ssh_config_path": "",
 	"demo_mode": false
 }
```

When I manually run semaphore it appears to work but not when I spin the container up initially.

```
bash-5.1$ semaphore server --config /home/semaphore/config.json
BoltDB /home/semaphore/database.boltdb
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.8.65
Interface 
Port :3000
Server is running
```

I wonder if that's because the entry point runs this default config and the environment values aren't setup correctly or aren't overriding it?

**Comment by bverkron** [comment]
Just attempted to run the docker-compose exactly as it is in the official doc and I get the same error. Perhaps there's something more broadly wrong here with the docker image?

```
Attempting to connect to database semaphore on mysql:3306 with user semaphore ...
nc: bad address 'mysql'
```

**Comment by bverkron** [comment]
Got something working but it was from some online article on another site. Haven't compared to the official doc but something was obviously different. The is what I have working now. Would be nice if the official doc example worked "out of the box".

Note I had to change some ports around because I had other stuff (or other experimental instances of semaphore) running on the default ports. I also like to use bind mounts instead of volumes because I like having access to the containers working files directly on the host to make backups and manipulation easy, instead of having to mount volumes manually to access the container files.

```
version: '2'
services:

  mysql-semaphore:
    image: mysql:5.6
    ports:
      - 3303:3306
    container_name: mysql-semaphore
    hostname: mysql-semaphore
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore_db
      MYSQL_USER: semaphore_user
      MYSQL_PASSWORD: <make one up>
    volumes:
      - /home/master/semaphore_custom/mount_mysql:/var/lib/mysql

  semaphore:
    ports:
      - 3003:3000
    image: semaphoreui/semaphore:latest
    container_name: semaphore-custom
    environment:
      SEMAPHORE_DB_USER: semaphore_user
      SEMAPHORE_DB_PASS: <make one up>
      SEMAPHORE_DB_HOST: mysql-semaphore
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore_db
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: <make one up>
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: asdf@asdf.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: <generate one according to the doc via a CLI command>
    volumes:
      - /home/master/semaphore_custom/mount_semaphore:/home/semaphore    
    depends_on:
      - mysql-semaphore
```
