### ISSUE TITLE
Survey Variables Don't Seem To Do Anything

### ISSUE THREAD

**Issue by nlvw** [ansible-semaphore/semaphore#1081]
As stated in the title survey variables don't seem to actually do anything.

Consider the following Playbook:

```yaml
- name: "Test Ansible Connection"
  hosts: "{{ cplay_hosts | default('all') }}"
  become: false
  strategy: linear
  tasks:
    - name: connection test
      ping:
  post_tasks:
    - name: stop ssh client persistant connection
      meta: reset_connection
```

The default is to target 'all' hosts but is overridable if the 'cplay_hosts' variable is set.  This works fine on the command line but in semaphore if I set this with a survey variable it doesn't work and will target 'all' regardless. It looks like the survey variable is not setting the ansible variable at all.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/5723368/199795447-5e7994ae-f617-45d9-acce-e26bd233d140.png">

Ansible Semaphore Version = 2.8.66
