### ISSUE TITLE
Task will failed when task delegate_to localhost with sudo

### ISSUE THREAD

**Issue by DesireWithin** [ansible-semaphore/semaphore#1098]
**Environment:** Semaphore v2.8.53 , running in k8s.

I try to run such task like this:
```yaml
---
- name: docker clean
  hosts: all
  user: automation
  become: true
  gather_facts: false

  tasks:
    - name: wait 30 seconds and then continue
       wait_for:   # I konw use pause task by the way, I mean all tasks in this case will fail, for example uri 
           timeout: 30
       delegate_to: localhost
    ...
```
The output will show: 
```
[master]: FAILED! => {"msg": "privilege output closed while waiting for password prompt:\n/bin/sh: sudo: not found\n"}
```
The reason is there is no `sudo` command in Semaphore docker image.

__________________________________________________________________________________

So I build my own docker image:
Dockfile:
```
FROM semaphoreui/semaphore:v2.8.53

USER 0
RUN apk add --no-cache sudo

USER 1001
ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/usr/local/bin/semaphore-wrapper", "/usr/local/bin/semaphore", "server", "--config", "/etc/semaphore/config.json"]
```
The output will show:
```
fatal: [worker2]: FAILED! => {"changed": false, "module_stderr": "Sorry, try again.\n[sudo via ansible, key=byztqlhrjqaevwknheczcocehvqykrir] password:\nsudo: no password was provided\nsudo: 1 incorrect password attempt\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}
```
I think the reason is there is no `localhost` in the `Semaphore Inventory File` and I don't provide sudo password.
___________________________

So I let semaphore  run as root, the issue is solved.
Dockfile:
```
FROM semaphoreui/semaphore:v2.8.53

USER 0
RUN apk add --no-cache sudo

ENTRYPOINT ["/sbin/tini", "--"]
CMD ["/usr/local/bin/semaphore-wrapper", "/usr/local/bin/semaphore", "server", "--config", "/etc/semaphore/config.json"]
```

I know it is not best practices, 
What should I do?

**Comment by nroach44** [comment]
Add `become: false` to the `wait_for:` task:

```
...
  tasks:
    - name: wait 30 seconds and then continue
      become: false
      wait_for:   # I konw use pause task by the way, I mean all tasks in this case will fail, for example uri 
        timeout: 30
      delegate_to: localhost
...
```
