### ISSUE TITLE
semaphore-wrapper ignores environment variables via docker

### ISSUE THREAD

**Issue by pufferbatterie** [ansible-semaphore/semaphore#1110]
I can' run the default dockerized example from README.md
SEMAPHORE_DB_DIALECT seems to be ignored or resetted to default by semaphore-wrapper

```
version: '2'

services:
  semaphore:
    ports:
      - 3000:3000
    image: ansiblesemaphore/semaphore:v2.8.53   #tried 2.7.0 too
    environment:
      SEMAPHORE_DB_DIALECT: bolt

    # without command: it uses mysql regardless of env var

    # uses mysql probably from /usr/local/bin/semaphore-wrapper default (https://github.com/ansible-semaphore/semaphore/blob/develop/deployment/docker/common/semaphore-wrapper#L31)
#    command: /bin/sh -c "printenv ; sleep 1 ; /usr/local/bin/semaphore-wrapper  /usr/local/bin/semaphore server --config /etc/semaphore/config.json"

    # prints: semaphore-1  | Cannot Find configuration! Use --config parameter to point to a JSON file generated by `semaphore setup`.
    command: /bin/sh -c "printenv ; sleep 1 ; /usr/local/bin/semaphore server --config /etc/semaphore/config.json"

```

docker verion is btw: Docker version 20.10.18, build e42327a
but passes environment variables through the container tested with printenv
