### ISSUE TITLE
unable to access SSL certificate

### ISSUE THREAD

**Issue by igor-rus43** [ansible-semaphore/semaphore#1138]
The certificate is allowed on the main machine. But git clone is executed from docker. How can this be corrected? Apparently you need to put a certificate
```
Cloning Repository https://data.passport.local:8220/auth/sudir/devops/ansible.git
Cloning into 'repository_1_1'...
fatal: unable to access 'https://data.passport.local:8220/auth/sudir/devops/ansible.git/': SSL certificate problem: unable to get local issuer certificate
```

**Comment by Kariton** [comment]
the dirty way:

add a gitconfig to your volumes:
```yaml
    volumes:
      - /path/to/data/gitconfig:/etc/gitconfig:r
```

and this is the content of `gitconfig`

```ini
[http]
    sslVerify = false
```

just solved the same issue for myself.
with this approach no certificate validation is done.

it is better to trust the CA e.g. add your CA to the docker image. (have to look into that myself)

**Comment by mboeker** [comment]
The sslverify = false is not a good solution, for one thing that only fixes the problem of pulling the repo. In my setup I have a CA and SUI will need to trust my CA for access to everything.
I've tried this:
```
    volumes:
      - ./my-ca.cert:/etc/ssl/my-ca.crt:ro
      ...
    environment:
      ...
      SSL_CERT_FILE: /etc/ssl/my-ca.crt
      REQUESTS_CA_BUNDLE: /etc/ssl/my-ca.crt
      CURL_CA_BUNDLE: /etc/ssl/my-ca.crt
      GIT_SSL_CAINFO: /etc/ssl/my-ca.pem
```
This makes `curl https://somehost.my.local` work inside the SUI container, but it still won't git clone from gitlab.my.local`
