### ISSUE TITLE
How to become root in Semaphpore Task Templates ?

### ISSUE THREAD

**Issue by drtech981** [ansible-semaphore/semaphore#1154]
Playbook I'm trying to execute : 
```
---

- hosts: ubuntu
  become: yes
  become_method: sudo
  become_user: root
  tasks:
  - name: Update Repositories and Upgrade Packages [Ubuntu]
    apt:
      update_cache: yes
      upgrade: "yes"
    when: ansible_distribution == "Ubuntu"
```

Error I'm Getting : 
`Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)"`

I've even edit sudoers file to not ask for password for escalating privileges, however I'm still getting the same error.

What else do I need to do to attain root privileges while execute a task template ?

**Comment by ySp-chld** [comment]
I think your issue is with Ansible not semaphore have you tried your code outside of Semaphore ?
I'm usually just using `become: true` on task or playbook i want to run as root.
Maybe it's also a sudo issue but semaphore is not responsible imho.

**Comment by drtech981** [comment]
Running the playbook via CLI doesn't bring up any error. 
My issue is how to elevate privileges when running a playbook via Semaphore, then maybe I don't need `become: true`

**Comment by fiftin** [comment]
You should provide Sudo credentials to Inventory.

<img width="483" alt="image" src="https://user-images.githubusercontent.com/914224/215227421-8292c498-b4c0-4495-ad48-878f2c9c785c.png">

**Comment by drtech981** [comment]
I already have. 
![image](https://user-images.githubusercontent.com/79300765/215304670-b055f42d-efcf-47c2-9e10-310d5b8ec6f1.png)

Still getting the same error ...

Can anyone post any of their playbooks requiring root ?

**Comment by lbouriez** [comment]
I am also interested on this, having the same error, become: true in my playbook doesnt use the sudo credentials setup in semaphore.
@drtech981 did you find a solution ?

**Comment by emdepl** [comment]
Hi, 

I have the same problem with simple playbook 
Sudo password is added in credentials and set in inventory

```
---
- name: Check become success
  hosts: all

  tasks:
  - name: Check whoami
    command: whoami
    register: whoami_out

  - name: Check whoami become
    command: whoami
    become: true
    become_method: sudo
    become_user: root
    register: whoami_become_out
```

```
# lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```

```
# ansible --version
ansible 2.9.6
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.8.10 (default, Nov 14 2022, 12:59:47) [GCC 9.4.0]
```

**Comment by emdepl** [comment]
Hi,

I solved my problem. 
My scenario was: 

- semaphore installed and running under user semaphore
- ansible connecting by default as user root
- userX was used to connecting to servers

**Setting ansible_ssh_user to userX in inventory (or extra vars) and mentioned earlier credentials for sudo/become - solved my problem**

I think ansible_ssh_user or ansible_user should be set to value from user credentials in semaphore inventory. Here is something broken https://github.com/ansible-semaphore/semaphore/blob/8d5ba2857d6b9501f0ca13f167080cd569ca5bb3/services/tasks/runner.go#L693

**Comment by drtech981** [comment]
@emdepl Whrre exactly do I add `ansible_ssh_user` ? How do set it up in inventory ? Where are the extra vars declared ? 
Help will be much appreciated.

**Comment by timmyb824** [comment]
Thought I'd mention I've tried a million and one things to get a similar playbook to work but can never get past `
E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?`. I tired every combination of ansible config, variable, and argument; I've tried them in the inventory file, ansible.cfg file, extra arguments within the CLI, and within the playbooks themselves but still no luck. This included trying @emdepl solution but that didn't work either. All works well using the `ansible-playbook` command on the host, but not when trying to use Semaphore. For example this works fine:

```yaml
- name: Update packages via apt
  hosts: all

  tasks:
    - name: Update apt packages
      ansible.builtin.apt:
        name: '*'
        state: latest
        update_cache: true
        cache_valid_time: 86400 # One day
      when:
        - ansible_distribution == "Ubuntu" or ansible_distribution == "Debian"
```

```bash
ansible-playbook -i inventory.ini update-pkgs.yaml
```

In this case, I tried setting `ansible_become_password` rather than using -K  just to see if it made a difference.
```ini
[hosts]
vm100 ansible_host=192.168.86.123 ansible_port=22 ansible_user=jsmith ansible_become=true ansible_become_password=password123 ansible_private_key_file=/home/jsmith/.ssh/id_rsa
```

I did everything the same on semaphore, except I didn't specify `ansible_private_key_file=/home/jsmith/.ssh/id_rsa` in the inventory since its in the keystore, but it won't work and I am lost as to why.

**Comment by talha5389** [comment]
Not working for me as well. Trying to debug for hours now. It works via cli but not with semaphore. I am running semaphore in docker

**Comment by Caesarovich** [comment]
I had kind of the same issue. When creating the credentials you will use as Sudo credentials, make sure to specify the username to `root` or whatever user you need it. I had made the mistake to only specify the root password and assumed that `become_user` in my playbooks would make it, but no. You must both specify the sudo user and its password.

I hope this helps you guys. @talha5389 @drtech981

**Comment by dcolley** [comment]
In my inventory I configured a key for `User credentials` and user:pass `Sudo credentials`.

Finally adding this in the Environment worked for me:
```json
{
  "ansible_become_user": "root"
}
```

![image](https://github.com/ansible-semaphore/semaphore/assets/1845970/39d20114-7771-461e-afff-86459daccbb1)

**Comment by drtech981** [comment]
> In my inventory I configured a key for `User credentials` and user:pass `Sudo credentials`.

Can you please give the proper syntax for this ? I'm not being able to get it to work.

**Comment by dcolley** [comment]
This is my playbook:
```yml
---
- name: Update and upgrade packages on Ubuntu
  hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true

    - name: Upgrade all packages
      apt:
        upgrade: dist
```
This is my Inventory:

![image](https://github.com/ansible-semaphore/semaphore/assets/1845970/0bcede17-a46f-4862-be0d-c20e2da092cd)

User Credentials are `ssh key`: username: derek, private key generated on command line, then `ssh-copy-id` the key to all target servers.
Sudo credentials are `user:pass` derek:myspecialsecret...!

**Update**: I also tried with user:pass in both User and Sudo credentials and it works for me.
