### ISSUE TITLE
Docker Compose Container Fails

### ISSUE THREAD

**Issue by rxerium** [ansible-semaphore/semaphore#1173]
Hey, 

I have the below error when attempting to start the container (`docker-compose up -d`) with the default settings provided on the README. 

```
Config output directory (default /home/semaphore): 
Running: mkdir -p /etc/semaphore..
panic: open /etc/semaphore/config.json: permission denied

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/cli/setup.SaveConfig(0xc0000b6dc0)
        /go/src/github.com/ansible-semaphore/semaphore/cli/setup/setup.go:155 +0x40b
github.com/ansible-semaphore/semaphore/cli/cmd.doSetup()
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:34 +0x7f
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func4(0x22e45a0?, {0x9d3e5d?, 0x1?, 0x1?})
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:23 +0x17
github.com/spf13/cobra.(*Command).execute(0x22e45a0, {0xc0000a6400, 0x1, 0x1})
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x22e36a0)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:36 +0x5b
main.main()
        /go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x17
```

I've started the container in privileged mode however that did not seem to work, any ideas?

Thanks

**Comment by rxerium** [comment]
Further errors when running it in a different container:
```
root@ansible-semphore:~/ansible# sudo docker-compose up -d
Starting ansible_semaphore_1 ... error

ERROR: for ansible_semaphore_1  Cannot start service semaphore: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default3178010533` failed with output: apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?

error: exit status 243

ERROR: for semaphore  Cannot start service semaphore: AppArmor enabled on system but the docker-default profile could not be loaded: running `/usr/sbin/apparmor_parser apparmor_parser -Kr /var/lib/docker/tmp/docker-default3178010533` failed with output: apparmor_parser: Unable to replace "docker-default".  Permission denied; attempted to load a profile while confined?

error: exit status 243
ERROR: Encountered errors while bringing up the project.
```

Note that I am experiencing these errors on Proxmox LXC containers.

**Comment by isracostta** [comment]
The same erro for me.

semaphore_1  | Generating /tmp/semaphore/config.stdin ...
semaphore_1  | 2
semaphore_1  | /var/lib/semaphore/database.boltdb
semaphore_1  | /tmp/semaphore
semaphore_1  |
semaphore_1  | no
semaphore_1  | no
semaphore_1  | no
semaphore_1  | no
semaphore_1  | /etc/semaphore
semaphore_1  | admin
semaphore_1  | admin@localhost
semaphore_1  | admin
semaphore_1  | changeme
semaphore_1  | 
semaphore_1  | Hello! You will now be guided through a setup to:
semaphore_1  |
semaphore_1  | 1. Set up configuration for a MySQL/MariaDB database
semaphore_1  | 2. Set up a path for your playbooks (auto-created)
semaphore_1  | 3. Run database Migrations
semaphore_1  | 4. Set up initial semaphore user & password
semaphore_1  |
semaphore_1  | What database to use:
semaphore_1  |    1 - MySQL
semaphore_1  |    2 - BoltDB
semaphore_1  |    3 - PostgreSQL
semaphore_1  |  (default 1):
semaphore_1  | db filename (default /home/semaphore/database.boltdb):
semaphore_1  | Playbook path (default /tmp/semaphore):
semaphore_1  | Web root URL (optional, see https://github.com/ansible-semaphore/semaphore/wiki/Web-root-URL):
semaphore_1  | Enable email alerts? (yes/no) (default no):
semaphore_1  | Enable telegram alerts? (yes/no) (default no):
semaphore_1  | Enable slack alerts? (yes/no) (default no):
semaphore_1  | Enable LDAP authentication? (yes/no) (default no):
semaphore_1  | Config output directory (default /home/semaphore):
semaphore_1  | Running: mkdir -p /etc/semaphore..
semaphore_1  | panic: open /etc/semaphore/config.json: permission denied
semaphore_1  |
semaphore_1  | goroutine 1 [running]:
semaphore_1  | github.com/ansible-semaphore/semaphore/cli/setup.SaveConfig(0xc000162dc0)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/cli/setup/setup.go:155 +0x40b
semaphore_1  | github.com/ansible-semaphore/semaphore/cli/cmd.doSetup()
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:34 +0x7f
semaphore_1  | github.com/ansible-semaphore/semaphore/cli/cmd.glob..func4(0x25d30e0?, {0xb96f17?, 0x1?, 0x1?})
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:23 +0x17
semaphore_1  | github.com/spf13/cobra.(*Command).execute(0x25d30e0, {0xc0001af120, 0x1, 0x1})
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
semaphore_1  | github.com/spf13/cobra.(*Command).ExecuteC(0x25d21e0)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3b4
semaphore_1  | github.com/spf13/cobra.(*Command).Execute(...)
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
semaphore_1  | github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:36 +0x5b
semaphore_1  | main.main()
semaphore_1  |  /go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x17

**Comment by atribemc** [comment]
You can get around this problem by creating the config.json file in you mapped ./data/home directory. then you can populate it with the default values. https://docs.ansible-semaphore.com/administration-guide/configuration#configuration-file

After I did that I had trouble with it parsing the config.json file. So i just set everything with environment vars in the docker-compose file and didn't map ./data/home:/etc/semaphore at all.

**Comment by thetredev** [comment]
I encountered this issue too. The problem is that you're mapping `/home/semaphore` as root user, but it's supposed to belong to a different user (`semaphore` I guess). Hence, it can't create a file in there. It's akin to run the following command as non-root user:
```
$ mkdir -p /root/somedir
```

But I don't see any possibility to tell Docker to map the directory to a different user. The semaphore application/wrapper should  do that for us, but it doesn't as it seems.

I tried doing this because the environment variables from the docs are not used, and I have no idea how to configure semaphore via Docker Compose without those. Mapping `/etc/semaphore` to a folder containing the correct `config.json` file doesn't help either, it always falls back to the defaults... Image used: `semaphoreui/semaphore:v2.8.90`.

**Comment by Cloud-Kid** [comment]
Same problem here, seems odd, shouldn't this kind of rights abstraction be handled by docker ? Creating directories and docker-compose file as root result with the same error.

**Comment by thetredev** [comment]
@Cloud-Kid no, should be handled by the application (wrapper).

**Comment by Cloud-Kid** [comment]
I managed to make it running by setting the image version from "latest" to "v2.8.90" and adding a "user" statement in my docker-compose

`user: "${UID}:${GID}"`

At startup, the following statement is printed : 
```
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
```

I don't understand the difference, but it works. 

Hope this will help some of you

**Comment by thetredev** [comment]
@Cloud-Kid thanks! Gonna try this next week also.

**Comment by kavishgr** [comment]
Changing both volume locations to `/home/semaphore` result in no errors:

```yaml
volumes:
      - ./config:/home/semaphore
      - ./boltdb:/home/semaphore
```

 But both `./config` and `./boltdb` are empty.

**Comment by pythoninthegrass** [comment]
@Cloud-Kid That worked for me too! Was following @ChristianLempa's [post](https://github.com/ChristianLempa/videos/tree/main/ansiblesemaphore-tutorial) and it wasn't obvious that a blank string would solve permissions issues upstream.

FWIW this is my known good `docker-compose.yml` config:
```yaml
version: "3.9"

services:
  postgres:
    image: postgres:14
    container_name: semaphore-postgres
    restart: unless-stopped
    hostname: postgres
    volumes:
     - semaphore-postgres:/var/lib/postgresql/data
    environment:
     - POSTGRES_USER=semaphore
     - POSTGRES_PASSWORD=${DB_PASS}
     - POSTGRES_DB=semaphore

  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: ansible-semaphore
    restart: unless-stopped
    user: "${UID}:${GID}"
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=${DB_PASS}
      - SEMAPHORE_DB_HOST=postgres
      - SEMAPHORE_DB_PORT=5432
      - SEMAPHORE_DB_DIALECT=postgres
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=${SEM_ADMIN_PASS}
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=${SEM_ACCESS_KEY} # head -c32 /dev/urandom | base64
      - ANSIBLE_HOST_KEY_CHECKING=false                   # optional
    volumes:
      - "$HOME/docker/containers/semaphore/inventory/:/inventory:ro"
      - "$HOME/docker/containers/semaphore/authorized-keys/:/authorized-keys:ro"
      - "$HOME/docker/containers/semaphore/config:/etc/semaphore:rw"
    depends_on:
      - postgres

volumes:
  semaphore-postgres:
    driver: local
```

**Comment by venkatakarthikbandaru** [comment]
@isracostta were you able to fix this problem and setup semaphore, i was facing the same issue

**Comment by fardjad** [comment]
The docker image [defaults to UID 1001](https://github.com/ansible-semaphore/semaphore/blob/30f8c5a7fa5fdd52df056268e96255dfc8b53dae/deployment/docker/prod/Dockerfile#L29).

With the following in `docker-compose.yml`:

```
services:
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
    volumes:
      - ./data/home:/etc/semaphore
      - ./data/lib:/var/lib/semaphore
```

You can create a data directory and set its owner to ID 1001:

```
mkdir -p ./data/{home,lib}
sudo chown -R 1001 ./data
```

And then start the container.

**Comment by kavishgr** [comment]
Tried it with rootless podman. Works fine without any issues. I'm using `userns_mode: keep-id`(which is root inside the container and mapped as my user(toto) on the host). Got the compose file [here](https://docs.semui.co/administration-guide/installation#docker). I removed all the LDAP entries, and left everything as is(not recommended).

```
services:
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    userns_mode: keep-id
    hostname: mysql
    volumes:
      - ./semaphore-mysql:/var/lib/mysql:Z
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
    depends_on:
       - mysql
```

Owner of the `semaphore-mysql` directory:

```
toto@coreos:~/semaphore$ ls -ldZ semaphore-mysql
drwxr-xr-x. 8 toto toto system_u:object_r:container_file_t:s0:c229,c974 4096 Jan 14 09:49 semaphore-mysql
toto@coreos:~/semaphore$ podman unshare ls -ldZ semaphore-mysql
drwxr-xr-x. 8 root root system_u:object_r:container_file_t:s0:c229,c974 4096 Jan 14 09:49 semaphore-mysql
```
