### ISSUE TITLE
Question:  How to get ARA working with ansible-semaphore

### ISSUE THREAD

**Issue by samcro1967** [ansible-semaphore/semaphore#1243]
Below is what I have tried to get ARA working with ansible-semaphore.

1.  Added environment variables to Semaphore docker compose for `ANSIBLE_CALLBACK_PLUGINS`, `ARA_API_CLIENT`, & `ARA_API_SERVER`.
2. Installed pip3 and ARA w/o server API using a custom Dockerfile in the semaphore container.
3. Confirmed with `ansible-config dump` that `ANSIBLE_CALLBACK_PLUGINS` is seen by ansible.
4. Confir4med with echo from inside the container that environment variables `ARA_API_CLIENT` & `ARA_API_SERVER` are present.
5. Configured ARA to listen on 192.168.1.104 in /opt/ara/settings.yaml.
6. Ran playbook with `--vvv` and waited until successful completion.
7. Browsed to ARA reporting URL and no playbook executions, tasks, or hosts are present.

I am not seeing anything in the ansible task output in the Semaphore GUI about callback errors or errors in either container logs.  Not sure what I am missing.  Hoping someone can point out what I have missed.

**Dockerfile**
```
FROM semaphoreui/semaphore:latest

USER root
RUN apk add rsync py3-pip
user semaphore
RUN pip install git+https://github.com/ansible-community/ara
```
<sumary>**Docker Compose**</summary>
<details>

```
  ara-api:
    hostname: ara-api
    image: recordsansible/ara-api:latest
    container_name: ara-api
    restart: always
    ports:
      - 9450:8000
    volumes:
      - ${docker}/ara-api:/opt/ara
    tty: true  
semaphore:
    hostname: semaphore
    image: osu.registry:5000/user/semaphore:latest #semaphoreui/semaphore:latest
    container_name: semaphore
    restart: unless-stopped
    environment:
      - SEMAPHORE_DB_USER=user
      - SEMAPHORE_DB_PASS=password
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=password
      - SEMAPHORE_ADMIN_NAME=user
      - SEMAPHORE_ADMIN_EMAIL=user@doamin.net
      - SEMAPHORE_ADMIN=user
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=<redacted>
      - ANSIBLE_HOST_KEY_CHECKING=False
      - ANSIBLE_CALLBACK_PLUGINS=$(python3 -m ara.setup.callback_plugins)
      - ARA_API_CLIENT=http
      - ARA_API_SERVER=http://192.168.1.104:9450
    ports:
      - 3100:3000
    volumes:
      - ${docker}/semaphore/temp:/tmp/semaphore/
      - ${docker}/semaphore/ansible/ansible.cfg:/etc/ansible/ansible.cfg
      - ${docker}/semaphore/config/config.json:/etc/semaphore/config.json
      - ${docker}/ansible:/ansible
      - /home/user:/home/user
    depends_on:
      - mysql
```
</details>
