### ISSUE TITLE
Configure colors of output window and/or background

### ISSUE THREAD

**Issue by jrglynn2** [ansible-semaphore/semaphore#1256]
Hi, this is an enhancement request to be able to either change the color scheme for the play results generated in the output window, or to change the background of the output window from Black to something else.

My issue is some of my plays, I can't see the play results in the output window because it is the same color as the background.

I have attached 2 screen shots - 1 of the output not being seen, and 1 of the output that is highlighted, to show the output is there, but can't be seen because it matches the background. I redacted the server name & URL, but you should be able to see what is happening.

For this particular play, I am doing a straightforward URI call, waiting for a URL to come back up before proceeding to the next step.
```
- name: Test if application is up - {{ tags.URL }}
  delegate_to: localhost
  ignore_errors: yes
  ansible.builtin.uri:
      url: "{{ tags.URL + url_healthcheck }}"
      method: GET
      src: url_post.json
      return_content: yes
  register: url_check
  until: "'OK' in (url_check.content|upper)"
  retries: 720 # 720 * 5 seconds = 1hour (60*60/5)
  delay: 5 # Every 5 seconds
```

To be able to fully customize any of the colors would be ideal, but even just being able to customize the background color to various shades would work, I think.

Thanks!

![semaphore_cant-see-results](https://github.com/ansible-semaphore/semaphore/assets/41384097/e560c56f-d706-4d42-8340-630b045a06b3)
![semaphore_highlight-results](https://github.com/ansible-semaphore/semaphore/assets/41384097/4007cf58-e0ba-4eb7-84f1-5b1d2a281aa3)
