### ISSUE TITLE
How to use bastion in Semaphore

### ISSUE THREAD

**Issue by 9whirls** [ansible-semaphore/semaphore#1258]
I installed the latest version of Semaphore via Snap on an Ubuntu VM. It works well when I run tasks against nodes with public IPs. However, when remote nodes only have private IPs and need to be reached via a bastion server, tasks always fail saying the remote node is unreachable. My inventory file looks like below

```
all:
  hosts:
    vm01:
      ansible_host: <private_ip>
  vars:
    bastion: <bastion_public_ip>
    ansible_ssh_private_key_file: /var/snap/semaphore/current/my_private_key.pem
    ansible_ssh_common_args: "-o ProxyCommand='ssh -q ubuntu@{{bastion}} -o IdentityFile=/var/snap/semaphore/current/my_private_key.pem -W %h:%p'"
    ansible_user: administrator
    ansible_shell_type: cmd
```

This works well if I run Ansible directly from the VM, but running it from Semaphore fails.
Does anyone know how to resolve this problem?
Meanwhile is there a way to change the ssh config file (`~/.ssh/config` on Ubuntu, but don't know where the counterpart file is in snap) within the Semaphore snap?
