### ISSUE TITLE
Docker security - support secrets

### ISSUE THREAD

**Issue by alaricljs** [ansible-semaphore/semaphore#1268]
It would be helpful for the docker image and compose example to properly support Docker secrets.  Generally this is achieved by adding an env var `NNNN_FILE` where NNNN is any env var that should contain sensitive info.  The NNNN_FILE will then be pointed to a mounted secret containing the sensitive data and the docker container/software will need to read that file rather than the NNNN env var.

See postgres' own docker container and `POSTGRES_PASSWORD_FILE` as an example of implementation.

**Comment by alaricljs** [comment]
I went through the code in deployment/docker/common/semaphore-wrapper to figure out how hard this might be and it turns out the only lack is in the documentation.

I'm not so great at documentation either. ;)

**Comment by adicrescenzo** [comment]
Thanks @alaricljs, I was plan to open a merge request in order to add this feature. I would like to use docker-compose secrets and reading settings from file instead of env vars is essential

**Comment by c-10001001** [comment]
You can indeed set some of the  variables through a secret.
Below is an example compose file

```
version: '3.7'

services:
  mysql:
    #restart: unless-stopped
    image: mysql:8.0
    secrets:
        - semaphore_dbuser
        - semaphore_dbpassword
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER_FILE: /run/secrets/semaphore_dbuser
      MYSQL_PASSWORD_FILE: /run/secrets/semaphore_dbpassword
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:latest
    secrets:
        - semaphore_dbuser
        - semaphore_dbpassword
        - semaphore_admin_user
        - semaphore_adminpassword
        - semaphore_accesskey
    environment:
      SEMAPHORE_DB_USER_FILE: /run/secrets/semaphore_dbuser
      SEMAPHORE_DB_PASS_FILE: /run/secrets/semaphore_dbpassword
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD_FILE: /run/secrets/semaphore_adminpassword
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN_FILE: /run/secrets/semaphore_admin_user
      SEMAPHORE_ACCESS_KEY_ENCRYPTION_FILE: /run/secrets/semaphore_accesskey
      #SEMAPHORE_LDAP_PASSWORD_FILE:
    depends_on:
      - mysql 

volumes:
  semaphore-mysql: 

secrets:
  semaphore_adminpassword:
    external: true
  semaphore_dbuser:
    external: true
  semaphore_accesskey:
    external: true
  semaphore_admin_user:
    external: true
  semaphore_database:
    external: true
  semaphore_dbpassword:
    external: true

```

I think this can be closed with a quick reference to the _FILE vars in the documentation.
