### ISSUE TITLE
Become: true is not working and real time too

### ISSUE THREAD

**Issue by S0b1t** [ansible-semaphore/semaphore#1279]
Hi,

I installed semaphore from [docs](https://docs.ansible-semaphore.com/administration-guide/installation#docker)

### Become: true is not working

First, I ran an ansible playbook to create some files to test the functionality of the Semaphore that doesn't require root user. Everything was fine. But when I run a file that updates the packages, it throws a **_fatal: [172.30.122.60]: FAILED! => {"changed": false, "msg": "This command has to be run under the root user.", "results": []}_**

This is my file looks like:
```
---
- hosts: "{{ hosts }}"
  become: yes

  tasks:
    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
```
When I run the file on the server using Ansible CLI it worked fine. Without any problem.
Tried to become: true ethier

Tried [this-command-has-to-be-run-under-the-root-user-but-i-am-root-only](https://stackoverflow.com/questions/68978130/this-command-has-to-be-run-under-the-root-user-but-i-am-root-only) and [ansible-role-bootstrap/issues/39](https://github.com/robertdebock/ansible-role-bootstrap/issues/39), didn't help.

### Showing jobs in real time is not working

After running any task, nothing is displayed, it is only displayed after refreshing the web browser page.

![image](https://github.com/ansible-semaphore/semaphore/assets/87570847/ef157b47-231e-4fa3-9567-9d32846aad3c)

**Comment by S0b1t** [comment]
My apologies for the second problem. I'm using the Firefox web browser, tried to run with Chrome and it shows the process in real time. Looks like a problem with Firefox

**Comment by thetanil** [comment]
become is also not working for me. I am using docker semaphoreui/semaphore:latest

when I run on the dockers host machine it's fine (uid=0), but when I run via semaphore, I get my user id.

```yaml
- hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: check id
      command: id -u
      register: id_output

    - name: print id
      debug:
        msg: "{{ id_output.stdout }}"

    - name: assert
      assert:
        that: id_output.stdout == '0'
```
