### ISSUE TITLE
sftp transfer mechanism failed

### ISSUE THREAD

**Issue by Razva** [ansible-semaphore/semaphore#1282]
I'm getting this when running a simple playbook:

```
[WARNING]: sftp transfer mechanism failed on [X.X.X.X]. Use ANSIBLE_DEBUG=1 to see detailed information
<X.X.X.X> SSH: EXEC scp -vvv -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o Port=XXXX -o 'IdentityFile="/root/snap/semaphore/common/repositories/access_key_529537282"' -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o 'User="cnctedsema"' -o ConnectTimeout=10 -o 'ControlPath="/root/snap/semaphore/common/repositories/.ansible/cp/be28846edb"' /tmp/ansible-local-2969qekpl_8t/tmpbvrn3p_o '[X.X.X.X]:/tmp/ansible-tmp-1686988003.6962752-2975-257643154070795/AnsiballZ_setup.py'
```

Please find the [full log here](https://is.gd/27egOo).

The `test.yml` file contains:

```
- hosts: debian11
  become: true
  become_user: root
  tasks:
    - name: Update apt repo and cache on all Debian/Ubuntu boxes
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Upgrade all packages on servers
      apt: upgrade=dist force_apt_get=yes
```

Also please see this (I suppose unrelated?) error as well:

```
[WARNING]: An error occurred while calling ansible.utils.display.initialize_locale (unsupported locale setting). This may result in incorrectly calculated text widths that can cause Display to print incorrect line lengths.
```

Any hints?
