### ISSUE TITLE
How does environment variables supposed to work? It does not work for me. 

### ISSUE THREAD

**Issue by whoisnobody** [ansible-semaphore/semaphore#1300]
I have a very simple use case scenario and I cannot make environments variables to be passed to my playbook. Vars are working correctly. 

Environment config:
![obraz](https://github.com/ansible-semaphore/semaphore/assets/63454966/c25afc6f-1d3c-402c-9757-81deba0217c4)

Playbook:
```
- name: "Run"
  hosts: hosts
  roles:
    - run
  environment:
    ENV_TO_TEST: "changeit"
  vars:
    variable_to_test: "changeit"
```

`variable_to_test` is being replaced as expected with "test1" value.
`ENV_TO_TEST` stays with value "changeit". It is not being replaced by the env defined in the semaphore. 

Do I misunderstand something regarding environments functionality? Unfortunately I cannot find any info in docs about how does it work in deep.
