### ISSUE TITLE
docker_image build task results in connection error

### ISSUE THREAD

**Issue by TheRealVira** [ansible-semaphore/semaphore#1310]
### Issue
`docker_image` build task results in "connection error" even though `docker` is installed and Dockerfile is present.
### Log
```
[...]
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error connecting: Error while fetching server API version: ('Connection aborted.', FileNotFoundError(2, 'No such file or directory'))"}
[...]
```
### Semaphore Dockerfile
```
FROM semaphoreui/semaphore:latest
USER root
RUN /sbin/apk add \
    rsync \
    docker \
    py3-pip \
    py3-requests \
    py3-dockerpty
USER semaphore
RUN pip3 install requests
```
### build-container-img.yaml
```
---
- hosts: localhost
  connection: local
  tasks:
    - name: Setup temp build directory
      file:
        state: directory
        path: /tmp/build
        mode: '0777'

    - name: Copy dockerfile
      copy:
        src: "../../../{{IMAGE_NAME}}/build/Dockerfile"
        dest: "/tmp/build/Dockerfile"
        mode: '0777'

    - name: Build container image
      docker_image:
        name: "{{IMAGE_NAME}}:vira-latest"
        build:
          path: "/tmp/build"
          dockerfile: "Dockerfile"
        source: build
        state: present
```
### Terminal
```
/tmp/build # ls -la
total 16
drwxrwxrwx    2 semaphor root          4096 Jul  2 18:15 .
drwxrwxrwt    1 root     root          4096 Jul  2 18:15 ..
-rwxrwxrwx    1 semaphor root           162 Jul  2 18:15 Dockerfile
```
### Repository Setup
```
└───semaphore
    ├───build
    │       Dockerfile
    └───playbooks
        ├───build
        │       build-container-img.yaml
```
