### ISSUE TITLE
Ansible Collection not working

### ISSUE THREAD

**Issue by cardosocristian** [ansible-semaphore/semaphore#1331]
I have a Rocky Linux 9 server and I installed the rpm version 2.8.90 and configured it to run tasks from a repository in my internal gitlab.
To run the test task I created, I need the fortinet.fortios collection to work correctly for the playbooks available in my repository.

I created the repository in the collections/requirements.yml directory but when running the task, I always get the alert:
**_"No collections/requirements.yml file found. Skip galaxy install process."_**

My file is as follows:
```
---
collections:
  # Install a collection from Ansible Galaxy.
  - name: fortinet.fortios
    version: ">=2.3.0"
    source: https://galaxy.ansible.com/fortinet/fortios
```

I also tried another way:

```
---
collections:
With the collection name, version, and source options
name: fortinet.fortios version: "2.3.0"
```
And also that way:
```
---
collections:
- name: fortinet.fortios
- name: ansible.netcommon
```

All without success, always receiving the same feedback reported at the beginning of this issue.

Is there any way to debug how this works or something I can do to try and force the file to be read?
