### ISSUE TITLE
[LDAP] web ui  tell that login failed while logs tell authorized via LDAP correctly !

### ISSUE THREAD

**Issue by bioinfornatics** [ansible-semaphore/semaphore#1341]
Dear,

I created this docker-compose.yml file

```yaml
---
version: '3'
services:
  db:
    image: mariadb:11.0.2
#    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${MYSQL_DATABASE}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
    volumes:
      - "${SEMAPHORE_HOME}/var/lib/mysql:/var/lib/mysql:rw"
    ports:
      - '3306:3306'
    networks:
      - semaphore
    restart: 'on-failure'
  semaphore:
    ports:
      - '8100:3000'
    image: 'semaphoreui/semaphore:v2.8.91'
    container_name: 'semaphore'
    user: "0:0"
    environment:
      SEMAPHORE_DB_USER: "${MYSQL_USER}"
      SEMAPHORE_DB_PASS: "${MYSQL_PASSWORD}"
      SEMAPHORE_DB_HOST: db
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: "${MYSQL_DATABASE}"
      SEMAPHORE_PLAYBOOK_PATH: "${SEMAPHORE_PLAYBOOK_PATH}"
      SEMAPHORE_ADMIN_PASSWORD: "${SEMAPHORE_ADMIN_PASSWORD}"
      SEMAPHORE_ADMIN_NAME: "${SEMAPHORE_ADMIN}"
      SEMAPHORE_ADMIN_EMAIL: "${SEMAPHORE_ADMIN_EMAIL}"
      SEMAPHORE_ADMIN: "${SEMAPHORE_ADMIN}"
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "${SEMAPHORE_ACCESS_KEY_ENCRYPTION}"
      SEMAPHORE_LDAP_ACTIVATED: 'yes'
      SEMAPHORE_LDAP_HOST: "${LDAP_HOST}"
      SEMAPHORE_LDAP_PORT: "${LDAP_PORT}"
      SEMAPHORE_LDAP_DN_SEARCH: "${LDAP_DN_SEARCH}"
      SEMAPHORE_LDAP_DN_BIND: "${SEMAPHORE_LDAP_DN_BIND}"
      SEMAPHORE_LDAP_PASSWORD: "${SEMAPHORE_LDAP_PASSWORD}"
      SEMAPHORE_LDAP_SEARCH_FILTER: "${SEMAPHORE_LDAP_SEARCH_FILTER}"
      SEMAPHORE_LDAP_MAPPING_DN: "${SEMAPHORE_LDAP_MAPPING_DN}"
      SEMAPHORE_LDAP_MAPPING_USERNAME: "${SEMAPHORE_LDAP_MAPPING_USERNAME}"
      SEMAPHORE_LDAP_MAPPING_FULLNAME: "${SEMAPHORE_LDAP_MAPPING_FULLNAME}"
      SEMAPHORE_LDAP_MAPPING_EMAIL: "${SEMAPHORE_LDAP_MAPPING_EMAIL}"
    volumes:
      - "${SEMAPHORE_HOME}/playbook:${SEMAPHORE_PLAYBOOK_PATH}:rw"
      - "${SEMAPHORE_HOME}/config:/etc/semaphore:rw"
    networks:
      - semaphore
    depends_on:
      - db
networks:
  semaphore:
    name: semaphore-network
```

Note: some vars are defined from `.env` file

while trying to login I have a 401 error

![screenshot](https://github.com/ansible-semaphore/semaphore/assets/491720/2f698735-2fe6-4534-bcd6-f021cb3e0aea)

And logs at same time
```
time="2023-07-13T00:42:00Z" level=info msg="User jonathan with email jonathanxxxxxxx@xxxx.com authorized via LDAP correctly"
```

did you have an idea where to look ?

Note: indeed I checked credential through ldapsearch

```
$ ldapsearch -x  -W -b "${SEMAPHORE_LDAP_DN_SEARCH}" -D "${SEMAPHORE_LDAP_DN_BIND}" -H ldap://${SEMAPHORE_LDAP_HOST}:${SEMAPHORE_LDAP_PORT}
```

Thanks best regards
