### ISSUE TITLE
How to add additional Python library dependencies?

### ISSUE THREAD

**Issue by robschm** [ansible-semaphore/semaphore#1346]
Hi,
how do I add python library dependencies, if I used the package manager installation method (rpm file)?
Apparently you can create a Dockerfile to add dependencies when using docker.

Installing the python libraries on the system python does not seem to work.

**Comment by ansibleguy** [comment]
Greetings.

As far as I can tell/reproduce it on a debian-based system: When installing it this way you have to run the Semaphore process manually or add a service to run it as daemon.
Either way - in a stable setup you should create and use a dedicated 'serviceuser' to run it.
The answer would be to install the dependencies in the context of that 'serviceuser'. (optimally using a [virtual-environment](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/))

You can see an ansible-based example of how I am doing this in one of my repositories: https://github.com/ansibleguy/sw_semaphore/blob/latest/tasks/debian/install.yml

\- AnsibleGuy

**Comment by dgibbs64** [comment]
Here is a dockerfile I have put together that might help.
```
FROM semaphoreui/semaphore:latest

USER root
RUN apk add --no-cache python3 py3-pip
RUN pip install pywinrm jmespath netaddr passlib requests matrix_client

USER semaphore
```
Related #1198

**Comment by ansibleguy** [comment]
@dgibbs64 FYI: OP asked for RPM-based installation
@robschm You could also give my docs-PR a read: [Manual Installation](https://github.com/ansibleguy/ansible-semaphore-docs/blob/manual-setup-docs/administration-guide/installation_manually.md)
Maybe it can help you solve your issues.

**Comment by devedse** [comment]
I would love to have some way of installing these packages too, so +1 from me.

Maybe per environment/repo/inventory you should be able to specify some dependencies?
@fiftin , is this something you could take a look at too 😄


P.s. if anyone wants my hacky solution that doesn't require creating a new docker image:

1. I went into the container `docker exec -it /bin/sh semaphore-semaphore-1`
1. I installed `apk add --no-cache python3 py3-pip`
1. I copied out the files from the container to my host (netaddr in `/usr/lib/netaddr` and `/usr/lib/python3.11/site-packages/netaddr`)
1. I mapped those files in the docker-compose file below
1. Hacky af but it works

```
version: "3.8"
services:
  semaphore:
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:v2.9.18
    user: "0:0"
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN_PASSWORD: blah
      SEMAPHORE_ADMIN_NAME: blah
      SEMAPHORE_ADMIN_EMAIL: blah@gmail.com
      SEMAPHORE_ADMIN: blah
    volumes:
      - /home/pi/dockercomposers/semaphore/home:/etc/semaphore
      - /home/pi/dockercomposers/semaphore/lib:/var/lib/semaphore
      - /home/pi/dockercomposers/semaphore/netaddr_install_files/netaddr:/usr/bin/netaddr
      - /home/pi/dockercomposers/semaphore/netaddr_install_files/sitepackages_netaddr:/usr/lib/python3.11/site-packages/netaddr
    restart: unless-stopped
```
