### ISSUE TITLE
Setup script fails when there are whitespaces in config

### ISSUE THREAD

**Issue by teronavt** [ansible-semaphore/semaphore#1370]
Hey,
I'm running Semaphore v2.8.90 and experiencing an issue with setup script when there are whitespaces in config.
For example when i try to set up the LDAP DN that have a whitespace it gives the `expected newline` warning and skips the next input:
```
LDAP DN for bind (default cn=user,ou=users,dc=example): cn=user,ou=user accounts,dc=example                                           
WARN[0041] An input error occurred: expected newline    

Password for LDAP bind user (default pa55w0rd): << this input is skipped
LDAP DN for user search (default ou=users,dc=example): "ou=user accounts,dc=example"
WARN[0066] An input error occurred: expected newline    

LDAP search filter (default (uid=%s)): << this input is skipped
LDAP mapping for DN field (default dn):
```
Possible workaround for docker installation - mount an external `config.json` and override CMD in docker-compose.yml:
```
    command: ["/usr/local/bin/semaphore", "server", "--config", "/etc/semaphore/config.json"]
    volumes:
      - ./config.json:/etc/semaphore/config.json:ro
```

**Comment by arnausq77** [comment]
I have the same issue. 
I've noticed that at the moment the program reads the configuration, it uses the **fmt.Sscanln** function (located at semaphore/cli/setup/setup.go line 183) which filters out the white spaces. As a possible solution, I've seen that the program could use the **bufio.NewScanner** function, which does preserve the white spaces.

**Comment by msultanov** [comment]
The issue still exists in the current version (2.16.45)
I'm trying to pass LDAP settings using environment variables in Docker Swarm container
As a LDAP i'm using Microsoft Active Directory

```
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    hostname: semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ************
      SEMAPHORE_DB_HOST: mysql.corp.company.com
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: Semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: it@company.com
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: ************
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ************
      SEMAPHORE_LDAP_ACTIVATED: yes
      SEMAPHORE_LDAP_HOST: ad1-dc1.corp.company.com
      SEMAPHORE_LDAP_PORT: 389
      SEMAPHORE_LDAP_NEEDTLS: 'false'
      SEMAPHORE_LDAP_DN_BIND: CN=Semaphore Bind,OU=Service Users,DC=corp,DC=company,DC=com
      SEMAPHORE_LDAP_PASSWORD: ************
      SEMAPHORE_LDAP_DN_SEARCH: OU=Company Users,DC=corp,DC=company,DC=com
      SEMAPHORE_LDAP_SEARCH_FILTER: (&(objectClass=organizationalPerson)(sAMAccountName=%s))
      TZ: UTC
    networks:
      - traefik_global
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik_global"
        - "traefik.http.routers.semaphore.rule=Host(`semaphore.corp.company.com`)"
        - "traefik.http.routers.semaphore.entrypoints=web"
        - "traefik.http.routers.semaphore.service=semaphore-svc"
        - "traefik.http.services.semaphore-svc.loadbalancer.server.port=3000"
networks:
  traefik_global:
    external: true
```

As you can see, there are some whitespaces in BIND_DN and SEARCH_DN variables. And when I run the service, it starts with errors 

```
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Hello! You will now be guided through a setup to:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 1. Set up configuration for a MySQL/MariaDB database
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 2. Set up a path for your playbooks (auto-created)
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 3. Run database Migrations
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | 4. Set up initial semaphore user & password
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | What database to use:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    1 - MySQL
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    2 - BoltDB (DEPRECATED!!!)
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    3 - PostgreSQL
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |    4 - SQLite
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  (default 1):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db Hostname (default 127.0.0.1:3306):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db User (default root):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db Password:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | db Name (default semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Playbook path (default /tmp/semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Public URL (optional, example: https://example.com/semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable email alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable telegram alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable slack alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable Rocket.Chat alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable Microsoft Team Channel alerts? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable LDAP authentication? (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP server host (default localhost:389):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Enable LDAP TLS connection (yes/no) (default no):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP DN for bind (default cn=user,ou=users,dc=example):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Password for LDAP bind user (default pa55w0rd):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP DN for user search (default ou=users,dc=example):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP search filter (default (uid=%s)):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for DN field (default dn):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for username field (default uid):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for full name field (default cn):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | LDAP mapping for email field (default mail):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Config output directory (default /home/semaphore):
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Running: mkdir -p dn..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Configuration written to dn/config.json..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Loading config
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Validating config
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  Pinging db..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Running db Migrations..
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  > Username:  > Email:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  Welcome back, mail! (a user with this username/email is already set up..)
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  Re-launch this program pointing to the configuration file
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | ./semaphore server --config dn/config.json
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  To run as daemon:
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | nohup ./semaphore server --config dn/config.json &
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    |  You can login with cn or uid.
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | No additional python dependencies to install
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Starting semaphore server
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Loading config
semaphore_semaphore.1.wfcscfbjcum9@DCRSW1-M1    | Cannot Find configuration! Use --config parameter to point to a JSON file generated by `semaphore setup`.
``` 

The exact errors are here 

``` 
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
time="2025-12-15T16:52:23Z" level=warning msg="An input error occurred: expected newline"
``` 

It is even writing the config in the incorrect folder
>> Configuration written to dn/config.json..
