### ISSUE TITLE
The job runs and completes successfully, but not applied

### ISSUE THREAD

**Issue by S0b1t** [ansible-semaphore/semaphore#1374]
### What I did ?
I installed semaphore from [docs](https://docs.ansible-semaphore.com/administration-guide/installation#docker) and created a job to install the Portainer agent in a Docker container on my servers.

### What did I expect to see?
I was expecting to see Portainer Agent running on Docker Container

### What did I see instead?
Container does not run even if the job was completed successfully

This is my job:
![image](https://github.com/ansible-semaphore/semaphore/assets/87570847/972defd8-4fe2-42ed-9fbf-7b2c80ab1ce6)
![image](https://github.com/ansible-semaphore/semaphore/assets/87570847/e428d715-bfc9-49e9-a3cb-8be3930b6957)

### Playbook:
* portainer_agent_ansible_playbook/tasks/main.yml

```
---
# tasks file for portainer_agent_ansible_playbook
- name: Check if portainer agent network exists
  shell: docker network ls -q -f name="{{ network }}"
  register: portainer_agent_network
  ignore_errors: true

- name: Create "{{ network }}" docker network, if doesn't exist
  docker_network:
    name: "{{ network }}"
  when: portainer_agent_network.stdout_lines | length == 0

- name: Check if portainer_agent container exists
  shell: docker ps -q -f name="{{ name }}"
  register: portainer_agent_container
  ignore_errors: true

- name: Running Portainer Agent in Docker Container
  docker_container:
    name: "{{ name }}"
    image: "{{ image }}:{{ tag }}"
    volumes:
      - "{{ bind_volume }}:{{ container_volume }}"
      - "{{docker_sock_path}}:{{ docker_sock_path }}"
    ports:
      - "{{ default_external_port }}:{{ default_internal_port }}"
    restart_policy: "{{ restart }}"
    networks:
      - name: "{{ network }}"
  when: portainer_agent_container.stdout_lines | length == 0
```

portainer_agent_ansible_playbook/vars/main.yml
```
---
# vars file for portainer_agent_ansible_playbook
network: "my-network"
name: "portainer_agent"
image: "portainer/agent"
tag: 2.18.3
bind_volume: "/data/docker/volumes"
container_volume: "/var/lib/docker/volumes"
docker_sock_path: "/var/run/docker.sock"
default_external_port: 9001
default_internal_port: 9001
restart: "always"
hosts: TK-MVNO-001
```

run_playbook.yml
```
---
- hosts: "{{ hosts }}"
  become: yes

  roles:
    - portainer_agent_ansible_playbook
```

####  If I run my playbook with ``` ansible-playbook run_playbook.yml -K``` it works fine
![image](https://github.com/ansible-semaphore/semaphore/assets/87570847/67a275d3-511f-4c74-a81f-238c55ad807b)

#### Guess
As you can see in the screenshot, the semaphore skips some steps and the sequence is sometimes displayed incorrectly. I changed my playbook many times but the semaphore didn't change the playbook, I mean are there any caches?! I think they are the problem.
