### ISSUE TITLE
unclear documentation on how to use ansible.builtin.include_tasks and other file include modules

### ISSUE THREAD

**Issue by BPplays** [ansible-semaphore/semaphore#1414]
it doesn't seem to say in the docs how you're supposed to include tasks, vars, playbooks, etc.
putting in the file path of the file in the repo doesn't seem to work

**Comment by ansibleguy** [comment]
Greetings.

Semaphore is only executing a playbook.
Inside [the playbook you can import tasks, vars, etc.](https://docs.ansible.com/ansible/latest/getting_started/get_started_playbook.html)

If that does not help your use-case - please provide more context on what you are trying to achieve.

**Comment by BPplays** [comment]
sorry if i was unclear i want to use ```include_tasks: "file_path"``` within a playbook but im not sure how to reference files in the same repo

```yml
---
- name: example
  hosts: "all"

  tasks:
    - name: example include task
      include_tasks: "/_include/example.yml"
```
