### ISSUE TITLE
Issues with ~ and $HOME in Semaphore

### ISSUE THREAD

**Issue by Jaryllan** [ansible-semaphore/semaphore#1419]
I would like to raise an issue with ~ and $HOME is not referring to the user's home directory when executing with Semaphore. It is currently referring to /tmp/semaphore, which is wrong and leads to inconsistence behaviour compared to running on terminal.

Removal of the /tmp/semaphore path in the config file does not fix the issue either. Would prefer the ~ and $HOME to behave as it should.

**Comment by ansibleguy** [comment]
Greetings!
This is because Semaphore always sets it to the `TmpPath` (_with fallback to /tmp/semaphore_).
Code reference: [AnsiblePlaybook.go#L23](https://github.com/ansible-semaphore/semaphore/blob/develop/lib/AnsiblePlaybook.go#L23)
One would need to work around that functionality to get rid of this.
What if you 'just' set it to the actual home directory of the user running semaphore?

**Comment by Jaryllan** [comment]
We are okay for temporary files to be in the /tmp/semaphore. But we may need to access to the files in the respective user's home directory when the playbook executes.

For example 
Different users have their own .Kube folder for kubernetes and their own .ssh folder, we cannot share this or have this placed on the /tmp/semaphore folder.

**Comment by ansibleguy** [comment]
Greetings!
I agree that overriding $HOME/~ is not clean/transparent and can lead to unexpected behavior at runtime.
Also I don't see the need for this when running vanilla Ansible.

As clarification - so I understand your environment:
You are running multiple instances of semaphore in as multiple different users in kubernetes, yes?

@fiftin Could you note why we need this override? Is it just 'for comfort' so Semaphore does not need to use specific paths at different points?

**Comment by setola** [comment]
> Also I don't see the need for this when running vanilla Ansible.

Hello everybody,

I think I have a case for this: 

I'm trying to write a playbook that configures rclone for the user semaphore is running on. 

This requires some files in a folder inside the user home. Currently I'm using "~" on an ansible.builtin.file path inside a role.

Here's some code extrapolation:
```yaml
- name: Ensure rclone is installed
  ansible.builtin.package:
    name: rclone
    update_cache: true
  become: true

- name: Ensure rclone config directory exists
  file:
    path: "~/.config/rclone"
    state: "directory"
    mode: "0775"

- name: Add rclone config
  template:
    src: rclone.conf.j2
    dest: "~/.config/rclone/rclone.conf"
    mode: "0600"
```

Such role is applied on other hosts, where the absolute path of the home is different.

The playbook runs fine when run on my machine, but on semaphore I cannot configure rclone due to the $HOME override. I think this extends on every package which use some configuration files inside the user home.

I tried to override `ansible_remote_tmp: /home/semaphore` inside my inventory, but I don't think this will won over this [hardcoded line](https://github.com/semaphoreui/semaphore/blob/v2.10.22/db_lib/AnsiblePlaybook.go#L27)

I'm open to suggestion :)
Thanks, have a nice day guys
