### ISSUE TITLE
Authelia + Semaphore

### ISSUE THREAD

**Issue by alexsalex** [ansible-semaphore/semaphore#1426]
I saw in the docs the OpenID support. Do you have any docs for how to connect Semaphore with Authelia? Could somebody help?

**Comment by elliotmatson** [comment]
I set this up a few days ago, mostly the same way as the other apps in Authelia's docs. Here's the relevant sections of my config files for each: (generate the client_secret according to the Authelia docs, this also assumes that you have the rest of the oidc_providers section configured in Authelia already)

## Authelia config.yaml:
```yaml
identity_providers:
  oidc:
    - id: semaphore
      description: Semaphore
      secret: 'your_secret'
      public: false
      authorization_policy: two_factor
      redirect_uris:
        - https://semaphore.example.com/api/auth/oidc/authelia/redirect
      scopes:
        - openid
        - profile
        - email
      userinfo_signing_algorithm: none
```

## Semaphore config.json:
```json
"oidc_providers":  {
    "authelia": {
        "display_name": "Authelia",
        "provider_url": "https://authelia.example.com",
        "client_id": "semaphore",
        "client_secret": "your_secret",
        "redirect_url": "https://semaphore.example.com/api/auth/oidc/authelia/redirect"
    }
},
```
