### ISSUE TITLE
How to use survey variables and hosts inventory

### ISSUE THREAD

**Issue by Sehyn** [ansible-semaphore/semaphore#1438]
Hi, I have a setup where I need to deploy an openstack VM then I retrieve the IP Adress and want to execute an playbook on that VM.

I would have wanted to:

Clone my github repository that contains:

playbook.yml
hosts

and when I want to execute the task on Semaphore, it would ask for a VM_IP field, and the playbook will retrieve that IP to performs the tasks.

I've been stuck for awhile and couldn't find a solution could anyone show me an example with placeholder text to do this?
Thank you.

**Comment by craigarms** [comment]
Hi,

You will need a Playbook with 2 plays, the first one would use the [add_host ](https://docs.ansible.com/ansible/latest/collections/ansible/builtin/add_host_module.html) module to add the "{{ VM_IP }}" to you inventory.

The second play would be able to use this.

It would look something along the line of this:
```
---
- name: Add the VM_IP var to the inventory
  hosts: localhost
  gather_facts: false

  tasks:
  - name: Add the VM_IP
     add_host:
       hostname: "{{ VM_IP }}"

- name: Second Play doing stuff on your VM_IP
  hosts: all

  tasks:
  - name: your tasks for VM_IP

etc...
```
