### ISSUE TITLE
Issue with root password

### ISSUE THREAD

**Issue by Karim-sigiz** [ansible-semaphore/semaphore#1445]
Hi, i have a problem with tests in my installation of semaphore. I don't understand what happening.
Install by instruction from here "https://computingforgeeks.com/install-semaphore-ansible-web-ui-on-ubuntu-debian/"
The point is. I did a playbook with only one task. It works in basic ansible. But when i am trying to use it in semaphore a have an error ```This command has to be run under the root user```
Creds are given from machine which should be updated. There are only one user admin/admin and this user have sudo. Task:
```
- name: ubuntu upgrade
      become: true
      apt:
        upgrade: yes
        update_cache: yes
```
ansible works with params: ``` ansible-playbook --ask-become-pass --ask-pass playbook.yml```. I am writing admin/admin and everything works. Why here is not? In data on my monitor command is the same.

What i did:
1) Create project
2) Copy playbook to directtory. configure repository like file://<full_path from />
3) Create a user credentianls like login-password admin/admin
4) Create Empty environment like {}
5) Create inventory ( user - credentials, sudo the same, static machine -  ip of my machine)
6) Create Template Task. I am writing all what created before

P.S Sorry for errors, if i have. This is my first question at all. My english is not very good

**Comment by ansibleguy** [comment]
Greetings.

It's not clear to me what could trigger this error.
Could you please share a screenshot of your task-template and copy-paste a little more of the task-output you are seeing?
Maybe also test-tasks before the 'apt' one:
```yaml
- name: Just a test
  ansible.builtin.debug:
    msg: "It's such a nice evening"
  become: false

- name: But now..
  ansible.builtin.debug:
    msg: "OR IS IT?"
  become: true
```
