### ISSUE TITLE
Official docker image

### ISSUE THREAD

**Issue by tokuhirom** [ansible-semaphore/semaphore#148]
If there's an official docker image, user can try ansible-semaphore more easily.

**Comment by matejkramny** [comment]
Thats version 1 though.

**Comment by dsmorse** [comment]
Building the docker image and the docker compose file to bring up both containers is pretty easy.  I have a prototype working (I will share it soon) but the problem I've discovered is that the -setup command wants a connection to the db so that it can write the default user directly to the DB... if there was a way to create a file with the username, email, name and password that would then be loaded into the DB when the container starts up making single docker compose file would be trivial.

Currently I created the semaphore container. Start the mysql with a volume mount to store the db data then start the semaphore container and override the run command to execute the setup, then I can use the standard docker compose to get the system up

**Comment by dsmorse** [comment]
here is a link to my docker wrapper:
 https://github.com/dsmorse/semaphore-docker

**Comment by dsmorse** [comment]
Excellent idea...   I have a working docker image now at: https://hub.docker.com/r/dsmorse/semaphore-docker/ and the docker compose file in in the original github link

**Comment by dsmorse** [comment]
OK I guess my docker wrapper is not yet ready for prime time... While it fires up OK it can't clone from a repo... I'll be working on it.

**Comment by goozbach** [comment]
I've done my take on it.

https://github.com/goozbach/semaphore/tree/dockerfiles

I've got an issue with the SSL termination using the Nginx proxy (it works but doesn't update the actual run).

**Comment by goozbach** [comment]
Figured out the websockets proxy issue, my pull request is #178

**Comment by surak** [comment]
There's an official docker image as of 2021, but I have no idea how to make it run.

**Comment by fiftin** [comment]
Docker compose example:

```
version: '2'

services:
  mysql:
    image: mariadb:10
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore

  semaphore:
    image: ansiblesemaphore/semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /etc/semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: "Developer"
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_WEB_ROOT: http://192.168.185.10:3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
```

**Comment by ziptx** [comment]
Try specifying a database version _below_ MariaDB 10.6.   There seems to be a breaking bug in 10.6.  See bug #681

**Comment by robinlennox** [comment]
Docker Compose Example to get around bug #681 

Note: Need to use 10.4 until the bug is fixed.

```
version: '3'

services:
  mysql:
    image: mariadb:10.4
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore

  semaphore:
    image: ansiblesemaphore/semaphore
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /etc/semaphore
      SEMAPHORE_ADMIN_PASSWORD: password
      SEMAPHORE_ADMIN_NAME: "Developer"
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_WEB_ROOT: http://127.0.0.1:3000
    ports:
      - "3000:3000"
    depends_on:
      - mysql
```
