### ISSUE TITLE
email alert does not working in docker compose

### ISSUE THREAD

**Issue by kimnami** [ansible-semaphore/semaphore#1511]
I've set environment variables in docker compose yaml file and turned on the alert button in UI. 
But I've got nothing. No email alert and even no any error log.
I think I've done everything to get alerts. What else should i do?

- in my docker compose yaml
  - tested this with version 2.9.4 and 2.9.37
```yaml
...
    environment:
 ...
      SEMAPHORE_EMAIL_HOST: MY_SMTP_SERVER
      SEMAPHORE_EMAIL_PORT: 25
      SEMAPHORE_EMAIL_SENDER: MY_SENDER
      SEMAPHORE_EMAIL_ALERT: true
...
```
- in docker container
<img width="781" alt="Pasted Graphic 2" src="https://github.com/ansible-semaphore/semaphore/assets/22041482/8bc80791-6c68-46ec-a8ce-175f3ecbd0ed">

- but in config.json
<img width="902" alt="Pasted Graphic 1" src="https://github.com/ansible-semaphore/semaphore/assets/22041482/3776f447-4dec-405b-9d61-32a60ff0a98f">

The other configurations (like mysql db host, port etc  ..) is set in config.json through docker-compose environment variables.
But email stuffs are not set.
