### ISSUE TITLE
LDAP login issue

### ISSUE THREAD

**Issue by DevAlphaKilo** [ansible-semaphore/semaphore#1522]
## Issue

After upgrading my docker image to **2.9.37**, while attempting to login, I receive a 500 error and am not able to login with either my ***ldap*** or ***local*** user accounts. 

![image](https://github.com/ansible-semaphore/semaphore/assets/44307521/97d78c6e-8893-449e-96f3-312cc36fb6ad)

I receive this error in the contain logs:
`time="2023-09-27T13:20:12Z" level=warning msg="unable to read LDAP response packet: unexpected EOF"`

The same error is generated when using either ***ldap*** or ***local*** user accounts to perform the login. When using **v2.9.4** I am able to login successfully with my LDAP credentials as expected.

No other changes were made in the environment.

#### Sad Path
- Upgrade to **v2.9.37** in docker compose file
- Recreate stack
- Attempt to login
- Receive 500 error
#### Happy Path
- Switch docker compose file to target **v2.9.4**
- Recreate stack
- Attempt to login
- Success

## Configuration

This is what my docker stack looks like:

```yaml
  semaphore:
    depends_on:
      - mysql
    image: semaphoreui/semaphore:v2.9.4
    hostname: semaphore
    restart: unless-stopped
    environment:
      SEMAPHORE_DB_USER: *redacted*
      SEMAPHORE_DB_PASS: *redacted*
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB_DIALECT: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN: local_admin
      SEMAPHORE_ADMIN_NAME: local_admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN_PASSWORD: *redacted*
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: *redacted*
      SEMAPHORE_LDAP_ACTIVATED: 'yes'
      SEMAPHORE_LDAP_HOST: *redacted*
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: *redacted*
      SEMAPHORE_LDAP_PASSWORD: *redacted*
      SEMAPHORE_LDAP_DN_SEARCH: *redacted*
      SEMAPHORE_LDAP_SEARCH_FILTER: *redacted*
```

## Resolution

- Switch docker compose file to target **v2.9.4**
- Recreate stack

Downgrading to **2.9.4** appears to fix the issue and allows me to login again.
