### ISSUE TITLE
Interface Survey Variables Issue

### ISSUE THREAD

**Issue by OliPou** [ansible-semaphore/semaphore#1533]
Hi team,

I use the `Survey Variables` section to define my hosts like this:
```yml
- name: PLaybook Title
  hosts: "{{ host_to_update | default('all') }}"
  gather_facts: true
  tasks:
...
```
Recently, I discovered that when I rerun the Ansible Semaphore interface and remove a variable that I had previously set (such as removing the host to deploy to all hosts), it sets the variable to an empty string and causes my play to crash. Is this behavior normal?

Regards,
