### ISSUE TITLE
While a task is running, barely can access UI

### ISSUE THREAD

**Issue by kimnami** [ansible-semaphore/semaphore#1543]
While a task is running, UI is too slow.
When I refresh the browser, I can see the blue waiting bar and I get "page unresponsive" every time.
Whenever that happens, I shoud exit pages and re-access the url.
Any advice? 😢 

<img width="1467" alt="스크린샷 2023-10-03 오후 9 55 21" src="https://github.com/ansible-semaphore/semaphore/assets/22041482/fef9a78a-b7f3-464b-b7be-7e93d872dcd1">

**Comment by kimnami** [comment]
I checked the process count. In `(1) trial`, about 100 processes ran for a task parallelly. But in `(2) trial` under 10 processes! Should I set sth up to control the number of processes per task?

**Comment by kimnami** [comment]
I guess I should check `forks` option first😅

**Comment by DevAlphaKilo** [comment]
This occasionally happens to me but have found that it is a limitation of hardware, not the software. What type of hardware are you running on? I use a Raspberry Pi 4 and docker, the choke point is the read/write of the SD card, causing the software to occasionally hang under heavy load. Usually this is only temporary and the jobs are still executing in the background.

**Comment by kimnami** [comment]
@DevAlphaKilo 
I use a linux server.. It has enough resources 😢 
For example, it has 48 core cpu, whenever I check, the usage is always under 20%. 
And semaphore is running on docker compose without resource limit options.

Like you said, executing tasks is not a problem, but the problem is the usability of UI.
Specifically, I think it's a problem if I refresh while looking at the running task log screen or close the log screen and refresh.

Thanks for the comment anyway!

**Comment by DevAlphaKilo** [comment]
@kimnami  
**Wow!** Sounds like in your case **hardware resources are not the constraint**.

Please post a sample of your compose file if possible, redact as needed.

### Troubleshooting Questions:

- Are you seeing any issues/errors in the container logs? If so, please provide sample logs if possible.

- What database are you using? (MySQL, PostgreSQL, BoltDB)

- Is the database local to the compose stack?

- Which version of Semaphore are you running in your compose file? 

- Have you tried downgrading to a lower version to see if the problem persists?

**Comment by kimnami** [comment]
Here's my compose file which is partially redacted with capital words.

```yaml
version: "3.7"          
x-common-variables:                 
  SEMAPHORE_VOLUME: &SEMAPHORE_VOLUME     
    type: bind                 
    source: MY_LOCAL_PATH
    target: /tmp/semaphore                
services:               
  semaphore:            
    restart: unless-stopped               
    ports:              
      - 3000:3000       
    image: PRIVATE_REG/semaphoreui/semaphore:v2.9.37  
    environment:        
      SEMAPHORE_DB_USER: semaphore        
      SEMAPHORE_DB_PASS: semaphore        
      SEMAPHORE_DB_HOST: MYSQL_IP_ADDR # for postgres, change to: postgres            
      SEMAPHORE_DB_PORT: 13306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres         
      SEMAPHORE_DB: semaphore             
      SEMAPHORE_EMAIL_HOST: SMTP_SERVER_ADDR      
      SEMAPHORE_EMAIL_PORT: 25            
      SEMAPHORE_EMAIL_SENDER: EMAIL_ADDR
      SEMAPHORE_EMAIL_ALERT: true         
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/              
      SEMAPHORE_ADMIN_PASSWORD: PASSWD          
      SEMAPHORE_ADMIN_NAME: admin         
      SEMAPHORE_ADMIN_EMAIL: EMAIL_ADDR
      SEMAPHORE_ADMIN: admin              
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ACCESS_KEY_ENCRYPTION
      SEMAPHORE_WEB_ROOT: WEB_ROOT
      ANSIBLE_HOST_KEY_CHECKING: "false"  
      ANSIBLE_REMOTE_USER: "REMOTE_USER"     
      ANSIBLE_FORKS: 50 
      ANSIBLE_CALLBACKS_ENABLED: "profile_tasks"            
      ANSIBLE_GATHERING: "explicit"       
      ANSIBLE_PIPELINING: "true"          
    volumes:            
      - *SEMAPHORE_VOLUME   
```

> - Are you seeing any issues/errors in the container logs? If so, please provide sample logs if possible.

Below errors time to time happen but this is not the direct cause of the problem I guess.
```
time="2023-10-03T12:43:40Z" level=info msg="Task 21 added to queue"
time="2023-10-03T12:43:44Z" level=info msg="Set resource locker with TaskRunner 21"
time="2023-10-03T12:43:44Z" level=info msg="Task 21 removed from queue"

time="2023-10-03T12:44:30Z" level=error msg="write tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:33932: use of closed network connection" level=Error
time="2023-10-03T12:44:30Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:33932: use of closed network connection" level=Error
time="2023-10-03T12:48:20Z" level=error msg="write tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:34816: i/o timeout" level=Error
time="2023-10-03T12:48:20Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:34816: use of closed network connection" error="Error closing websocket"

time="2023-10-03T12:54:45Z" level=error msg="websocket: close sent" level=Error
time="2023-10-03T12:54:45Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:33934: use of closed network connection" level=Error
time="2023-10-03T12:56:29Z" level=error msg="write tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:36160: i/o timeout" level=Error
time="2023-10-03T12:56:29Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:36160: use of closed network connection" error="Error closing websocket"

time="2023-10-03T12:59:55Z" level=error msg="write tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:33986: use of closed network connection" level=Error
time="2023-10-03T12:59:55Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:33986: use of closed network connection" level=Error
time="2023-10-03T13:02:12Z" level=info msg="Stopped running TaskRunner 21"
time="2023-10-03T13:02:12Z" level=info msg="Release resource locker with TaskRunner 21"

time="2023-10-03T13:03:00Z" level=error msg="websocket: close sent" level=Error
time="2023-10-03T13:03:00Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:37394: use of closed network connection" level=Error

time="2023-10-04T02:37:00Z" level=error msg="websocket: close sent" level=Error
time="2023-10-04T02:37:00Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:55742: use of closed network connection" level=Error

time="2023-10-04T02:37:29Z" level=error msg="websocket: close sent" level=Error
time="2023-10-04T02:37:29Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:55850: use of closed network connection" level=Error

time="2023-10-04T02:38:16Z" level=error msg="websocket: close sent" level=Error
time="2023-10-04T02:38:16Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:55988: use of closed network connection" level=Error

time="2023-10-04T02:50:58Z" level=error msg="websocket: close sent" level=Error
time="2023-10-04T02:50:58Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:56130: use of closed network connection" level=Error

time="2023-10-04T02:50:58Z" level=error msg="websocket: close sent" level=Error
time="2023-10-04T02:50:58Z" level=error msg="close tcp SEMAPHORE_CONTAINER_ADDR:3000->NGINX_SERVER_ADDR:56318: use of closed network connection" level=Error
```
> - What database are you using? (MySQL, PostgreSQL, BoltDB)

MySQL

> - Is the database local to the compose stack?

No. It's running on another server.

> - Which version of Semaphore are you running in your compose file?

v2.9.37 the latest one

> - Have you tried downgrading to a lower version to see if the problem persists?

Haven't tried yet! Maybe I should

I guess it only happens when the output's a lot.
The problematic task has 170000 lines' output.
When I execute a task that has 30 lines' output, it's all alright.
Maybe I should set  a `no_log` option or sth for the task that produce too much lines?
