### ISSUE TITLE
Can't execute scripts on localhost

### ISSUE THREAD

**Issue by Pshemas** [ansible-semaphore/semaphore#1554]
I'm trying to write a playbook that would run on a localhost. Outside Sempahore it works and returns "changed" result. But when run from Semaphore I get "skipped" status. 

Any ideas howto make it work from Semaphore?

Here's a sample playbook

```
---
- name: looping on localhost
  hosts:
    - 127.0.0.1

  tasks:
    - name: echo loop
      shell:
        cmd: echo {{ item }}
      loop:
        - 192.168.10.181
        - 192.168.10.182
        - 192.168.10.192
    - name: ping loop
      shell:
        cmd: ping {{ item }} -c 3
      loop:
        - 192.168.10.181
        - 192.168.10.182
        - 192.168.10.192
...

```

Here's what I get when running it on Semaphore:

```
 7:44:57 PM
PLAY [Pobierz fingerprint SSH] *************************************************
7:44:57 PM
7:44:57 PM
TASK [Gathering Facts] *********************************************************
7:44:59 PM
ok: [127.0.0.1]
7:44:59 PM
7:44:59 PM
TASK [add fingerprint to known_hosts] ******************************************
7:45:00 PM
skipping: [127.0.0.1] => (item=192.168.10.181)
7:45:00 PM
skipping: [127.0.0.1] => (item=192.168.10.182)
7:45:00 PM
skipping: [127.0.0.1] => (item=192.168.10.192)
7:45:00 PM
skipping: [127.0.0.1]
7:45:00 PM
7:45:00 PM
TASK [add fingerprint to known_hosts] ******************************************
7:45:01 PM
skipping: [127.0.0.1] => (item=192.168.10.181)
7:45:01 PM
skipping: [127.0.0.1] => (item=192.168.10.182)
7:45:01 PM
skipping: [127.0.0.1] => (item=192.168.10.192)
7:45:01 PM
skipping: [127.0.0.1]
7:45:01 PM
7:45:01 PM
PLAY RECAP *********************************************************************
7:45:01 PM
127.0.0.1 : ok=1 changed=0 unreachable=0 failed=0 skipped=2 rescued=0 ignored=0 
```
