### ISSUE TITLE
Run a task against one server out of inventory -> like limit

### ISSUE THREAD

**Issue by mikch06** [ansible-semaphore/semaphore#1611]
It should be possible to create a tasks and limit it against a single host out of inventory. If possible by Dropdown or just with the written hostname. 
- Now you have to run a playbook against the whole inventory.
- This is a feauture request more from system engineering side where we run a few small jobs against single hosts.

**Comment by rwaffen** [comment]
I have a workaround for this:

add the hosts line to your playbooks:

```yaml
---
- name: Add logrotate configuration for docker logs
  hosts: "{{ target_hosts | default('all') }}"
  tasks:
```

and then add a survey variable in semaphore to your template.
