### ISSUE TITLE
mysql/mariadb tls connection

### ISSUE THREAD

**Issue by markuman** [ansible-semaphore/semaphore#1612]
https://github.com/ansible-semaphore/semaphore/blob/85d9936082bc8a3fc763ff8d3f1f6a6695bfc956/cli/setup/setup.go#L97

Is it possible to use a tls connection?

**Comment by markuman** [comment]
As a workaround, we deployed a local proxysql on the same instance, that made the tls connection while semaphore connects to localhost.

```yml
        - name: "mariadb writer node"
          community.proxysql.proxysql_backend_servers:
            login_user: admin
            login_password: admin
            state: present
            hostgroup_id: 10
            hostname: abc.eu-central-1.rds.amazonaws.com
            comment: mariadb writer endpoint
            use_ssl: true
            max_connections: 500
            port: 3306
            load_to_runtime: true
```
