### ISSUE TITLE
Assing users on per host basis - like in group_vars

### ISSUE THREAD

**Issue by philnewm** [ansible-semaphore/semaphore#1621]
I'm a bit confused by the way semaphore handles inventory <-> username combinations.
Maybe I'm just not understanding how things are meant to be used, but so far the docs also didn't really help me:

In Ansible I can create some files under **group_vars** using the names of my available hosts and define the ansible_user on a **per host basis**.
So each host can use a different username with easy, and it works just as expected.

In semaphore, I only see the option to assign the **credentials of one user** to an **entire inventory**. So basically locking me in to only use one user for all the hosts which does create quite some problems for my use case.

So I'd like to know how can I assign **different usernames per host** in semaphore, since this works in Ansible in general.

**Comment by oviliz** [comment]
Same here.

In my inventory.yml I have something like this:
```
all:
  children:
    dbs:
      hosts:
        mysql:
          ansible_host: 10.10.0.2
    elasticsearch:
      hosts:
        es01:
          ansible_host: 10.10.0.3
        es02:
          ansible_host:  10.10.0.4
        es03:
          ansible_host: 10.10.0.5
      vars:
        ansible_user: root
        ansible_ssh_private_key_file: '/home/oviliz/.ssh/oviliz_id_rsa'
    etc:
      hosts:
```

My inventory has multiple hosts I can SSH to with the same user while I have a few hosts I need to connect with a different user.

In the UI Inventory I have created a "static YAML" record with all my hosts choosing the main user as default.

The documentation at https://docs.ansible-semaphore.com/user-guide/inventory seems to suggest that we can add multiple users to an inventory as it states:
> Each Inventory also has at least one credential tied to it.

However, I can't figure out how...

**Comment by lbouriez** [comment]
Have you ever found a solution ?

**Comment by philnewm** [comment]
@lbouriez sadly not for now.
And since I currently don't necessarily need a web interface to manage my Ansible playbooks, I just skipped semaphore at this point.
Nonetheless, I'll check out the Ansible AWX web interface at some point, maybe it fits better for my use case.

**Comment by iCelo-git** [comment]
Same problem here.
My inventory file looks like this:
```
[group_name]
server_one 	     ansible_host=192.168.70.133 	ansible_user=user_one
server_two 		ansible_host=192.168.70.43 	ansible_user=user_two
server_three 	     ansible_host=192.168.70.45 	ansible_user=user_three
```
As I try to run the playbook to only ping the servers I see that it uses the user from the localhost machine. It's ignoring the variables from the inventory.

As I add the ansible_user variable into enviroment it works but only for single server (because I can set one username here).
![image](https://github.com/ansible-semaphore/semaphore/assets/83703721/0fcd6b1f-9661-44b7-aadb-0792612a7d29)

Is there any workaround if it's not possible to just read the ansible_user from inventory file?

**Comment by jmartinezfl** [comment]
I had the same problem and I've been fighting for a while with the inventory configuration. In the end I managed to execute a task on two different hosts with different credentials.

The inventory setup that has finally worked for me has been something like this:
```yaml
group:
  hosts:
    first::
      ansible_host: 10.0.0.1
    second:
      ansible_host: 10.0.0.2
      ansible_ssh_user: 'user'
      ansible_ssh_password: 'pass'
```

In the UI I filled the _User Credential_ field with the saved credentials of the host named 'first'

I would like if instead of putting the password in the inventory you could define the path of the stored ssh key, but I haven't tried it
