### ISSUE TITLE
Docker container won't connect to database

### ISSUE THREAD

**Issue by coaxial** [ansible-semaphore/semaphore#1637]
With this docker-compose.yml:
```yaml
version: "3.4"
services:
  db:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgres/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/semaphore_db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/semaphore_db_password
    secrets:
      - semaphore_db_user
      - semaphore_db_password
    networks:
      - backend
    # image: mysql:8.0
    # volumes:
    #   - mysqldata:/var/lib/mysql
    # environment:
    #   MYSQL_USER_FILE: /run/secrets/semaphore_db_user
    #   MYSQL_PASSWORD_FILE: /run/secrets/semaphore_db_password
    #   MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    # secrets:
    #   - semaphore_db_user
    #   - semaphore_db_password
    # networks:
    #   - backend

  semaphore:
    image: semaphoreui/semaphore:v2.9.37
    environment:
      SEMAPHORE_DB_USER_FILE: /run/secrets/semaphore_db_user
      SEMAPHORE_DB_PASSWORD_FILE: /run/secrets/semaphore_db_password
      SEMAPHORE_DB_HOST: db
      SEMAPHORE_DB_PORT: 5432
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ACCESS_KEY_ENCRYPTION_FILE: /run/secrets/semaphore_ake
    depends_on:
      - db
    secrets:
      - semaphore_ake
      - semaphore_db_user
      - semaphore_db_password
    deploy:
      labels:
        traefik.enable: "true"
        traefik.http.routers.paperless-ngx-webserver.rule: "Host(`${TRAEFIK_FQDN}`)"
        traefik.http.routers.paperless-ngx-webserver.tls.domains[0].sans: "${TRAEFIK_SANS}"
        traefik.http.routers.paperless-ngx-webserver.tls.certResolver: "staging"
        traefik.http.services.paperless-ngx-webserver.loadbalancer.server.port: 3000
        traefik.http.services.paperless-ngx-webserver.loadbalancer.sticky.cookie.secure: "true"
    networks:
      - backend
      - traefik-net

networks:
  backend:
  traefik-net:
    external: true

secrets:
  semaphore_db_user:
    external: true
  semaphore_db_password:
    external: true
  semaphore_ake:
    external: true

volumes:
  pgdata:
  # mysqldata:
```

I get:
```
Attempting to connect to database semaphore on db:5432 with user semaphore ...
Generating /tmp/semaphore/config.stdin ...
...3
db:5432
semaphore
semaphore
semaphore
/tmp/semaphore

no
no
no
no
/etc/semaphore
admin
admin@localhost
admin
changeme

Hello! You will now be guided through a setup to:

1. Set up configuration for a MySQL/MariaDB database
2. Set up a path for your playbooks (auto-created)
3. Run database Migrations
4. Set up initial semaphore user & password

What database to use:
   1 - MySQL
   2 - BoltDB
   3 - PostgreSQL
 (default 1): 
db Hostname (default 127.0.0.1:5432): 
db User (default root): 
db Password: 
db Name (default semaphore): 
Playbook path (default /tmp/semaphore): 
Public URL (optional, example: https://example.com/semaphore): 
Enable email alerts? (yes/no) (default no): 
Enable telegram alerts? (yes/no) (default no): 
Enable slack alerts? (yes/no) (default no): 
Enable LDAP authentication? (yes/no) (default no): 
Config output directory (default /home/semaphore): 
Running: mkdir -p /etc/semaphore..
Configuration written to /etc/semaphore/config.json..
 Pinging db..
time="2023-11-18T14:50:49Z" level=warning msg="pq: password authentication failed for user \"semaphore\""
panic: pq: password authentication failed for user "semaphore"
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0xa831b7]

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Close(0x22fbc60?, {0x278b998?, 0xc0000a8f30?})
	/go/src/github.com/ansible-semaphore/semaphore/db/sql/SqlDb.go:263 +0x17
panic({0xb4c9a0, 0xc0000f6240})
	/usr/local/go/src/runtime/panic.go:884 +0x212
github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Connect(0xc000132710, {0xc000132008?, 0xc0000a9988?})
	/go/src/github.com/ansible-semaphore/semaphore/db/sql/SqlDb.go:290 +0xb05
github.com/ansible-semaphore/semaphore/cli/cmd.doSetup()
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:41 +0x17f
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func5(0x274f400?, {0xbf6e8e?, 0x1?, 0x1?})
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:23 +0x17
github.com/spf13/cobra.(*Command).execute(0x274f400, {0xc0001a9230, 0x1, 0x1})
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x274db00)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:37 +0x5b
main.main()
	/go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x17
```
