### ISSUE TITLE
subelements doesn't work with arrays in extra varibles

### ISSUE THREAD

**Issue by Plloi** [ansible-semaphore/semaphore#1644]
With this in environment extra vars:
```json
{
  "users": {
    "name": "plloi",
    "add_keys": [
      "<key to add>"
    ]
  }
}
```
And this task:

```yaml
- name: Add User SSH Keys
  ansible.posix.authorized_key:
    user: "{{ item.0.name }}"
    state: present
    key: "{{ item.1 }}"
  loop: "{{ users | subelements('add_keys', skip_missing=True) }}"
```

I get the following error:
```
 FAILED! => {"msg": "Unexpected templating type error occurred on ({{ users | subelements('add_keys', skip_missing=True) }}): the key add_keys should point to a dictionary, got '['<key to add>']'. the key add_keys should point to a dictionary, got '['<key to add>']'"}
 ```
 
 presently as a workaround i've added the relevant vars to inventory as:
 ```yaml
vars:
    users:
      - name: plloi
        add_keys:
          - <key to add>
```

Is there a fundamental difference between these approaches that I don't understand?
I would prefer to put this in environment extra vars for organizational purposes.
