### ISSUE TITLE
Various errors... No collections, No roles & unsupported locale setting

### ISSUE THREAD

**Issue by mc1903** [ansible-semaphore/semaphore#1646]
Very new to Ansible and thought Semaphore might make life a bit easier, but I am getting the following errors and I haven't a clue what to do.

```
4:04:17 PM	Task 36 added to queue
4:04:19 PM	Started: 36
4:04:19 PM	Run TaskRunner with template: Ping Spine Switches
4:04:19 PM	Preparing: 36
4:04:19 PM	Cloning Repository git@github.com:mc1903/Ansible.git
4:04:19 PM	Cloning into 'repository_11_21'...
4:04:19 PM	Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.
4:04:21 PM	installing static inventory
4:04:21 PM	No collections/requirements.yml file found. Skip galaxy install process.
4:04:21 PM	No roles/requirements.yml file found. Skip galaxy install process.
4:04:21 PM	ERROR: Ansible could not initialize the preferred locale: unsupported locale setting
4:04:21 PM	Running playbook failed: exit status 1
```

I have a static inventory.yml file in Semaphore

```
---

all:
  hosts:
    spine1:
      ansible_host: 10.1.0.11
      hostname: mc-dswi-v-spine1
      ansible_ssh_user: admin
      ansible_ssh_pass: admin
      ansible_network_os: dellemc.os10.os10
      ansible_connection: network_cli
    spine2:
      ansible_host: 10.1.0.12
      hostname: mc-dswi-v-spine2
      ansible_ssh_user: admin
      ansible_ssh_pass: admin
      ansible_network_os: dellemc.os10.os10
      ansible_connection: network_cli

```

I am trying a simple PING from a playbook downloaded from my GitHub Repo (ping.yml)

```
---

- name: Ping spine switches
  hosts: all
  tasks:
    - name: Ping spine switches
      ping:

```
Package manager/manual install.
```
semaphore@MC-ANSC-V-201:~$ ansible --version
ansible [core 2.15.6]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3/dist-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /usr/bin/ansible
  python version = 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] (/usr/bin/python3)
  jinja version = 3.0.3
  libyaml = True
semaphore@MC-ANSC-V-201:~$

semaphore@MC-ANSC-V-201:~$ semaphore version
v2.9.37
semaphore@MC-ANSC-V-201:~$

```

Where are the Semaphore logs saved? I don't see anything Semaphore related in /var/log/

What do I need for collections and roles in a requirements.yml file, where do I put it and what can I do about the 'unsupported locale setting' message?

Struggling... could someone point me in the right direction please?

Cheers,
M
