### ISSUE TITLE
Can't connect to MySQL, docker compose

### ISSUE THREAD

**Issue by wballoni** [ansible-semaphore/semaphore#1653]
Sorry for the length of this. I am trying to run the Semaphore docker image using docker compose (not docker-compose). Docker version 24.0.7, semaphore version latest (as of 27 Nov 2023), MySQL version 8.0.35. I am trying to get things running on a Pi 4.

My docker-compose.yml file is:

```
---
version: "3"

volumes:
  semaphore-mysql:
    driver: local

services:
  mysql:
    image: mysql:8.0
    hostname: mysql
    restart: unless-stopped
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=True
      - MYSQL_DATABASE=semaphore
      - MYSQL_USER=semaphore
      - MYSQL_PASSWORD=itsAsecret
  semaphore:
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:latest
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 3000:3000
    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=itsAsecret
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=itsAsecret
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=admin@localhost
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=itsAsecretToo
```

The first problem is that semaphore failed to write the config.json file:

```
ansiblesemaphore   | Running: mkdir -p /etc/semaphore..
ansiblesemaphore   | panic: open /etc/semaphore/config.json: permission denied
```

In order to get past this I had to open up the permissions on the config directory on the host (`chmod a+rwx config`). Doing this allows the directory to be written, not ideal! Any thoughts on this? 

The REAL frustrating issue is that semaphore cannot connect to the database. I get the following output from docker compose:

```
$ docker compose up
[+] Running 2/2
 ✔ Container semaphore-mysql-1  Created                                                                                                
 ✔ Container ansiblesemaphore   Created                                                                                                
Attaching to ansiblesemaphore, semaphore-mysql-1
semaphore-mysql-1  | 2023-11-27 16:52:38+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.35-1.el8 started.
ansiblesemaphore   | Attempting to connect to database semaphore on mysql:3306 with user semaphore ...
semaphore-mysql-1  | 2023-11-27 16:52:39+00:00 [Note] [Entrypoint]: Switching to dedicated user 'mysql'
semaphore-mysql-1  | 2023-11-27 16:52:39+00:00 [Note] [Entrypoint]: Entrypoint script for MySQL Server 8.0.35-1.el8 started.
semaphore-mysql-1  | '/var/lib/mysql/mysql.sock' -> '/var/run/mysqld/mysqld.sock'
semaphore-mysql-1  | 2023-11-27T16:52:40.273797Z 0 [Warning] [MY-011068] [Server] The syntax '--skip-host-cache' is deprecated and will be removed in a future release. Please use SET GLOBAL host_cache_size=0 instead.
semaphore-mysql-1  | 2023-11-27T16:52:40.278784Z 0 [System] [MY-010116] [Server] /usr/sbin/mysqld (mysqld 8.0.35) starting as process 1
semaphore-mysql-1  | 2023-11-27T16:52:40.298190Z 1 [System] [MY-013576] [InnoDB] InnoDB initialization has started.
semaphore-mysql-1  | 2023-11-27T16:52:41.220074Z 1 [System] [MY-013577] [InnoDB] InnoDB initialization has ended.
semaphore-mysql-1  | 2023-11-27T16:52:41.769165Z 0 [Warning] [MY-010068] [Server] CA certificate ca.pem is self signed.
semaphore-mysql-1  | 2023-11-27T16:52:41.769804Z 0 [System] [MY-013602] [Server] Channel mysql_main configured to support TLS. Encrypted connections are now supported for this channel.
semaphore-mysql-1  | 2023-11-27T16:52:41.779968Z 0 [Warning] [MY-011810] [Server] Insecure configuration for --pid-file: Location '/var/run/mysqld' in the path is accessible to all OS users. Consider choosing a different directory.
semaphore-mysql-1  | 2023-11-27T16:52:41.860429Z 0 [System] [MY-011323] [Server] X Plugin ready for connections. Bind-address: '::' port: 33060, socket: /var/run/mysqld/mysqlx.sock
semaphore-mysql-1  | 2023-11-27T16:52:41.861680Z 0 [System] [MY-010931] [Server] /usr/sbin/mysqld: ready for connections. Version: '8.0.35'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  MySQL Community Server - GPL.
ansiblesemaphore   | Generating /tmp/semaphore/config.stdin ...
ansiblesemaphore   | ...1
ansiblesemaphore   | mysql:3306
ansiblesemaphore   | semaphore
ansiblesemaphore   | itsAsecret
ansiblesemaphore   | semaphore
ansiblesemaphore   | /tmp/semaphore
ansiblesemaphore   | 
ansiblesemaphore   | no
ansiblesemaphore   | no
ansiblesemaphore   | no
ansiblesemaphore   | no
ansiblesemaphore   | /etc/semaphore
ansiblesemaphore   | admin
ansiblesemaphore   | admin@localhost
ansiblesemaphore   | admin
ansiblesemaphore   | itsAsecret
ansiblesemaphore   | 
ansiblesemaphore   | Hello! You will now be guided through a setup to:
ansiblesemaphore   | 
ansiblesemaphore   | 1. Set up configuration for a MySQL/MariaDB database
ansiblesemaphore   | 2. Set up a path for your playbooks (auto-created)
ansiblesemaphore   | 3. Run database Migrations
ansiblesemaphore   | 4. Set up initial semaphore user & password
ansiblesemaphore   | 
ansiblesemaphore   | What database to use:
ansiblesemaphore   |    1 - MySQL
ansiblesemaphore   |    2 - BoltDB
ansiblesemaphore   |    3 - PostgreSQL
ansiblesemaphore   |  (default 1): 
ansiblesemaphore   | db Hostname (default 127.0.0.1:3306): 
ansiblesemaphore   | db User (default root): 
ansiblesemaphore   | db Password: 
ansiblesemaphore   | db Name (default semaphore): 
ansiblesemaphore   | Playbook path (default /tmp/semaphore): 
ansiblesemaphore   | Public URL (optional, example: https://example.com/semaphore): 
ansiblesemaphore   | Enable email alerts? (yes/no) (default no): 
ansiblesemaphore   | Enable telegram alerts? (yes/no) (default no): 
ansiblesemaphore   | Enable slack alerts? (yes/no) (default no): 
ansiblesemaphore   | Enable LDAP authentication? (yes/no) (default no): 
ansiblesemaphore   | Config output directory (default /home/semaphore): 
ansiblesemaphore   | Running: mkdir -p /etc/semaphore..
ansiblesemaphore   | Configuration written to /etc/semaphore/config.json..
ansiblesemaphore   |  Pinging db..
ansiblesemaphore   | time="2023-11-27T16:52:42Z" level=warning msg="Error 1045: Access denied for user 'semaphore'@'172.19.0.3' (using password: YES)"
ansiblesemaphore   | panic: Error 1045: Access denied for user 'semaphore'@'172.19.0.3' (using password: YES)
ansiblesemaphore   | 	panic: runtime error: invalid memory address or nil pointer dereference
ansiblesemaphore   | [signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x5dd58c]
ansiblesemaphore   | 
ansiblesemaphore   | goroutine 1 [running]:
ansiblesemaphore   | github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Close(0x0?, {0x0?, 0x0?})
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/db/sql/SqlDb.go:263 +0x1c
ansiblesemaphore   | panic({0x684c80, 0x40000ec0a8})
ansiblesemaphore   | 	/usr/local/go/src/runtime/panic.go:884 +0x20c
ansiblesemaphore   | github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Connect(0x400000e718, {0x400000e018?, 0x400021d970?})
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/db/sql/SqlDb.go:290 +0x874
ansiblesemaphore   | github.com/ansible-semaphore/semaphore/cli/cmd.doSetup()
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:41 +0x120
ansiblesemaphore   | github.com/ansible-semaphore/semaphore/cli/cmd.glob..func5(0x22b6440?, {0x75a9b1?, 0x1?, 0x1?})
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/setup.go:23 +0x1c
ansiblesemaphore   | github.com/spf13/cobra.(*Command).execute(0x22b6440, {0x40001eb230, 0x1, 0x1})
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x4c4
ansiblesemaphore   | github.com/spf13/cobra.(*Command).ExecuteC(0x22b4b40)
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x360
ansiblesemaphore   | github.com/spf13/cobra.(*Command).Execute(...)
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
ansiblesemaphore   | github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:37 +0x64
ansiblesemaphore   | main.main()
ansiblesemaphore   | 	/go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x1c
ansiblesemaphore exited with code 0
```

This I just can’t get past. I tried playing with `mysql_native_password` on MySQL but no luck. Everything I’ve tried has failed to get past this. Googling didn’t help.

Any help here will be greatly appreciated!
