### ISSUE TITLE
sudo does not seem to work

### ISSUE THREAD

**Issue by northwestnodes-eric** [ansible-semaphore/semaphore#1671]
It seems sudo authentication does not work.

After creating key stores, repositories, environments, playbooks, etc. we dry run the playbook.

The dry run indicates success: successful SSH authentication, indicating the user and SSH key is correct, etc.

We then execute the task for real, which is where the fun begins: the SSH authentication works, but the moment there is a task with a `become: true` statement, it all falls apart. We tried something simple as an `apt update`.

Now, I know what you're thinking: but then your user doesn't have sudo permissions.

Unfortunately, it does. Logging in with the user works well, the key authenticates, the password authenticates. When logged in, all sudo commands work perfectly.

It is only when executing a playbook through Semaphore that it all falls apart.

Any ideas?

*The playbook*
```
---
- hosts: all
  become: true
  tasks:
    - name: update apt packages # <<< this one doesn't work, adding a become statement to the individual task also does not work.
      environment:
        DEBIAN_FRONTEND: noninteractive
      apt:
        update_cache: yes
    
    - name: upgrade apt packages
      environment:
        DEBIAN_FRONTEND: noninteractive
      apt:
        upgrade: yes
    
    - name: autoremove apt packages
      environment:
        DEBIAN_FRONTEND: noninteractive
      apt:
        autoremove: yes

    - name: check if reboot is required
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: reboot machine
      reboot:
        reboot_timeout: 300
      when: reboot_required.stat.exists
```
