### ISSUE TITLE
[BUG?]  Inventory error after create it using API from admin user.

### ISSUE THREAD

**Issue by esturniolo** [ansible-semaphore/semaphore#1677]
Hi!

I'm using  the latest Semaphore version (docker) and using the admin account I'm able to create users, projects, environments and keys.
The problem is that the project id of inventory API call is not working properly when the project id is higher that 1.

I created an user and a project with that user and admin as owner (besides some other users, keys, environments, blah blah blah).
When I make the call to create a new inventory from the API for the project 2, I get the 201 but visually I can't see/edit the inventory content.

To get this I ran the following using an admin token:

```
curl -vvv -X 'POST' \
  "http://$dnsname:$port/api/project/3/inventory" \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -H "Authorization: Bearer $apitoken" \
  -d "{
  \"name\": \"Default_Empty_Inventory\",
  \"project_id\": 3,
  \"inventory\": \"all:\n  hosts:\n    i-am-an-empty-inventory:\",
  \"ssh_key_id\": 1,
  \"type\": \"static-yaml\"
}"
```
_Note that the project_id is 3 (URL and payload). Any number here will fail, except for **project_id 1** that will be created flawlessly_

The output of the previous API call is the following:
```
* Mark bundle as not supporting multiuse
< HTTP/1.1 201 Created
< Content-Type: application/json
< Date: Tue, 12 Dec 2023 15:51:45 GMT
< Content-Length: 174
< 
{"id":30,"name":"Default_Empty_Inventory","project_id":3,"inventory":"all:\n  hosts:\n    i-am-an-empty-inventory:","ssh_key_id":1,"become_key_id":null,"type":"static-yaml"}
* Connection #0 to host localhost left intact
```
You can see there the 201 telling us that the inventory was successfully created.

But when I go to the UI I see this:

![image](https://github.com/ansible-semaphore/semaphore/assets/5169045/fb107ea5-d979-4714-be1e-044a7a6794a8)

It seems that in this call, the user who call the API can only create inventories for the project with the same id that the user, or something.
I haven't tried yet to create an environment using another user than admin. I mean log as user "joe" and create some inventory for himself.

---

The funny thing here is that another call like **_environment creation_** has the same structure and using the following, works like a charm:
```
        curl -X 'POST' \
          "http://$dnsname:$port/api/project/$api_project_id/environment" \
          -H 'accept: application/json' \
          -H 'Content-Type: application/json' \
          -H "Authorization: Bearer $apitoken" \
          -d "{
          \"name\": \"Default\",
          \"project_id\": $api_project_id,
          \"json\": \"{}\",
          \"env\": \"{}\"
        }"
```
I mean, I can use any number in project_id and works using the admin token.

---

The compose for this is the same as the example in the repo. The only change is the port:
```
services:
  # uncomment this section and comment out the mysql section to use postgres instead of mysql
  #postgres:
    #restart: unless-stopped
    #image: postgres:14
    #hostname: postgres
    #volumes: 
    #  - semaphore-postgres:/var/lib/postgresql/data
    #environment:
    #  POSTGRES_USER: semaphore
    #  POSTGRES_PASSWORD: semaphore
    #  POSTGRES_DB: semaphore
  # if you wish to use postgres, comment the mysql service section below 
  mysql:
    restart: unless-stopped
    image: mysql:8.0
    hostname: mysql
    volumes:
      - ./semaphore-mysql:/var/lib/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: semaphore
  semaphore:
    restart: unless-stopped
    ports:
      - 3043:3000
    image: semaphoreui/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: changeme
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: gs72mPntFATGJs9qK0pQ0rKtfidlexiMjYCH9gWKhTU=
      SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes' 
      SEMAPHORE_LDAP_HOST: dc01.local.example.com
      SEMAPHORE_LDAP_PORT: '636'
      SEMAPHORE_LDAP_NEEDTLS: 'yes'
      SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
      SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
      SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
      SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
    depends_on:
      - mysql # for postgres, change to: postgres
        #volumes:
        #  semaphore-mysql: # to use postgres, switch to: semaphore-postgres
```

Thanks in advance.
