### ISSUE TITLE
documentation: Docker installation mentions SEMAPHORE_PLAYBOOK_PATH - should be  SEMAPHORE_TMP_PATH?

### ISSUE THREAD

**Issue by jhart-uk** [ansible-semaphore/semaphore#1686]
_Running version 2.9.37_

As per:

https://docs.semui.co/administration-guide/installation#docker:

```
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: semaphore
      SEMAPHORE_DB_HOST: mysql # for postgres, change to: postgres
      SEMAPHORE_DB_PORT: 3306 # change to 5432 for postgres
      SEMAPHORE_DB_DIALECT: mysql # for postgres, change to: postgres
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
```

however in `/usr/local/bin/semaphore-wrapper` there's no mention of **SEMAPHORE_PLAYBOOK_PATH** - the closest is:

```
SEMAPHORE_TMP_PATH="${SEMAPHORE_TMP_PATH:-/tmp/semaphore}"
```

Should this environment variable be **SEMAPHORE_TMP_PATH**?
