### ISSUE TITLE
Task doesn't run after fetching repo

### ISSUE THREAD

**Issue by chientrm** [ansible-semaphore/semaphore#1708]
I have `ansible/update.yml` with this content

```yaml
---
- hosts: all
  become: true
  tasks:
    - ansible.builtin.import_role:
        name: update_system
```

However, it stucks after fetching the repo:

<img width="995" alt="Screen Shot 2024-01-19 at 5 36 17 PM" src="https://github.com/ansible-semaphore/semaphore/assets/70304839/4646c729-8e22-40e5-9291-15c9769e8aba">
