### ISSUE TITLE
Unstructured output

### ISSUE THREAD

**Issue by Noswell** [ansible-semaphore/semaphore#1709]
Hello everyone. I've been testing some new playbooks via semaphore and noticed a very strange thing with how semaphore output information, which was get from cisco device (i think it does not depend from which device the information was received, but still).
Using the playbook below:
```YAML
---
- name: Cisco command playbook
  hosts: all
  gather_facts: no
  vars:
    ansible_connection: network_cli
    ansible_network_os: ios

  tasks:
    - name: Run user command on Cisco device
      ios_command:
        commands: show vlan
      register: result

    - name: Show command output
      ansible.builtin.debug:
        var: result.stdout_lines
...
```
i'm getting different types of output, one from native ansible on my ubuntu and one from semaphore. So the output i get from native ansible is pretty good, very similar to what i have on my cisco, in context of structure (comfortable to read and analize):
![image](https://github.com/ansible-semaphore/semaphore/assets/77017369/01d9ea1d-cdec-4c16-8106-f1a0b6a26248)

But when i play my playbook using semaphore, i get this:
![image](https://github.com/ansible-semaphore/semaphore/assets/77017369/1a135ae5-1bb9-460c-8050-a5d7379f2abb)

As you can see (i hope, as i'm using github issues for the first time and may not know some of it's rules and mechanics, btw sorry for that), the semaphore's output is not so structured and uncomfortable to read.
The interesting thing for me is when i go to ansible.cfg file and write ```stdout_callbacks = yaml/debug``` in the [default] section, the output is changed in both semaphore and native ansible, however in semaphore the structure of an output is keeping "bad". I'd be very grateful to any suggestings of how can i fix this problem!
Sorry for my bad english
