### ISSUE TITLE
OIDC configuration username_claim don't work

### ISSUE THREAD

**Issue by EHEX-schildt** [ansible-semaphore/semaphore#1731]
Hi,

i configured OIDC with this guide: https://docs.semui.co/administration-guide/openid

```yaml
"oidc_providers": {
  "my-idp": {
    "display_name": "Sign in with my-idp",
    "provider_url": "https://my.idp/oauth2/openid/semaphore",
    "client_id": "semaphore",
    "client_secret": "$secret"
  }
}
```

According to the guide:

- `"username_claim": "preferred_username",`  # default value, id_token claim to use as the username
- `"name_claim": "preferred_username",`  # default value, id_token claim to use as the display name

I would expet username and display name are both the same and provided by my IDP via the preferred_username claim.

If i login with a IDP Account the display name (name_claim) works as expected.
But for the username (username_claim) i get family_name? extend with some random String.

Setting `"name_claim": "name",` via oidc_providers config works as expected.
explicit Setting the default `"username_claim": "preferred_username",` via oidc_providers config don't work.
Setting `"username_claim": "name",` via oidc_providers config don't work.

Semaphore Version: v2.9.45
