### ISSUE TITLE
Roles are captured before pre_tasks have been processed

### ISSUE THREAD

**Issue by peedy2495** [ansible-semaphore/semaphore#1732]
I'm not able to run playbook content like this:

```
pre_tasks:

    - name: preparing - get current role name
      shell: 'cat /tmp/semaphore/repository_2_2/.git/config|grep url|rev|cut -d "/" -f1|rev|cut -d "." -f1'
      register: curr_role_name

    - name: preparing - propagate role_name
      set_fact:
        role_name: "{{ curr_role_name.stdout }}"

    - name: preparing - create playbook role dir
      file:
        path: "{{ playbook_dir }}/roles/{{ curr_role_name.stdout }}"
        state: directory

    - name: preparing - collect role items
      find: 
        paths: "{{ playbook_dir }}"
        excludes: "roles"
        file_type: "directory"
      register: role_items 

    - name: preparing - symlink project items as role
      file:
        src: "{{ item }}"
        dest: "{{ playbook_dir }}/roles/{{ role_name }}/{{ item | basename}}"
        state: link
      with_items: "{{ role_items.files | map(attribute='path') | list }}"
    
  roles:
    - "{{ role_name }}"
```

This behavior does not correspond to the Ansible documentation. [Using roles at the play level](https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#id5)
I'm not using the role import via requirements.yml, because of lack of secrets in the download url using private github repositories.
