### ISSUE TITLE
Git repositories from requirements.yml are not being updated

### ISSUE THREAD

**Issue by peedy2495** [ansible-semaphore/semaphore#1753]
I'm concatenating repositories with different themes into a job template.

But running a task  template doesn't update the requirements.
Deleting a requirement/repo in  /tmp/semaphore/.ansibe/roles/ causes an error instead of repulling this requirement.

Actual workaround:
git pull for updating within the repo dir, when changes has been commited to the source of truth.

**Comment by andreas-marschke** [comment]
Could you share:
 - The playbook for the concatenation
 - The Playbook referencing the repositories
 
Can you elaborate what Deleting Requirement entails?

**Comment by peedy2495** [comment]
I meant deleting the repository directory that was not updated after a change to this repository.

Take a look @ [peedy2495/sem_desktops_ubuntu2204](https://github.com/peedy2495/sem_desktops_ubuntu2204)

**Comment by andreas-marschke** [comment]
Ok. So this appears to only be a subset of the playbooks you are using and doesn't seem to be a full ansible project?

If you initially cloned this repository manually into your ansible repo that was cloned by semaphore,  any changes to your sub repo will never have been communicated to semaphore in the first place.

If I'm wholly misunderstanding your setup, please enlighten me.

**Comment by peedy2495** [comment]
The repo [peedy2495/sem_desktops_ubuntu2204](https://github.com/peedy2495/sem_desktops_ubuntu2204) was defined in semaphore as repo source and has been used in a task template.
The other elements for the play has been defined in the repo via requirements.yml (refer repo source)

After running the task template first time, every dependency/role  has been pulled and executed.
But, after a commit in a dependency repo, defined via requirements.yml, changes won't be pulled/updated in future runs.

**Comment by andreas-marschke** [comment]
After some digging this is apparently a limitation in ansible-galaxy https://github.com/ansible/ansible/issues/6466. 
Semaphore is only trying to "do the right thing" and runs `ansible-galaxy roles install -r {requirements.yml} --force` as it "should", but the real limitation is not on Semaphore's side.

I'm sorry, we can't help here.

**Comment by peedy2495** [comment]
I found the prob for this bug:

If any requirements.yml, neither in collections, nor in roles hasn't been changed, the update will be skipped.
Therefore no changes within the external roles will be updated.

Please reopen this bug.

Workaround for now:
```
- hosts: all
  gather_facts: true
  vars:
    ansible_become: no

  pre_tasks:
    - name: reload external roles
      shell: 'export HOME=/tmp/semaphore; ansible-galaxy install -r roles/requirements.yml --force'
      delegate_to: localhost
```
running this one for keeping external roles current ...

**Comment by peedy2495** [comment]
Please read my last comment/explanation in this issue and reopen it.

Cheers ... Peedy

**Comment by peedy2495** [comment]
If anyone is struggling with updating external dependencies, I have a simple new workaround:

```yaml
pre_tasks:
  - name: Semaphore - remove requirements hash file to force a new requirements download
    ansible.builtin.command:
      cmd: "rm roles/requirements.yml.md5"
    delegate_to: localhost
    become: false
```
Explanation:  
Semaphore updates external dependencies only if the `requirements.yml` file has changed. The hash file `requirements.yml.md5` stores the hash of the current requirements file.  
If the file `reqirements.yml.md5` has been removed or `requirements.yml` has been modified on source, Semaphore will detect the change and trigger a fresh download of all dependencies.

This method could be an option in the UI - Refresh requirements: Never/OnChgange/Always

**Comment by peedy2495** [comment]
Update: The structure for managing those MD5 files has changed. This method is now required to force external roles to reload:
```yaml
pre_tasks:
  - name: Semaphore - remove requirements hash file to force a new requirements download
    ansible.builtin.shell: rm ../../repository_*_internal/*.md5
    args:
      executable: bash
    delegate_to: localhost
```

Maybe this should be an option (a checkbox) in the task template configuration to remove those files internally before calling Ansible.
