### ISSUE TITLE
Getting 401 error code from Runner

### ISSUE THREAD

**Issue by jlopez994** [ansible-semaphore/semaphore#1766]
Hi,

I'm trying to setup a runner with docker compose but after it manages to connect to my semaphore instance it keeps logging this message: `Checking new jobs error, server returns code 401`

This is the full log in case you need it:
```
ansible-semaphore-runner  | Loading environment...
ansible-semaphore-runner  | Staring runner...
ansible-semaphore-runner  | [defaults]
ansible-semaphore-runner  | host_key_checking = False
ansible-semaphore-runner  | stdout_callback = yaml
ansible-semaphore-runner  | bin_ansible_callbacks = yes
ansible-semaphore-runner  | Loading config
ansible-semaphore-runner  | Validating config
ansible-semaphore-runner  | time="2024-02-18T12:01:06Z" level=info msg="Trying to register on server"
ansible-semaphore-runner  | time="2024-02-18T12:01:06Z" level=info msg="Runner registered on server"
ansible-semaphore-runner  | time="2024-02-18T12:01:07Z" level=error msg="Checking new jobs error, server returns code 401"
ansible-semaphore-runner  | time="2024-02-18T12:01:08Z" level=error msg="Checking new jobs error, server returns code 401"
(...)
```

Also, this is my compose config for the runner:
```
--
services:
  semaphore-runner:
    container_name: ansible-semaphore-runner
    image: semaphoreui/runner
    volumes:
      - ./config/config.json:/etc/semaphore/config.json
      - ./service.json:/tmp/service
    restart: unless-stopped
    networks:
      - test

networks:
  test:
    external: true
```

And this is the configuration file content:
```
{
  "runner": {
    "registration_token": "test",
    "config_file": "/tmp/semaphore-runner.json",
    "api_url": "http://ansible-semaphore:3000/api",
    "max_parallel_tasks": 3
  }
}
```

Bot instances are running on the same machine. I also added these two lines to the main configuration:
```
"use_remote_runner": true,
"runner_registration_token": "test"
```

Thanks in advance!
