### ISSUE TITLE
Unable to edit Inventory - failed with: Request failed with status code 400

### ISSUE THREAD

**Issue by mgertz** [ansible-semaphore/semaphore#1785]
Hi.

When I try to edit an inventory, I get the error message `Request failed with status code 400`

![image](https://github.com/ansible-semaphore/semaphore/assets/5869633/e30cd2cb-d760-4283-a7fe-a0b9823517b2)

I'm running Semaphore in a docker stack. When I look in the log for the stack, there isn't any warnings about the 400 error.

My docker-compose.yml file looks like this.
```yaml
services:

  postgres:
    restart: unless-stopped
    image: postgres:14
    hostname: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: semaphore
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: semaphore
    networks:
      - internal

  semaphore:
    image: semaphoreui/semaphore:latest
    container_name: semaphore_gui
    restart: no
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: ${DB_PASSWORD}
      SEMAPHORE_DB_HOST: postgres # for postgres, change to: postgres | for mysql, change to: mysql
      SEMAPHORE_DB_PORT: 5432 # change to 5432 for postgres | change to 3306 for mysql
      SEMAPHORE_DB_DIALECT: postgres # for postgres, change to: postgres | for mysql, change to: mysql
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /playbooks #/tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: email@examp.com (No! that has been change ;) )
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ENCRYPTION_KEY}
      ANSIBLE_HOST_KEY_CHECKING: false
      TZ: Europe/Copenhagen
    volumes:
      - ./playbooks:/playbooks
      - ./inventory:/inventory
    labels:
      - traefik.enable=true
      - traefik.docker.network=traefik
      - traefik.http.routers.semaphore.entrypoints=web
      - traefik.http.routers.semaphore.rule=Host(`semaphore.localhost`)
      - traefik.http.services.semaphore.loadbalancer.server.port=3000
    networks:
      - traefik
      - internal
    depends_on:
      - postgres # for postgres, change to: postgres | for mysql, change to: mysql


volumes:
  mysql: # to use postgres, switch to: semaphore-postgres
  postgres:

networks:
  traefik:
    external: true
  internal:
    external: false
```

Does anyone know how to fix this issue?
