### ISSUE TITLE
Postgres connection bug - when using docker image semaphoreui/semaphore:2.9.37

### ISSUE THREAD

**Issue by skensell201** [ansible-semaphore/semaphore#1797]
Use ansible-semaphore version 2.9.37 in docker

Perhaps a bug has been discovered. When ansible-semaphore is connected to Postgres with an additional port of 5432, the semaphore command is not executed inside the container.

### docker-compose
```
services:
  semaphore:
    restart: unless-stopped
    ports:
      - 3000:3000
    image: semaphoreui/semaphore:2.9.37
    extra_hosts:
      postgres.lan: 10.115.19.19
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_HOST: postgres.lan
      SEMAPHORE_DB_PORT: 5000
      SEMAPHORE_DB_DIALECT: postgres
      SEMAPHORE_DB: semaphore
```

### config.json
```
/etc/semaphore $ cat config.json
...
{
        "postgres": {
                "host": "postgres.lan:5000",
                "user": "semaphore",
                "pass": "*********",
                "name": "semaphore",
                "options": {
                        "sslmode": "disable"
                }
        },
        "dialect": "postgres",
```

### Error
```
$ semaphore --config config.json user list
Loading config
Validating config
WARN[0000] dial tcp 10.115.19.19:5432: connect: connection refused
panic: dial tcp 10.115.19.19: connect: connection refused

goroutine 1 [running]:
github.com/ansible-semaphore/semaphore/db/sql.(*SqlDb).Connect(0xc0000ba710, {0xb?, 0xc000095cc8?})
        /go/src/github.com/ansible-semaphore/semaphore/db/sql/SqlDb.go:290 +0xb05
github.com/ansible-semaphore/semaphore/cli/cmd.createStore({0x0, 0x0})
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:103 +0x65
github.com/ansible-semaphore/semaphore/cli/cmd.glob..func13(0x274e500?, {0xbf6e8e?, 0x2?, 0x2?})
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/user_list.go:17 +0x45
github.com/spf13/cobra.(*Command).execute(0x274e500, {0xc0000444e0, 0x2, 0x2})
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x274db00)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:974 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/github.com/ansible-semaphore/semaphore/vendor/github.com/spf13/cobra/command.go:902
github.com/ansible-semaphore/semaphore/cli/cmd.Execute()
        /go/src/github.com/ansible-semaphore/semaphore/cli/cmd/root.go:37 +0x5b
main.main()
        /go/src/github.com/ansible-semaphore/semaphore/cli/main.go:8 +0x17
```

After I created a new rule on haproxy, completely duplicating the rule for port 5000, the only difference is bind *:5000 -> bind *:5432 After that, semaphore started working

### After change haproxy
```
$ cat config.json | grep postgres
"postgres": {
    "host": "postgres.lan:5000",
"dialect": "postgres",

$ semaphore --config config.json user list
Loading config
Validating config
admin
developer
qa
```
