### ISSUE TITLE
Any playbook that will install and setup this app?

### ISSUE THREAD

**Issue by rjrobinson** [ansible-semaphore/semaphore#194]
Was wondering if there is a playbook that will set up all dependencies from scratch, where the user only has to specify the install type?

**Comment by gcavalcante8808** [comment]
@rjrobinson  What do you mean with 'install type'?

**Comment by rjrobinson** [comment]
I guess im looking for a role, that will init the semaphore set up. 

like

```yaml
---
- hosts: semaphore
  role: 
    - semaphore
```

all we have to do is spin up the VM. Thoughts?
