### ISSUE TITLE
Unable to run tasks with become=true  [ Privilege output closed while waiting for password prompt ]

### ISSUE THREAD

**Issue by ipa-rar** [ansible-semaphore/semaphore#1971]
I tried v2.9.69-beta and tried to Update and upgrade apt packages with this script

```
---
- hosts: all
  become: true
  connection: local
  tasks:
    - name: Update and upgrade apt packages
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
```

`fatal: [192.168.50.156]: FAILED! => {"msg": "privilege output closed while waiting for password prompt:\n/bin/sh: sudo: not found\n"}`

This happens to all the playbooks that I have with `become=true`
