### ISSUE TITLE
Feature: Playbook to update requirements.yml

### ISSUE THREAD

**Issue by zzecool** [ansible-semaphore/semaphore#2025]
### Related to

Service (scheduled tasks, alerts), Ansible (task execution), Docker

### Impact

better user experience

### Missing Feature

I was reading the documention about the /home/semaphore/requirements.yml at :  https://docs.semui.co/administration-guide/installation_manually#ansible-collections-and-roles-1

I believe the most refined way to perform the actual installation or update is by using a Task in Semaphore for localhost.

1: Create and populate the requirements.yml.
2: Make a task with the following playbook.

```
---
- name: Install or upgrade Ansible collections and roles
  hosts: localhost
  tasks:
    - name: Install or upgrade collections
      command: ansible-galaxy collection install --upgrade -r /home/semaphore/requirements.yml
      ignore_errors: yes

    - name: Install roles
      command: ansible-galaxy role install --force -r /home/semaphore/requirements.yml
      ignore_errors: yes

```

3: Schedule it to run with cron. 
4: You are always up to date.

### Implementation

As a build in playbook untill you will add in the web interface a way to add collections and roles.
