### ISSUE TITLE
Problem: incorrect task link in email alerts

### ISSUE THREAD

**Issue by vicat28** [ansible-semaphore/semaphore#2097]
### Issue

After updating to v2.9.112-4f95ac8-1717, the Task Log link in email alerts is incorrect - it does not contain `web_host`, even though it is set correctly in config:
![obraz](https://github.com/semaphoreui/semaphore/assets/30496057/84f41015-947e-42ec-b8d9-e3519675ddc7)

Before the update, the link was set correctly and was clickable.

### Impact

Service (scheduled tasks, alerts)

### Installation method

Docker

### Database

Postgres

### Semaphore Version

v2.9.112-4f95ac8-1717

### Configuration

`config.json`
```
{
    [...]
    "web_host": "http://example.com:3000",
    [...]
    "email_alert": true,
    [...]
}
```

### Additional information

Possibly related to [#2084](https://github.com/semaphoreui/semaphore/issues/2084#issue-2336044746)

**Comment by sherlock7402** [comment]
Same Problem here. Using docker-compose with:
```yaml
  semaphore:
    image: semaphoreui/semaphore:v2.10.43
    ports:
      - "3000:3000"
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_EMAIL_ALERT: False
      SEMAPHORE_TELEGRAM_ALERT: True
      SEMAPHORE_TELEGRAM_CHAT: "-xxxx"
      SEMAPHORE_TELEGRAM_TOKEN: "***"
      SEMAPHORE_WEB_HOST: "https://sema.example.com"
```

Getting messages like:
```
1-do-ping
#2147483617 ❌ERROR  - 
by Me
/project/1/templates/2?t=2147483617
```
