### ISSUE TITLE
Answer file for semaphore -setup?

### ISSUE THREAD

**Issue by KarenTovmasian** [ansible-semaphore/semaphore#218]
Hi guys!

First of all, thanks you for a great solution for ansible fans.
We want to automate semaphore setup so it meets or Infrastructure-As-Code requirements, would be nice if there will be a way to install and start semaphore with answer file.

**Comment by gcavalcante8808** [comment]
@KarenTovmasian 
Do you have some 'sample' about the file? 

Actually I'm use the ansible to setUP the semaphore container... And then ... use the container.

**Comment by KarenTovmasian** [comment]
@gcavalcante8808 
something like a YAML file
```yaml
---
db_host: 192.168.1.1
db_port: 3306 # 3306 by default if not provided
db_user: someuser # semaphore by default if not provided
db_password: supersecurepassword
```
etc.

Docker is nice, but we don't plan to use it yet.
