### ISSUE TITLE
Problem: Task stuck in running status - Failed to lock apt for exclusive operation

### ISSUE THREAD

**Issue by masterwishx** [ansible-semaphore/semaphore#2280]
### Issue

![image](https://github.com/user-attachments/assets/b9dcd928-0fc8-4968-acd7-0ec58e61af8b)

Error: 

`TASK [Update all installed packages to their latest version] *******************`

`fatal: [instance-mysite]: FAILED! => {"changed": false, "msg": "Failed to lock apt for exclusive operation: Failed to lock directory /var/lib/apt/lists/: E:Could not get lock /var/lib/apt/lists/lock. It is held by process 50083 (python3)"}`

```
---
- name: Update Ubuntu packages and check reboot
  hosts: all
  become: yes  

  tasks:
    - name: Update all installed packages to their latest version
      apt:
        name: "*"
        state: latest
        only_upgrade: yes
        update_cache: yes        
      register: updated_packages
        
   ...
   ...
```

### Impact

Service (scheduled tasks, alerts)

### Installation method

Docker

### Semaphore Version

using in docker Unraid x64 latest version [ghcr.io/imagegenius/semaphore](https://github.com/orgs/imagegenius/packages/container/package/semaphore) v2.10.23-beta-e44910d4-1723230462
