### ISSUE TITLE
Problem: Dynamic Inventory File - permission denied

### ISSUE THREAD

**Issue by dag-gremache** [ansible-semaphore/semaphore#2290]
### Issue

I created a python script that generates an inventory list, this works perfectly on my local machine. This file is then pushed to the git repo. 

I setup the inventory file within semaphore just as any other file based inventory. (no user or root creds). 

When i run the template, i get the following error:

```
10:27:28 AM
Loading collection ansible.builtin from 
10:27:28 AM
host_list declined parsing /tmp/semaphore/inventory_389/inventory/inventory.py as it did not pass its verify_file() method
10:27:28 AM
auto declined parsing /tmp/semaphore/inventory_389/inventory/inventory.py as it did not pass its verify_file() method
10:27:28 AM
yaml declined parsing /tmp/semaphore/inventory_389/inventory/inventory.py as it did not pass its verify_file() method
10:27:28 AM
toml declined parsing /tmp/semaphore/inventory_389/inventory/inventory.py as it did not pass its verify_file() method
10:27:28 AM
[WARNING]:  * Failed to parse
10:27:28 AM
/tmp/semaphore/inventory_389/inventory/inventory.py with script plugin:
10:27:28 AM
problem running /tmp/semaphore/inventory_389/inventory/inventory.py --list
10:27:28 AM
([Errno 13] Permission denied:
10:27:28 AM
'/tmp/semaphore/inventory_389/inventory/inventory.py')
10:27:28 AM
[WARNING]:  * Failed to parse

```
Semaphore is setup using docker, and i am lost here. 

1. I do not know what the root password is, since whenever I connect to the docker instance I just use `sudo docker run -it semaphoreui/semaphore bash`
2. I've done lots of research and i can't figure out how to make this work, or how to generate a root password within the docker instance. 

Based on the `([Errno 13] Permission denied:` error, i am assuming the .py script fails to run because semaphore does not have permission to run the script. How can i fix this within the docker instance, or is there anything i can modify on the docker file?

**Docker file**

```
---
volumes:
  semaphore-mysql:
    driver: local
services:
  mysql:
    image: docker.io/library/mysql:8.3
    hostname: mysql
    volumes:
      - semaphore-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=semaphore
      - MYSQL_USER=semaphore
      - MYSQL_PASSWORD=pass goes here!  # change!
    restart: unless-stopped
  semaphore:
    container_name: ansiblesemaphore
    image: semaphoreui/semaphore:latest
    user: "${UID}:${GID}"
    ports:
      - 3000:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=pass goes here!  # change!
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT=3306
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=pass goes here!  # change!
      - SEMAPHORE_ADMIN_NAME="NoC"
      - SEMAPHORE_ADMIN_EMAIL=noc@domain.com
      - SEMAPHORE_ADMIN=noc@domain.com
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=key goes here  # add to your access key encryption !
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
    volumes:
      - ./inventory/:/inventory:ro
      - ./authorized-keys/:/authorized-keys:ro
      - ./config/:/etc/semaphore:rw
      - ./requirements.txt:/etc/semaphore/requirements.txt
    restart: unless-stopped
    depends_on:
      - mysql
```

### Impact

Docker, Semaphore Project

### Installation method

Docker

### Database

MySQL

### Browser

Microsoft Edge

### Semaphore Version

v2.10.22-e44910d-1721658561

### Ansible Version

```bash
ansible [core 2.16.9]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/semaphore/apps/ansible/9.4.0/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/semaphore/apps/ansible/9.4.0/venv/bin/ansible
  python version = 3.11.9 (main, Apr 14 2024, 13:40:00) [GCC 13.2.1 20231014] (/opt/semaphore/apps/ansible/9.4.0/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```
