### ISSUE TITLE
Problem: "request failed with status code 400" with creating key or inventory.

### ISSUE THREAD

**Issue by tomshomelab** [ansible-semaphore/semaphore#2509]
### Issue

making any changes to keystore, inventory gives me the following error: "request failed with status code 400" 

![image](https://github.com/user-attachments/assets/6bb38fda-f8cb-49fa-8517-f6925c31adff)

and the below error appears in the logs for docker. 

```
time="2024-10-29T14:38:29Z" level=error msg="illegal base64 data at input byte 28"
goroutine 59 [running]:
runtime/debug.Stack()
	/usr/local/go/src/runtime/debug/stack.go:24 +0x5e
runtime/debug.PrintStack()
	/usr/local/go/src/runtime/debug/stack.go:16 +0x13
github.com/semaphoreui/semaphore/api/helpers.WriteError({0x1957fc0, 0xc0000c6ee0}, {0x1953460, 0x1dec160})
	/go/src/semaphore/api/helpers/helpers.go:122 +0x21b
github.com/semaphoreui/semaphore/api/projects.AddKey({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/api/projects/keys.go:92 +0x5d4
net/http.HandlerFunc.ServeHTTP(0x7f35679065b8?, {0x1957fc0?, 0xc0000c6ee0?}, 0xc00020e900?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/api.Route.GetMustCanMiddleware.func4.1({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/api/projects/project.go:59 +0x127
net/http.HandlerFunc.ServeHTTP(0xc00020e6c0?, {0x1957fc0?, 0xc0000c6ee0?}, 0xc48400?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/api/projects.ProjectMiddleware.func1({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/api/projects/project.go:43 +0x43d
net/http.HandlerFunc.ServeHTTP(0x1957fc0?, {0x1957fc0?, 0xc0000c6ee0?}, 0x0?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/api.authentication.func1({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/api/auth.go:102 +0x57
net/http.HandlerFunc.ServeHTTP(0xc23960?, {0x1957fc0?, 0xc0000c6ee0?}, 0xc?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/api.JSONMiddleware.func1({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/api/router.go:45 +0xf6
net/http.HandlerFunc.ServeHTTP(0xb73300?, {0x1957fc0?, 0xc0000c6ee0?}, 0x78c4ec?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/api.StoreMiddleware.func1.1()
	/go/src/semaphore/api/router.go:36 +0x28
github.com/semaphoreui/semaphore/db.StoreSession({0x19677c0, 0xc000062730}, {0xc00042f2f0, 0xc}, 0xc00049f7d8)
	/go/src/semaphore/db/Store.go:463 +0x5f
github.com/semaphoreui/semaphore/api.StoreMiddleware.func1({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/api/router.go:35 +0x126
net/http.HandlerFunc.ServeHTTP(0xc00020e6c0?, {0x1957fc0?, 0xc0000c6ee0?}, 0xc2ee20?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/cli/cmd.runService.func1.1({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/cli/cmd/root.go:93 +0xea
net/http.HandlerFunc.ServeHTTP(0x0?, {0x1957fc0?, 0xc0000c6ee0?}, 0x411d65?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/api.Route.CORSMethodMiddleware.func1.1({0x1957fc0, 0xc0000c6ee0}, 0xc00020e6c0)
	/go/src/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x89
net/http.HandlerFunc.ServeHTTP(0xc00020e5a0?, {0x1957fc0?, 0xc0000c6ee0?}, 0xc0000959b8?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/gorilla/mux.(*Router).ServeHTTP(0xc000000480, {0x1957fc0, 0xc0000c6ee0}, 0xc00020e360)
	/go/src/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x1e2
github.com/semaphoreui/semaphore/cli/cmd.runService.ProxyHeaders.func2({0x1957fc0, 0xc0000c6ee0}, 0xc00020e360)
	/go/src/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x143
net/http.HandlerFunc.ServeHTTP(0xc00003cc65?, {0x1957fc0?, 0xc0000c6ee0?}, 0x7f35679123a8?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
github.com/semaphoreui/semaphore/cli/cmd.runService.cropTrailingSlashMiddleware.func3({0x1957fc0, 0xc0000c6ee0}, 0xc00020e360)
	/go/src/semaphore/cli/cmd/server.go:27 +0xbd
net/http.HandlerFunc.ServeHTTP(0x411d65?, {0x1957fc0?, 0xc0000c6ee0?}, 0xc0000c6e01?)
	/usr/local/go/src/net/http/server.go:2166 +0x29
net/http.serverHandler.ServeHTTP({0x1955a48?}, {0x1957fc0?, 0xc0000c6ee0?}, 0x6?)
	/usr/local/go/src/net/http/server.go:3137 +0x8e
net/http.(*conn).serve(0xc000210120, {0x1959e68, 0xc000124090})
	/usr/local/go/src/net/http/server.go:2039 +0x5e8
```

### Impact

Web-Frontend (what users interact with)

### Installation method

Docker

### Database

MySQL

### Browser

Firefox, Microsoft Edge, Opera

### Semaphore Version

latest

### Manual installation - system information

Linux docker-v3-management 5.4.0-196-generic #216-Ubuntu SMP Thu Aug 29 13:26:53 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

im using nginx reverse proxy behind cloudflare. accessing the ansbile ui through https

### Configuration

```
---
volumes:
  semaphore-mysql:
    driver: local
services:
  mysql:
    image: docker.io/library/mysql:8.3
    hostname: mysql
    volumes:
      - /docker/ansible/semaphore-mysql:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=semaphore
      - MYSQL_USER=semaphore
      - MYSQL_PASSWORD=password  # change!
    restart: unless-stopped
  semaphore:
    container_name: ansiblesemaphore
    image: docker.io/semaphoreui/semaphore:latest
    user: "${UID}:${GID}"
    ports:
      - 3162:3000
    environment:
      - SEMAPHORE_DB_USER=semaphore
      - SEMAPHORE_DB_PASS=password  # change!
      - SEMAPHORE_DB_HOST=mysql
      - SEMAPHORE_DB_PORT=3000
      - SEMAPHORE_DB_DIALECT=mysql
      - SEMAPHORE_DB=semaphore
      - SEMAPHORE_PLAYBOOK_PATH=/tmp/semaphore/
      - SEMAPHORE_ADMIN_PASSWORD=password  # change!
      - SEMAPHORE_ADMIN_NAME=admin
      - SEMAPHORE_ADMIN_EMAIL=EMAIL
      - SEMAPHORE_ADMIN=admin
      - SEMAPHORE_ACCESS_KEY_ENCRYPTION=KEY  # add to your access key encryption !
# generate a new key within any terminal, dont need ansible installed
# `head -c23 /dev/urandom | base64`
      - ANSIBLE_HOST_KEY_CHECKING=false  # (optional) change to true if you want to enable host key checking
    volumes:
      - /docker/ansible/inventory/:/inventory:ro
      - /docker/ansible/authorized-keys/:/authorized-keys:ro
      - /docker/ansible/config/:/etc/semaphore:rw
    restart: unless-stopped
    depends_on:
      - mysql
    labels:
      - homepage.group=Management
      - homepage.name=Ansible-Semaphore
      - homepage.icon=ansible.png
      - homepage.href=http://192.168.0.112:3000
      - homepage.description=Automation
      - homepage.showStats=false
```
