### ISSUE TITLE
Problem: Injecting weird port value despite setting in configuration.json file (docker)

### ISSUE THREAD

**Issue by toaspzoo** [ansible-semaphore/semaphore#2530]
### Issue

I am trying to setup semaphore ui, running as container in kubernetes and seeing error described in the form. Somehow, "tcp://xxx.xxx.xxx.xxx:3000" is assigned as a port config key.

### Impact

Docker

### Installation method

Docker

### Database

MySQL

### Browser

Chrome

### Semaphore Version

semaphoreui/semaphore:2.10.35

### Logs & errors

```
Pinging database on mariadb port 3306...
No additional python dependencies to install
Starting semaphore server
Loading config
Validating config
panic: value of field 'Port' is not valid: tcp://10.111.77.182:3000 (Must match regex: '^:?([0-9]{1,5})$')
goroutine 1 [running]:
github.com/semaphoreui/semaphore/util.validateConfig(...)
 /go/src/semaphore/util/config.go:512
github.com/semaphoreui/semaphore/util.ConfigInit({0x7ffca3d8f9d4, 0x1a}, 0x0)
 /go/src/semaphore/util/config.go:241 +0x351
github.com/semaphoreui/semaphore/cli/cmd.createStore({0xc88198, 0x4})
 /go/src/semaphore/cli/cmd/root.go:118 +0x3c
github.com/semaphoreui/semaphore/cli/cmd.runService()
 /go/src/semaphore/cli/cmd/root.go:63 +0x3c
github.com/semaphoreui/semaphore/cli/cmd.init.func9(0xc0001a7000?, {0xc881cc?, 0x4?, 0xc881d0?})
 /go/src/semaphore/cli/cmd/server.go:18 +0xf
github.com/spf13/cobra.(*Command).execute(0x1e345a0, {0xc00016bd20, 0x2, 0x2})
 /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x1e33460)
 /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
 /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1041
github.com/semaphoreui/semaphore/cli/cmd.Execute()
 /go/src/semaphore/cli/cmd/root.go:56 +0xc5
main.main()
 /go/src/semaphore/cli/main.go:8 +0xf`
```

### Configuration

/etc/semaphore/config.json
```
{
      "bolt": {
        "host": "/home/ubuntu/semaphore.bolt"
      },
      "mysql": {
        "host": "mariadb",
        "user": "root",
        "pass": "root",
        "name": "semaphore",
        "options": {}
      },
      "dialect": "mysql",
      "port": "3000",
      "interface": "",
      "tmp_path": "/tmp/semaphore",
      "cookie_hash": "*****",
      "cookie_encryption": "*****",
      "access_key_encryption": "*****",
      "email_sender": "",
      "email_host": "",
      "email_port": "",
      "web_host": "https://sem.3ez.pl",
      "ldap_binddn": "",
      "ldap_bindpassword": "",
      "ldap_server": "",
      "ldap_searchdn": "",
      "ldap_searchfilter": "",
      "ldap_mappings": {
        "dn": "",
        "mail": "",
        "uid": "",
        "cn": ""
      },
      "telegram_chat": "",
      "telegram_token": "",
      "concurrency_mode": "",
      "max_parallel_tasks": 0,
      "email_alert": false,
      "telegram_alert": false,
      "slack_alert": false,
      "slack_url": "",
      "rocketchat_alert": false,
      "rocketchat_url": "",
      "ldap_enable": false,
      "ldap_needtls": false
    }
```

### Additional information

Running in kubernetes cluster

```
apiVersion: apps/v1
kind: Deployment
metadata:
  name: semaphore
  namespace: semaphore
  labels:
    app: semaphore
spec:
  replicas: 1
  selector:
    matchLabels:
      app: semaphore
  template:
    metadata:
      labels:
        app: semaphore
    spec:
      containers:
        - name: semaphore
          image: semaphoreui/semaphore:v2.10.35
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: semaphore-config
              mountPath: /etc/semaphore/config.json
              subPath: config.json
      volumes:
        - name: semaphore-config
          configMap:
            name: semaphore
      initContainers:
        - name: wait-for-mysql
          image: busybox:latest
          command: [ 'sh', '-c', 'until nc -z -v -w30 mariadb 3306; do echo "Waiting for MySQL..."; sleep 5; done;' ]
```

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: semaphore
  namespace: semaphore
data:
  config.json: |
    {
      "bolt": {
        "host": "/home/ubuntu/semaphore.bolt"
      },
      "mysql": {
        "host": "mariadb",
        "user": "root",
        "pass": "root",
        "name": "semaphore",
        "options": {}
      },
      "dialect": "mysql",
      "port": "3000",
      "interface": "",
      "tmp_path": "/tmp/semaphore",
      "cookie_hash": "*****",
      "cookie_encryption": "*****",
      "access_key_encryption": "*****",
      "email_sender": "",
      "email_host": "",
      "email_port": "",
      "web_host": "",
      "ldap_binddn": "",
      "ldap_bindpassword": "",
      "ldap_server": "",
      "ldap_searchdn": "",
      "ldap_searchfilter": "",
      "ldap_mappings": {
        "dn": "",
        "mail": "",
        "uid": "",
        "cn": ""
      },
      "telegram_chat": "",
      "telegram_token": "",
      "concurrency_mode": "",
      "max_parallel_tasks": 0,
      "email_alert": false,
      "telegram_alert": false,
      "slack_alert": false,
      "slack_url": "",
      "rocketchat_alert": false,
      "rocketchat_url": "",
      "ldap_enable": false,
      "ldap_needtls": false
    }
```
