### ISSUE TITLE
Question: What do I need to do when a task hangs

### ISSUE THREAD

**Issue by MaKaNu** [ansible-semaphore/semaphore#2534]
### Question

I have installed semaphore manual on a LXC container. My ansible Installation playbook is basically the process described for manual installation via deb file.

After figuring out how to give my semaphore user access to our private role repos, I thought I made it, but every playbook stops directly at the first tasks:

Here with gather_facts:
![image](https://github.com/user-attachments/assets/a680883f-b134-4c6b-9d5b-874521e3aaa1)

And here without:
![image](https://github.com/user-attachments/assets/623ced24-4a8f-420b-8631-54ba78977434)

My Simple test which works perfectly if I run locally:

```yaml
---
- name: Run Base Setup
  hosts: semaphore-test
  become: true
  gather_facts: false
  roles:
    - base
```

### Related to

Web-Frontend (what users interact with)
