### ISSUE TITLE
Problem: debug/dry run/diff checkboxes on integrations are not saved 

### ISSUE THREAD

**Issue by jhuesser** [ansible-semaphore/semaphore#2600]
### Issue

I'm trying to troubleshoot a task template that is triggered by a webhook. For that I wanted to enable the `debug -vvvv` option on the integration. However upon saving and reopening the integration config modal, the console logs the following two entries listed below.

This happens for the other fields (Dry Run --check, and Diff -diff) as well.

### Impact

Web-Frontend (what users interact with)

### Installation method

Docker

### Database

MySQL

### Browser

Chrome, Safari

### Semaphore Version

v2.10.43-e43af6b-1732278120

### Ansible Version

```bash
ansible [core 2.16.13]
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/semaphore/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /opt/semaphore/apps/ansible/9.4.0/venv/lib/python3.11/site-packages/ansible
  ansible collection location = /home/semaphore/.ansible/collections:/usr/share/ansible/collections
  executable location = /opt/semaphore/apps/ansible/9.4.0/venv/bin/ansible
  python version = 3.11.10 (main, Sep 11 2024, 09:58:40) [GCC 13.2.1 20231014] (/opt/semaphore/apps/ansible/9.4.0/venv/bin/python3)
  jinja version = 3.1.4
  libyaml = True
```

### Logs & errors

1st error in browser console:

```js
ItemListPageBase.js:134 TypeError: Cannot read properties of null (reading 'name')
    at a.Do (IntegrationForm.vue:1:551)
    at e._render (vue.runtime.esm.js:3569:22)
    at a.i (vue.runtime.esm.js:4081:21)
    at ri.get (vue.runtime.esm.js:4495:25)
    at ri.run (vue.runtime.esm.js:4570:22)
    at Xn (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at dt (vue.runtime.esm.js:1915:12)
at @ vue.runtime.esm.js:1897
st @ vue.runtime.esm.js:1888
it @ vue.runtime.esm.js:1848
e._render @ vue.runtime.esm.js:3571
i @ vue.runtime.esm.js:4081
ri.get @ vue.runtime.esm.js:4495
ri.run @ vue.runtime.esm.js:4570
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
dt @ vue.runtime.esm.js:1915
Promise.then
ot @ vue.runtime.esm.js:1942
gt @ vue.runtime.esm.js:1999
ni @ vue.runtime.esm.js:4418
ri.update @ vue.runtime.esm.js:4560
ge.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
si.set @ vue.runtime.esm.js:4644
editItem @ ItemListPageBase.js:134
click @ Integrations.vue:12
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
rt @ vue.runtime.esm.js:1863
An.e.$emit @ vue.runtime.esm.js:3903
click @ VBtn.ts:163
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ItemFormBase.js:120 TypeError: Cannot read properties of null (reading 'debug')
    at a.br (TaskParamsForm.vue:1:298)
    at e._render (vue.runtime.esm.js:3569:22)
    at a.i (vue.runtime.esm.js:4081:21)
    at ri.get (vue.runtime.esm.js:4495:25)
    at ri.run (vue.runtime.esm.js:4570:22)
    at Xn (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at dt (vue.runtime.esm.js:1915:12)
at @ vue.runtime.esm.js:1897
st @ vue.runtime.esm.js:1888
it @ vue.runtime.esm.js:1848
e._render @ vue.runtime.esm.js:3571
i @ vue.runtime.esm.js:4081
ri.get @ vue.runtime.esm.js:4495
ri.run @ vue.runtime.esm.js:4570
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
dt @ vue.runtime.esm.js:1915
Promise.then
ot @ vue.runtime.esm.js:1942
gt @ vue.runtime.esm.js:1999
ni @ vue.runtime.esm.js:4418
ri.update @ vue.runtime.esm.js:4560
ge.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
si.set @ vue.runtime.esm.js:4644
loadData @ ItemFormBase.js:120
await in loadData
reset @ ItemFormBase.js:73
await in reset
needReset @ ItemFormBase.js:60
rt @ vue.runtime.esm.js:1863
ri.run @ vue.runtime.esm.js:4584
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
dt @ vue.runtime.esm.js:1915
Promise.then
ot @ vue.runtime.esm.js:1942
gt @ vue.runtime.esm.js:1999
ni @ vue.runtime.esm.js:4418
ri.update @ vue.runtime.esm.js:4560
ge.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
si.set @ vue.runtime.esm.js:4644
editItem @ ItemListPageBase.js:134
click @ Integrations.vue:12
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
rt @ vue.runtime.esm.js:1863
An.e.$emit @ vue.runtime.esm.js:3903
click @ VBtn.ts:163
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
```

2nd error in browser console:
```js
ItemListPageBase.js:134 TypeError: Cannot read properties of null (reading 'name')
    at a.Do (IntegrationForm.vue:1:551)
    at e._render (vue.runtime.esm.js:3569:22)
    at a.i (vue.runtime.esm.js:4081:21)
    at ri.get (vue.runtime.esm.js:4495:25)
    at ri.run (vue.runtime.esm.js:4570:22)
    at Xn (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at dt (vue.runtime.esm.js:1915:12)
at @ vue.runtime.esm.js:1897
st @ vue.runtime.esm.js:1888
it @ vue.runtime.esm.js:1848
e._render @ vue.runtime.esm.js:3571
i @ vue.runtime.esm.js:4081
ri.get @ vue.runtime.esm.js:4495
ri.run @ vue.runtime.esm.js:4570
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
dt @ vue.runtime.esm.js:1915
Promise.then
ot @ vue.runtime.esm.js:1942
gt @ vue.runtime.esm.js:1999
ni @ vue.runtime.esm.js:4418
ri.update @ vue.runtime.esm.js:4560
ge.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
si.set @ vue.runtime.esm.js:4644
editItem @ ItemListPageBase.js:134
click @ Integrations.vue:12
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
rt @ vue.runtime.esm.js:1863
An.e.$emit @ vue.runtime.esm.js:3903
click @ VBtn.ts:163
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961
ItemFormBase.js:120 TypeError: Cannot read properties of null (reading 'debug')
    at a.br (TaskParamsForm.vue:1:298)
    at e._render (vue.runtime.esm.js:3569:22)
    at a.i (vue.runtime.esm.js:4081:21)
    at ri.get (vue.runtime.esm.js:4495:25)
    at ri.run (vue.runtime.esm.js:4570:22)
    at Xn (vue.runtime.esm.js:4326:13)
    at Array.<anonymous> (vue.runtime.esm.js:1989:12)
    at dt (vue.runtime.esm.js:1915:12)
at @ vue.runtime.esm.js:1897
st @ vue.runtime.esm.js:1888
it @ vue.runtime.esm.js:1848
e._render @ vue.runtime.esm.js:3571
i @ vue.runtime.esm.js:4081
ri.get @ vue.runtime.esm.js:4495
ri.run @ vue.runtime.esm.js:4570
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
dt @ vue.runtime.esm.js:1915
Promise.then
ot @ vue.runtime.esm.js:1942
gt @ vue.runtime.esm.js:1999
ni @ vue.runtime.esm.js:4418
ri.update @ vue.runtime.esm.js:4560
ge.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
si.set @ vue.runtime.esm.js:4644
loadData @ ItemFormBase.js:120
await in loadData
reset @ ItemFormBase.js:73
await in reset
needReset @ ItemFormBase.js:60
rt @ vue.runtime.esm.js:1863
ri.run @ vue.runtime.esm.js:4584
Xn @ vue.runtime.esm.js:4326
(anonymous) @ vue.runtime.esm.js:1989
dt @ vue.runtime.esm.js:1915
Promise.then
ot @ vue.runtime.esm.js:1942
gt @ vue.runtime.esm.js:1999
ni @ vue.runtime.esm.js:4418
ri.update @ vue.runtime.esm.js:4560
ge.notify @ vue.runtime.esm.js:730
set @ vue.runtime.esm.js:1055
si.set @ vue.runtime.esm.js:4644
editItem @ ItemListPageBase.js:134
click @ Integrations.vue:12
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
rt @ vue.runtime.esm.js:1863
An.e.$emit @ vue.runtime.esm.js:3903
click @ VBtn.ts:163
rt @ vue.runtime.esm.js:1863
n @ vue.runtime.esm.js:2188
s._wrapper @ vue.runtime.esm.js:6961

```

no errors on the server side logged

### Manual installation - system information

reverse proxy used:

```yml
  traefik:
    image: traefik:v2.10
    container_name: traefik_reverseproxy
    command:
      - "--log.level=DEBUG"
      - "--api.dashboard=true" 
      - "--providers.docker=true"  #
      - "--entrypoints.web.address=:80"  
      - "--entrypoints.websecure.address=:443" 
      - "--certificatesresolvers.myresolver.acme.email=admin@example.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json" 
      - "--certificatesresolvers.myresolver.acme.dnschallenge.provider=digitalocean" 
      - "--certificatesresolvers.myresolver.acme.dnschallenge.delaybeforecheck=0"

    ports:
      - "80:80"  
      - "443:443"  
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro  
      - /opt/semaphore/traefik/letsencrypt:/letsencrypt  
    environment:
      - DO_AUTH_TOKEN=myverysecuretoken 
    networks:
      - semaphore_network
    labels:
      - "traefik.http.routers.traefik.rule=Host(`traefik.example.com`)"
      - "traefik.http.routers.traefik.entrypoints=websecure"
      - "traefik.http.routers.traefik.service=api@internal"
      - "traefik.http.routers.traefik.tls=true"
      - "traefik.http.routers.traefik.tls.certresolver=myresolver"
    
 ```
