### ISSUE TITLE
Problem: HTTP 400/401 when creating or restoring a project respectively

### ISSUE THREAD

**Issue by chkpwd** [ansible-semaphore/semaphore#2663]
### Issue

I've created a new instance of Semaphore with oidc (authentik) setup. Disabled password authentication. Upon logon, I'm not able to create a new Project nor restore from a backup.

Warning when creating new project:
```
time="2024-12-26T13:57:13-05:00" level=warning msg="chkpwd is not permitted to edit users"
```

Error when attempting restore:
```
Loading config
Validating config
BoltDB /var/lib/semaphore/database.boltdb
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.11.2-0e9490c-1735214886
Interface 
Port :3000
Server is running

No additional python dependencies to install
Starting semaphore server
time="2024-12-26T13:57:03-05:00" level=error msg="websocket: close sent" fields.level=Error
time="2024-12-26T13:57:03-05:00" level=error msg="close tcp 172.17.0.3:3000->172.16.16.11:49210: use of closed network connection" fields.level=Error
time="2024-12-26T13:58:26-05:00" level=error msg="unsupported kind interface"
time="2024-12-26T13:58:26-05:00" level=error msg="unsupported kind interface"
goroutine 6 [running]:
runtime/debug.Stack()
        /usr/local/go/src/runtime/debug/stack.go:24 +0x64
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x1c
github.com/semaphoreui/semaphore/api/helpers.WriteError({0x15ef140, 0x40001e4ee0}, {0x15e97e0, 0x4000097eb0})
        /go/src/semaphore/api/helpers/helpers.go:122 +0x20c
github.com/semaphoreui/semaphore/api/projects.Restore({0x15ef140, 0x40001e4ee0}, 0x40001af440)
        /go/src/semaphore/api/projects/backup_restore.go:54 +0x1e0
net/http.HandlerFunc.ServeHTTP(0x15ef140?, {0x15ef140?, 0x40001e4ee0?}, 0xc500000000000000?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
github.com/semaphoreui/semaphore/api.authentication.func1({0x15ef140, 0x40001e4ee0}, 0x40001af440)
        /go/src/semaphore/api/auth.go:102 +0x58
net/http.HandlerFunc.ServeHTTP(0x7a1880?, {0x15ef140?, 0x40001e4ee0?}, 0xc?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
github.com/semaphoreui/semaphore/api.JSONMiddleware.func1({0x15ef140, 0x40001e4ee0}, 0x40001af440)
        /go/src/semaphore/api/router.go:45 +0xf0
net/http.HandlerFunc.ServeHTTP(0x0?, {0x15ef140?, 0x40001e4ee0?}, 0x0?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
github.com/semaphoreui/semaphore/api.StoreMiddleware.func1.1()
        /go/src/semaphore/api/router.go:36 +0x34
github.com/semaphoreui/semaphore/db.StoreSession({0x15fed68, 0x400015b808}, {0x40002e5f40, 0xc}, 0x40004f3780)
        /go/src/semaphore/db/Store.go:562 +0x60
github.com/semaphoreui/semaphore/api.StoreMiddleware.func1({0x15ef140, 0x40001e4ee0}, 0x40001af440)
        /go/src/semaphore/api/router.go:35 +0x10c
net/http.HandlerFunc.ServeHTTP(0x40001af440?, {0x15ef140?, 0x40001e4ee0?}, 0x7bbac0?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
github.com/semaphoreui/semaphore/cli/cmd.runService.func1.1({0x15ef140, 0x40001e4ee0}, 0x40001af440)
        /go/src/semaphore/cli/cmd/root.go:93 +0xe4
net/http.HandlerFunc.ServeHTTP(0x0?, {0x15ef140?, 0x40001e4ee0?}, 0x555900?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
github.com/semaphoreui/semaphore/api.Route.CORSMethodMiddleware.func1.1({0x15ef140, 0x40001e4ee0}, 0x40001af440)
        /go/src/semaphore/vendor/github.com/gorilla/mux/middleware.go:51 +0x7c
net/http.HandlerFunc.ServeHTTP(0x40001af320?, {0x15ef140?, 0x40001e4ee0?}, 0x25210?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
github.com/gorilla/mux.(*Router).ServeHTTP(0x40000eed80, {0x15ef140, 0x40001e4ee0}, 0x40001af200)
        /go/src/semaphore/vendor/github.com/gorilla/mux/mux.go:212 +0x194
github.com/semaphoreui/semaphore/cli/cmd.runService.ProxyHeaders.func2({0x15ef140, 0x40001e4ee0}, 0x40001af200)
        /go/src/semaphore/vendor/github.com/gorilla/handlers/proxy_headers.go:59 +0x130
net/http.HandlerFunc.ServeHTTP(0x40000c4f35?, {0x15ef140?, 0x40001e4ee0?}, 0x7f609cc7c8?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
github.com/semaphoreui/semaphore/cli/cmd.runService.cropTrailingSlashMiddleware.func3({0x15ef140, 0x40001e4ee0}, 0x40001af200)
        /go/src/semaphore/cli/cmd/server.go:27 +0xc4
net/http.HandlerFunc.ServeHTTP(0x10?, {0x15ef140?, 0x40001e4ee0?}, 0x40001e4ee0?)
        /usr/local/go/src/net/http/server.go:2166 +0x38
net/http.serverHandler.ServeHTTP({0x15ecbc8?}, {0x15ef140?, 0x40001e4ee0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:3137 +0xbc
net/http.(*conn).serve(0x40000ca480, {0x15f1038, 0x400019e390})
        /usr/local/go/src/net/http/server.go:2039 +0x508
created by net/http.(*Server).Serve in goroutine 1
        /usr/local/go/src/net/http/server.go:3285 +0x3f0
```

I'm suspecting the user being created via oidc is not an admin.

### Impact

Web-Frontend (what users interact with), Semaphore Project

### Installation method

Docker

### Database

BoltDB

### Browser

Firefox

### Semaphore Version

v2.11.2

### Logs & errors

![image](https://github.com/user-attachments/assets/e3095f4f-bbd6-41e9-84ae-9d96626a63f3)
![image](https://github.com/user-attachments/assets/af156e6c-59d8-4000-b38c-9254b2be35f4)

### Configuration
```
---
semaphore_container:
  - name: semaphore
    image: semaphoreui/semaphore:v2.11.2
    user: 1001:1001
    env:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: &name chkpwd
      SEMAPHORE_ADMIN_NAME: *name
      SEMAPHORE_ACCESS_KEY_ENCRYPTION: "{{ lookup('bws_cache', 'infra-semaphore-secrets').value.access_key_encryption }}"
      SEMAPHORE_PASSWORD_LOGIN_DISABLED: "true"
      SEMAPHORE_WEB_ROOT: https://semaphore.chkpwd.com
      ANSIBLE_HOST_KEY_CHECKING: "False"
      TZ: "{{ timezone }}"
    volumes:
      - "{{ configuration_path }}/semaphore/db:/var/lib/semaphore"
      - "{{ configuration_path }}/semaphore/config:/etc/semaphore"
      - "{{ configuration_path }}/semaphore/tmp:/tmp/semaphore"
    ports: [3005:3000]


semaphore_oidc_config:
  oidc_providers:
    authentik:
      display_name: "Sign in with SSO"
      provider_url: "https://authentik.chkpwd.com/application/o/semaphore-ui/"
      client_id: "semaphore"
      client_secret: "{{ lookup('bws_cache', 'infra-semaphore-secrets').value.oauth_client_secret }}"
      redirect_url: "https://semaphore.chkpwd.com/api/auth/oidc/authentik/redirect"
      scopes:
        - "email"
        - "openid"
        - "profile"
      username_claim: "preferred_username"
      name_claim: "preferred_username"
```

### Additional information

Deployed using ansible.

**Comment by vadimreutskiy** [comment]
I have the same issue and found the following reason behind code 400: if the backup file has the following configuration, it fails:
```
      "task_params": {
        "allow_debug": false
      },
```

By removing `"allow_debug": false`, I made Semaphore restore it successfully.

**Comment by fiftin** [comment]
Fixed in 2.13.7.

**Comment by wachcio** [comment]
I have same problem in Proxmox [https://community-scripts.github.io/ProxmoxVE/scripts?id=semaphore](url)
Version 2.13.10-f79e5ce-1744022098

**Comment by chkpwd** [comment]
I'm not sure this issue is solved. On the latest release (v2.14.7), I have created a container with the necessary elements:

```
    env:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: foo
      SEMAPHORE_ADMIN_NAME: foo 
      SEMAPHORE_ADMIN_PASSWORD:  bar
```

```yaml
semaphore_oidc_config:
  oidc_providers:
    authentik:
      display_name: "Sign in with SSO"
      provider_url: "https://authentik.chkpwd.com/application/o/semaphore-ui/"
      client_id: foo
      client_secret: bar
      redirect_url: "https://semaphore.chkpwd.com/api/auth/oidc/authentik/redirect"
      scopes:
        - "email"
        - "openid"
        - "profile"
      username_claim: "username" # user is foo
      name_claim: "name" # John Doe
      email_claim: "email" # authentik@domain.com
```
The important the bit that's displayed in the logs is the same error as before:
```
time="2025-05-03T16:30:07-04:00" level=warning msg="m0niuwye53ntewyr is not permitted to edit users"
```
Full logs:
```
Generating setup file  ...
Executing semaphore setup

Hello! You will now be guided through a setup to:

1. Set up configuration for a MySQL/MariaDB database
2. Set up a path for your playbooks (auto-created)
3. Run database Migrations
4. Set up initial semaphore user & password

What database to use:
   1 - MySQL
   2 - BoltDB
   3 - PostgreSQL
 (default 1): 
db filename (default /home/semaphore/database.boltdb): 
Playbook path (default /tmp/semaphore): 
Public URL (optional, example: https://example.com/semaphore): 
Enable email alerts? (yes/no) (default no): 
Enable telegram alerts? (yes/no) (default no): 
Enable slack alerts? (yes/no) (default no): 
Enable Rocket.Chat alerts? (yes/no) (default no): 
Enable Microsoft Team Channel alerts? (yes/no) (default no): 
Enable LDAP authentication? (yes/no) (default no): 
Config output directory (default /home/semaphore): 
Running: mkdir -p /etc/semaphore..
Configuration written to /etc/semaphore/config.json..
Loading config
Validating config
 Pinging db..
Running db Migrations..
Executing migration v0.0.0 (at 2025-05-03 20:23:22.770444604 +0000 UTC)...
Executing migration v1.0.0 (at 2025-05-03 20:23:22.782400224 +0000 UTC)...
Executing migration v1.2.0 (at 2025-05-03 20:23:22.786552959 +0000 UTC)...
Executing migration v1.3.0 (at 2025-05-03 20:23:22.790493457 +0000 UTC)...
Executing migration v1.4.0 (at 2025-05-03 20:23:22.794648341 +0000 UTC)...
Executing migration v1.5.0 (at 2025-05-03 20:23:22.799235072 +0000 UTC)...
Executing migration v1.6.0 (at 2025-05-03 20:23:22.803540714 +0000 UTC)...
Executing migration v1.7.0 (at 2025-05-03 20:23:22.807983873 +0000 UTC)...
Executing migration v1.8.0 (at 2025-05-03 20:23:22.812069479 +0000 UTC)...
Executing migration v1.9.0 (at 2025-05-03 20:23:22.816096254 +0000 UTC)...
Executing migration v2.2.1 (at 2025-05-03 20:23:22.821097925 +0000 UTC)...
Executing migration v2.3.0 (at 2025-05-03 20:23:22.825144477 +0000 UTC)...
Executing migration v2.3.1 (at 2025-05-03 20:23:22.830220907 +0000 UTC)...
Executing migration v2.3.2 (at 2025-05-03 20:23:22.834383161 +0000 UTC)...
Executing migration v2.4.0 (at 2025-05-03 20:23:22.841998344 +0000 UTC)...
Executing migration v2.5.0 (at 2025-05-03 20:23:22.852423072 +0000 UTC)...
Executing migration v2.5.2 (at 2025-05-03 20:23:22.857044655 +0000 UTC)...
Executing migration v2.7.1 (at 2025-05-03 20:23:22.861694145 +0000 UTC)...
Executing migration v2.7.4 (at 2025-05-03 20:23:22.866097008 +0000 UTC)...
Executing migration v2.7.6 (at 2025-05-03 20:23:22.871261307 +0000 UTC)...
Executing migration v2.7.8 (at 2025-05-03 20:23:22.875766743 +0000 UTC)...
Executing migration v2.7.9 (at 2025-05-03 20:23:22.880382715 +0000 UTC)...
Executing migration v2.7.10 (at 2025-05-03 20:23:22.884244621 +0000 UTC)...
Executing migration v2.7.12 (at 2025-05-03 20:23:22.888730742 +0000 UTC)...
Executing migration v2.7.13 (at 2025-05-03 20:23:22.893003236 +0000 UTC)...
Executing migration v2.8.0 (at 2025-05-03 20:23:22.897794391 +0000 UTC)...
Executing migration v2.8.1 (at 2025-05-03 20:23:22.902473436 +0000 UTC)...
Executing migration v2.8.7 (at 2025-05-03 20:23:22.90746746 +0000 UTC)...
Executing migration v2.8.8 (at 2025-05-03 20:23:22.913563287 +0000 UTC)...
Executing migration v2.8.20 (at 2025-05-03 20:23:22.91837172 +0000 UTC)...
Executing migration v2.8.25 (at 2025-05-03 20:23:22.923858683 +0000 UTC)...
Executing migration v2.8.26 (at 2025-05-03 20:23:22.928484896 +0000 UTC)...
Executing migration v2.8.36 (at 2025-05-03 20:23:22.93428917 +0000 UTC)...
Executing migration v2.8.38 (at 2025-05-03 20:23:22.938579627 +0000 UTC)...
Executing migration v2.8.39 (at 2025-05-03 20:23:22.943450485 +0000 UTC)...
Executing migration v2.8.40 (at 2025-05-03 20:23:22.947938162 +0000 UTC)...
Executing migration v2.8.42 (at 2025-05-03 20:23:22.954173655 +0000 UTC)...
Executing migration v2.8.51 (at 2025-05-03 20:23:22.959464786 +0000 UTC)...
Executing migration v2.8.57 (at 2025-05-03 20:23:22.963173897 +0000 UTC)...
Executing migration v2.8.58 (at 2025-05-03 20:23:22.967812869 +0000 UTC)...
Executing migration v2.8.91 (at 2025-05-03 20:23:22.973458478 +0000 UTC)...
Executing migration v2.9.6 (at 2025-05-03 20:23:22.978041154 +0000 UTC)...
Executing migration v2.9.46 (at 2025-05-03 20:23:22.98252135 +0000 UTC)...
Executing migration v2.9.60 (at 2025-05-03 20:23:22.986191461 +0000 UTC)...
Executing migration v2.9.61 (at 2025-05-03 20:23:22.990507343 +0000 UTC)...
Executing migration v2.9.62 (at 2025-05-03 20:23:22.994375878 +0000 UTC)...
Executing migration v2.9.70 (at 2025-05-03 20:23:22.997832084 +0000 UTC)...
Executing migration v2.9.97 (at 2025-05-03 20:23:23.001660842 +0000 UTC)...
Executing migration v2.9.100 (at 2025-05-03 20:23:23.006086612 +0000 UTC)...
Executing migration v2.10.12 (at 2025-05-03 20:23:23.009298653 +0000 UTC)...
Executing migration v2.10.15 (at 2025-05-03 20:23:23.012146013 +0000 UTC)...
Executing migration v2.10.16 (at 2025-05-03 20:23:23.015037225 +0000 UTC)...
Executing migration v2.10.24 (at 2025-05-03 20:23:23.01773942 +0000 UTC)...
Executing migration v2.10.26 (at 2025-05-03 20:23:23.020681631 +0000 UTC)...
Executing migration v2.10.28 (at 2025-05-03 20:23:23.023882543 +0000 UTC)...
Executing migration v2.10.33 (at 2025-05-03 20:23:23.031003638 +0000 UTC)...
Executing migration v2.10.46 (at 2025-05-03 20:23:23.037417202 +0000 UTC)...
Executing migration v2.11.5 (at 2025-05-03 20:23:23.041022425 +0000 UTC)...
Executing migration v2.12.0 (at 2025-05-03 20:23:23.044955311 +0000 UTC)...
Executing migration v2.12.3 (at 2025-05-03 20:23:23.048785328 +0000 UTC)...
Executing migration v2.12.4 (at 2025-05-03 20:23:23.052719159 +0000 UTC)...
Executing migration v2.12.5 (at 2025-05-03 20:23:23.056368029 +0000 UTC)...
Executing migration v2.12.15 (at 2025-05-03 20:23:23.059862272 +0000 UTC)...
Executing migration v2.13.0 (at 2025-05-03 20:23:23.062906611 +0000 UTC)...
Executing migration v2.14.0 (at 2025-05-03 20:23:23.066473983 +0000 UTC)...
Executing migration v2.14.1 (at 2025-05-03 20:23:23.069700413 +0000 UTC)...
Executing migration v2.14.5 (at 2025-05-03 20:23:23.072479089 +0000 UTC)...
Executing migration v2.14.7 (at 2025-05-03 20:23:23.075360467 +0000 UTC)...
Migrations Finished


time="2025-05-03T16:23:23-04:00" level=warning msg="no rows in result set" fields.level=Warn
 > Username:  > Email:  > Your name:  > Password: 
 You are all setup chkpwd!
 Re-launch this program pointing to the configuration file

./semaphore server --config /etc/semaphore/config.json

 To run as daemon:

nohup ./semaphore server --config /etc/semaphore/config.json &

 You can login with admin@localhost or chkpwd.
No additional python dependencies to install
Starting semaphore server
Loading config
Validating config
BoltDB /var/lib/semaphore/database.boltdb
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.14.7-f77a5a0-1746171973
Interface 
Port :3000
Server is running
No additional python dependencies to install
Starting semaphore server
Loading config
Validating config
BoltDB /var/lib/semaphore/database.boltdb
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.14.7-f77a5a0-1746171973
Interface 
Port :3000
Server is running
time="2025-05-03T16:30:07-04:00" level=warning msg="m0niuwye53ntewyr is not permitted to edit users"
```
This is the POST request sent to the backend:
```
POST:
  scheme: https
  host: semaphore.chkpwd.com
  filename: /api/projects

name: test
```
