### ISSUE TITLE
Problem: Cannot configure SMTP for Azure communication service

### ISSUE THREAD

**Issue by remohoeppli** [ansible-semaphore/semaphore#2688]
### Issue

I run semaphore as a docker container configured using docker compose. I tried configuring the email alerts for Azure communication service, but cannot make it work. My docker compose file looks as follows (with changed usernames, emails, and passwords).

```
services:
  semaphore:
    image: semaphoreui/semaphore:latest
    restart: always
    container_name: semaphore
    ports:
      - 3000:3000
    environment:
      SEMAPHORE_DB_DIALECT: bolt
      SEMAPHORE_ADMIN: admin
      SEMAPHORE_ADMIN_PASSWORD: admin_pw
      SEMAPHORE_ADMIN_NAME: Admin
      SEMAPHORE_ADMIN_EMAIL: test@test.test
      SEMAPHORE_EMAIL_ALERT: True
      SEMAPHORE_EMAIL_SENDER: sendermail@test.test
      SEMAPHORE_EMAIL_HOST: smtp.azurecomm.net
      SEMAPHORE_EMAIL_PORT: 587
      SEMAPHORE_EMAIL_USERNAME: username
      SEMAPHORE_EMAIL_PASSWORD: password
      SEMAPHORE_EMAIL_SECURE: True
```

When the service is trying to send a mail I see the following logentry:

`time="2025-01-09T14:15:57Z" level=error msg="504 5.7.4 Unrecognized authentication type" fields.level=Error`

When switching the var SEMAPHORE_EMAIL_SECURE to false, I get the following entry:

`time="2025-01-09T14:20:37Z" level=error msg="451 5.7.3 STARTTLS is required to send mail" fields.level=Error`

Azure communication service does not allow any other port than 587, so I'm mostly stuck. Any advice would be much appreciated.

### Impact

Service (scheduled tasks, alerts)

### Installation method

Docker

### Database

BoltDB

### Browser

Chrome

### Semaphore Version

v2.11.2-0e9490c-1735214878

### Logs & errors

No additional python dependencies to install
Starting semaphore server
Loading config
Validating config
BoltDB /var/lib/semaphore/database.boltdb
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.11.2-0e9490c-1735214878
Interface 
Port :3000
Server is running
time="2025-01-09T14:15:53Z" level=info msg="Task 2147483643 added to queue"
time="2025-01-09T14:15:54Z" level=info msg="Set resource locker with TaskRunner 2147483643"
time="2025-01-09T14:15:54Z" level=info msg="Task 2147483643 removed from queue"
time="2025-01-09T14:15:57Z" level=error msg="remove /tmp/semaphore/inventory_2147483643: no such file or directory"
time="2025-01-09T14:15:57Z" level=error msg="504 5.7.4 Unrecognized authentication type" fields.level=Error
time="2025-01-09T14:15:57Z" level=info msg="Stopped running TaskRunner 2147483643"
time="2025-01-09T14:15:57Z" level=info msg="Release resource locker with TaskRunner 2147483643"

No additional python dependencies to install
Starting semaphore server
Loading config
Validating config
BoltDB /var/lib/semaphore/database.boltdb
Tmp Path (projects home) /tmp/semaphore
Semaphore v2.11.2-0e9490c-1735214878
Interface 
Port :3000
Server is running
time="2025-01-09T14:20:34Z" level=info msg="Task 2147483643 added to queue"
time="2025-01-09T14:20:35Z" level=info msg="Set resource locker with TaskRunner 2147483643"
time="2025-01-09T14:20:35Z" level=info msg="Task 2147483643 removed from queue"
time="2025-01-09T14:20:37Z" level=warning msg="read |0: file already closed" error="Failed to read TaskRunner output"
time="2025-01-09T14:20:37Z" level=error msg="remove /tmp/semaphore/inventory_2147483643: no such file or directory"
time="2025-01-09T14:20:37Z" level=error msg="451 5.7.3 STARTTLS is required to send mail" fields.level=Error
time="2025-01-09T14:20:37Z" level=info msg="Stopped running TaskRunner 2147483643"
time="2025-01-09T14:20:37Z" level=info msg="Release resource locker with TaskRunner 2147483643"
