### ISSUE TITLE
Feature: Inventory Integration to Hypervisors

### ISSUE THREAD

**Issue by tl87** [ansible-semaphore/semaphore#2709]
### Related to

Other

### Impact

major improvement to user experience

### Missing Feature

AWX and AAP offer integration capabilities with various hypervisors, such as VMware, through an API provided by the hypervisor. This integration enables the creation of a dynamic inventory.

As a result, the inventory is automatically updated based on the hosts in VMware or other hypervisors, eliminating the need for manual updates to the inventory file. This ensures that the inventory remains current without relying on others to manage updates, providing an always-up-to-date reflection of the hosts in VMware or another hypervisor.

### Implementation

Utilize the API provided by the various hypervisors to retrieve hostnames, which can then undergo a validation process to ensure proper formatting. Once validated, an inventory can be generated and made available for use in Ansible Semaphore. The inventory can be set to update automatically on an hourly basis, or an option can be provided to manually trigger an inventory update as needed.

### Design

Although I don't have programming experience, I believe that utilizing an API from a hypervisor to retrieve hostnames may require authentication. This would likely involve setting up a user or API key to allow access to the hypervisor and pull the necessary hostnames. Once retrieved, Semaphore could then format the data and generate the inventory.

Given that different hypervisors have distinct API request structures and formats, I assume that separate integrations would need to be developed for each. It might be beneficial to begin with the most commonly used hypervisors, such as VMware and Proxmox.

**Comment by tl87** [comment]
I found a work-around and you might get some value for adding it to your documentation for Ansible Semaphore, because I can see more people being interested in adding VMware as a dynamic inventory.

The guide is as follows:

# ansible - vmware inventory

this guide will help set up a dynamic inventory file in yaml format, where it uses the Ansible collection module community.vmware, the python packages pyVmomi, requests and vSphere Automation SDK.

1. Install python packages:

```bash
pip install \
	ansible \
	requests \
	pyVmomi \
	git+https://github.com/vmware/vsphere-automation-sdk-python.git
```

2. Install Ansible collection:

```bash
ansible collection install \
	community.vmware
```

3. Create a service account in VMware, with the correct API permissions.

4. Add below to ansible.cfg, to load plugin:

```bash
[inventory]
enable_plugins = vmware_vm_inventory
```

5. Create the inventory, let's call it `vmware.yaml`, and add the credentials from the VMware user and the hostname for the vcenter:

```yaml
plugin: vmware_vm_inventory
strict: false
hostname: vcenter01.domain.com
username: vmware-api-user
password: !vault |
  $ANSIBLE_VAULT;1.1;AES256
  3932.....
validate_certs: false
with_tags: false
groups:
  VMs: true
```

You can use a clear-text-password, but I recommend using an Ansible encrypted string.

To create encrypted string, use the command below, and the output can then be added to `vmware.yaml` in the **password** field:

```bash
ansible-vault encrypt_string 'PUT YOUR PASSWORD HERE'
```

6. To test if it works, use the command below:

```bash
ansible-inventory -i vmware.yml --list --ask-vault-pass
```

If it all goes well, you should see a list of hosts, it might seem like it's stuck, but that could be that you have alot of VM's or slow connection. Don't worry, simply wait.

Now you are done.

### Bonus tip

You can add the inventory to Ansible Semaphore, just make sure you have created a secret for the encrypted string. This assumes you have setup an Repository in Semaphore, where `vmware.yaml` is committed to.

*This guide is made on Ansible Semaphore version v2.11.2, things might be subject to change in newer versions.*

1. Sign into Ansible Semaphore's webgui.

2. Navigate `Key Store` and click on `New Key`.

Set the following:

- Key Name: vmware encrypted string password
- Type: Login with password
- Login (Optional): {blank}
- Password: {add the password used to encrypt the string in step 5}

Click on the `Create button`.

3. Navigate to `Inventory` and click on `New Inventory`.

Set the following:

- Name: vmware inventory
- User credentials: vmware encrypted string password
- Sudo Credentials (Optional): {blank}
- Type: File
- Path to Inventory file: {set path to vmware.yaml corresponding to where it's located in the repository}
- Repository: {set to the repo, where vmware.yaml exists}

4. Done

You can use `--limit` to limit what host should be used when using this inventory.

---

**Comment by tl87** [comment]
The plugin **vmware_vm_inventory** is no longer recommended to use, the new way is to use **vmware.vmware.vms**.

However when using the either plugin, I'm having trouble with Ansible Semaphore getting the hosts from VMware.

You can run the ansible-inventory command and get the host in CLI, but it seems like Semaphore does not parse the hosts or something.

### To test with **vmware.vmware.vms**:

1. Make sure that the user, you are using has the correct permissions in VMware to get the inventory via API.

2. Create the file vmware_vms.yaml, and add the following, replace to macth your environment:

```yaml
plugin: vmware.vmware.vms
hostname: {vcenter-fqdn or ip}
username: {vcenter api username}
password: !vault |
    $ANSIBLE_VAULT;1.1;AES256
    32..{encrypted vault password for vmware api user}
validate_certs: false
properties:
    - 'name'
    - 'config.name'
    - 'guest.ipAddress'
compose:
    ansible_host: 'guest.ipAddress'
    composed_var: 'config.name'
    ansible_port: "'5985'"
    ansible_connection: "'winrm'"
    ansible_winrm_transport: "'kerberos'"
    ansible_winrm_server_cert_validation: "'ignore'"
    ansible_winrm_kerberos_delegation: "'true'"
    ansible_winrm_scheme: "'http'"
    ansible_user: "'{username@DOMAIN.TLD}'"
    ansible_password: "'!vault |
        $ANSIBLE_VAULT;1.1;AES256
        326...{encrypted vault string for the user account that runs the ansible jobs on windows}'"
groups:
    VMs: true
filters:
    - runtime.powerState == "poweredOn"
hostnames:
    - config.name
```

3. Create the vault_password file with the password for your the vault password.

4. Run command in CLI to test:

```bash
ansible-inventory -i /path/to/inventory/vmware_vms.yaml --vault-password-file /path/to/vault_password --list
```

---

In semaphore, when using vmware_vms.yaml as inventory with the correct vault password, etc. The hosts are not parsed and Semaphore simply gives you "skipping: no hosts matched".

Debug output:

```
Loading collection vmware.vmware from /opt/semaphore/apps/ansible/11.1.0/venv/lib/python3.11/site-packages/ansible_collections/vmware/vmware
Unable to parse /tmp/semaphore/inventory_1499/inventory/vmware_vms.yaml as an inventory source
[WARNING]: No inventory was parsed, only implicit localhost is available
[WARNING]: provided hosts list is empty, only localhost is available.
```

It works with ansible-inventory command, but Im betting that the inventory is missing something for it to work with semaphore?
