### ISSUE TITLE
Docs: Website compose generator fails with postgres in same compose

### ISSUE THREAD

**Issue by Sleuth56** [ansible-semaphore/semaphore#2714]
### Problem

When you set the following settings on the container configurator page semaphore fails to start because the db isn't up yet. I tested this with postgres but mysql probably has the same issue. The solution is quite simple. adding `depends_on` to the semaphore container to make it start after the database is up will fix this issue. I couldn't find the website repository or I would have PRed it.
https://semaphoreui.com/install/docker/2_11/
![Image](https://github.com/user-attachments/assets/d11227fa-951a-49ac-a951-162781717184)
```
services:
    semaphore_db:
        image: postgres
        environment:
            POSTGRES_USER: semaphore
            POSTGRES_PASSWORD: password123
            POSTGRES_DB: semaphore
        volumes:
            - semaphore_postgres:/var/lib/postgresql/data
        networks:
            - semaphore_network
    semaphore:
        ports:
            - 3000:3000
        image: semaphoreui/semaphore:v2.11.2
        environment:
            SEMAPHORE_DB_DIALECT: postgres
            SEMAPHORE_DB_HOST: semaphore_db
            SEMAPHORE_DB_NAME: semaphore
            SEMAPHORE_DB_USER: semaphore
            SEMAPHORE_DB_PASS: password123
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: admin
            SEMAPHORE_ADMIN_NAME: admin
            SEMAPHORE_ADMIN_EMAIL: admin@example.com
            ANSIBLE_HOST_KEY_CHECKING: False
        volumes:
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
        networks:
            - semaphore_network
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
    semaphore_postgres:
networks:
    semaphore_network: {driver: "bridge"}
```

### Related to

Configuration
