### ISSUE TITLE
ProblemPlatform linux on host is using the discovered Python interpreter at /usr/bin/python3.11:

### ISSUE THREAD

**Issue by itmcdonalds** [ansible-semaphore/semaphore#2739]
### Issue

<img width="814" alt="Image" src="https://github.com/user-attachments/assets/818693ad-8882-45b5-8c3b-29f53eeba92d" />

### Impact

Web-Frontend (what users interact with)

### Installation method

Docker

### Database

MySQL

### Browser

Safari

### Semaphore Version

v2.12.4

### Ansible Version

```bash
ansible [core 2.18.2]
```

### Logs & errors

[WARNING]: Platform linux on host is using the discovered Python interpreter at /usr/bin/python3.11, but future installation of another Python interpreter could change the meaning of that path.

### Manual installation - system information

Linux semaphore 6.1.0-31-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.128-1 (2025-02-07) x86_64 Linux

### Additional information

I realize this can be fixed by adding "interpreter_python=auto_silent" in ansible.cfg. But can this be fixed with a semaphore docker variable? Or some automated way during installation?

**Comment by mircsicz** [comment]
TLDR:

Note for the next one coming by in search for a solution:

Add a line like this to your ansible.cfg (in your repo from which you pull the playbooks)
`interpreter_python = auto_silent`

**Comment by JonasGroeger** [comment]
I chose to be explicit by setting `ansible_interpreter_python`:

```
# You can have Ansible auto-discover a suitable interpreter or set it yourself.
# See https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html
ansible_python_interpreter: "/usr/bin/python3"
```

Full context:

```
---
all:
  hosts:
    test_container:
        # You can have Ansible auto-discover a suitable interpreter or set it yourself.
        # See https://docs.ansible.com/ansible/latest/reference_appendices/interpreter_discovery.html
        ansible_python_interpreter: "/usr/bin/python3"
```
