### ISSUE TITLE
Feature: pywinrm[kerberos] support built into docker containers

### ISSUE THREAD

**Issue by gawainXX** [ansible-semaphore/semaphore#2741]
### Related to

Docker

### Impact

nice to have for enterprise usage

### Missing Feature

Greetings, It's nice to see there is winrm support built into the docker container, although that support is fairly limited without kerberos support.

I have to install the following within the docker container in order to get kerberos auth (via vaulted creds) to work against domain member systems.

apk packages:
- krb5
- krb5-dev 
- gcc 
- musl-dev 
- python3-dev

python pip packages:
- pywinrm[kerberos]

### Implementation

Would it be possible to add these into the docker build?

**Comment by gawainXX** [comment]
I forgot to add, I'm currently using semaphoreui/semaphore:v2.12.4-ansible2.16.5

**Comment by best-74** [comment]
+1 on this.. Seems wierd leaving this out. My primary use case is managing both windows & linux servers. Would make it a little bit more simple to deploy.

**Comment by tradiuz** [comment]
I've had to use a post_start docker hook in my compose to handle this:

```yaml
services:
  semaphore:
    post_start:
      - user: root 
        command: ln -s /home/semaphore/.ssh/known_hosts /etc/ssh/ssh_known_hosts
      - user: root
        command: >
          apt-get install  krb5 krb5-dev gcc  musl-dev
          python3-dev  libkrb5-dev  kbr5-config &&  pip install -r
          /tmp/win_requirements.txt
# ... the rest of the file
```
