### ISSUE TITLE
Problem: Can't logon to web UI after a docker compose down/up

### ISSUE THREAD

**Issue by TGH-TH** [ansible-semaphore/semaphore#2761]
### Issue

Unable to log onto the web UI with the default admin acct after the containers have been stopped and removed and then started again.

Flushing all Semaphore data (purge volumes) and then docker compose up works but then you are back to an initial install state

Any (some?) running of semaphore commands within the container ends badly

```
~ $ semaphore user list
Loading config
Validating config
panic: timeout

goroutine 1 [running]:
github.com/semaphoreui/semaphore/db/bolt.(*BoltDb).openDbFile(0xc000247808)
        /go/src/semaphore/db/bolt/BoltDb.go:119 +0x1ab
github.com/semaphoreui/semaphore/db/bolt.(*BoltDb).Connect(0xc000247808, {0x0, 0x0})
        /go/src/semaphore/db/bolt/BoltDb.go:148 +0x33
github.com/semaphoreui/semaphore/cli/cmd.createStore({0x0, 0x0})
        /go/src/semaphore/cli/cmd/root.go:169 +0x62
github.com/semaphoreui/semaphore/cli/cmd.init.func17(0xc000219600?, {0xcdb7cb?, 0x4?, 0xcdb7cf?})
        /go/src/semaphore/cli/cmd/user_list.go:17 +0x35
github.com/spf13/cobra.(*Command).execute(0x1ff98c0, {0x2063300, 0x0, 0x0})
        /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:989 +0xab1
github.com/spf13/cobra.(*Command).ExecuteC(0x1ff7080)
        /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /go/src/semaphore/vendor/github.com/spf13/cobra/command.go:1041
github.com/semaphoreui/semaphore/cli/cmd.Execute()
        /go/src/semaphore/cli/cmd/root.go:57 +0xc5
main.main()
        /go/src/semaphore/cli/main.go:8 +0xf
~ $ 
```
config.json
```
cat /etc/semaphore/config.json
{
        "bolt": {
                "host": "semaphore_db"
        },
        "dialect": "bolt",
        "tmp_path": "/tmp/semaphore",
        "web_host": "http://semaphore.domain.com:2000",
        "cookie_hash": "zQQX6mSyPTiA1CygTV4qiu7WZjPiDUAPi7n8FRHleHpR6yK32mTs/HZ4k=",
        "cookie_encryption": "bgVfaaulHRU/VT4gTVi7n8FRHk2uxi65C3FTK4hJo=",
        "access_key_encryption": "EFJEgokmB6mSyPTiA1CybXJkhwMUyTid6YrCBbJ0="
 }~ $
```
docker-compose.yml
```
services:
    semaphore_db:
        image: postgres
        environment:
            POSTGRES_USER: semaphore
            POSTGRES_PASSWORD: GIpStaBKlS3lnLmr0TqO
            POSTGRES_DB: semaphore
        networks:
            - semaphore_network
    semaphore:
        ports:
            - 2000:2000
        depends_on:
            - semaphore_db
        image: semaphoreui/semaphore:v2.12.9
        environment:
            SEMAPHORE_DB_DIALECT: bolt
            SEMAPHORE_DB_HOST: semaphore_db
            SEMAPHORE_DB_NAME: semaphore
            SEMAPHORE_DB_USER: semaphore
            SEMAPHORE_DB_PASS: GIpStaBKlS3lnLmr0TqO
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: changeme
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
            SEMAPHORE_PORT: "2000"
            SEMAPHORE_WEB_ROOT: "http://semaphore.domain.com:2000"
            ANSIBLE_HOST_KEY_CHECKING: "False"
        volumes:
            - type: bind
              source: /home/semaphore/projects/ansible
              target: /etc/ansible
              read_only: true
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
        networks:
            - semaphore_network
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
    semaphore_mysql:
networks:
    semaphore_network:
        driver: bridge
```

### Impact

Web-Frontend (what users interact with)

### Installation method

Docker

### Database

Postgres

### Browser

Microsoft Edge

### Semaphore Version

v2.12.9-e693f31-1739369571

### Ansible Version

```bash

```

### Logs & errors

```
semaphore-semaphore-1     | Migrations Finished
semaphore-semaphore-1     | BoltDB semaphore_db
semaphore-semaphore-1     | Tmp Path (projects home) /tmp/semaphore
semaphore-semaphore-1     | Semaphore v2.12.9-e693f31-1739369571
semaphore-semaphore-1     | Interface
semaphore-semaphore-1     | Port 2000
semaphore-semaphore-1     | Server is running
```

### Manual installation - system information

None - behaviour is the same with (Caddy) and without

**Comment by TGH-TH** [comment]
I noticed a lack of persistence in the docker postgres setup - I was sure that would be the cause so have reset the whole thing according to the config below - The issue STILL persists however much to my suprise....

```
services:
    semaphore_db:
        image: postgres
        environment:
            POSTGRES_USER: semaphore
            POSTGRES_PASSWORD: GIpSr0TqOtaBKlS3lnLm
            POSTGRES_DB: semaphore
        volumes:
            - semaphore_postgres:/var/lib/postgresql/data
        networks:
            - semaphore_network
    semaphore:
        ports:
            - 2000:2000
        depends_on:
            - semaphore_db
        image: semaphoreui/semaphore:v2.12.9
        environment:
            SEMAPHORE_DB_DIALECT: bolt
            SEMAPHORE_DB_HOST: semaphore_db
            SEMAPHORE_DB_NAME: semaphore
            SEMAPHORE_DB_USER: semaphore
            SEMAPHORE_DB_PASS: GIpSr0TqOtaBKlS3lnLm
            SEMAPHORE_ADMIN: admin
            SEMAPHORE_ADMIN_PASSWORD: changeme
            SEMAPHORE_ADMIN_NAME: Admin
            SEMAPHORE_ADMIN_EMAIL: admin@localhost
            SEMAPHORE_PORT: "2000"
            SEMAPHORE_WEB_ROOT: "http://semaphore.domain.com:2000"
            ANSIBLE_HOST_KEY_CHECKING: "False"
        volumes:
            - type: bind
              source: /home/admin/projects/ansible
              target: /etc/ansible
              read_only: true
            - semaphore_data:/var/lib/semaphore
            - semaphore_config:/etc/semaphore
            - semaphore_tmp:/tmp/semaphore
        networks:
            - semaphore_network
volumes:
    semaphore_data:
    semaphore_config:
    semaphore_tmp:
    semaphore_postgres:
networks:
    semaphore_network:
        driver: bridge
```
