### ISSUE TITLE
Question: How to show Ansible task as successful with exit code 4

### ISSUE THREAD

**Issue by madozu** [ansible-semaphore/semaphore#2916]
### Question

I have some hosts that might be turned off when an Ansible task runs. In that case, Ansible returns RC=4 (RUN_UNREACHABLE_HOSTS) and SemaphoreUI marks this Ansible task as failed as shown below:

`Running app failed: exit status 4`

How can I treat a specific non-zero exit code (e.g. RC=4) from an Ansible task as successful, so the SemaphoreUI shows it's status as "Success" and does not send an error notification email?

### Related to

Ansible (task execution)

**Comment by svennd** [comment]
I don't think this is the answer you are looking for but : 
```
ignore_unreachable: true
```
But this would still report an error. You can try to wrap ansible-playbook in a bash script : 
ansible-playbook your_playbook.yml
```
rc=$?
if [ $rc -eq 4 ]; then
  echo "Ignoring RC=4 (unreachable hosts)"
  exit 0
else
  exit $rc
fi
```

**Comment by madozu** [comment]
Thanks @svennd for the reply :-) Your approach surely works, but going the "bash script" way basically means that I am losing all the dynamic settings (when running the task) like adding parameters and the like.

I might raise a feature request to be able to specify additional "successful" return codes.

**Comment by svennd** [comment]
Hey @madozu 

Alternatively you could run it localhost: first task is a ping and then delegate if the server is up (else skip). Not sure if it would work but you could use import_playbook for some clean yaml code.

That would be a pretty advanced feature for not that many use cases I think.

**Comment by madozu** [comment]
Thanks again @svennd , you pointed me to the right direction 😄. Just to share what I came up with:

```
- hosts: all
  gather_facts: false
  ignore_errors: true
  serial: 1
  tasks:
    - name: Check if host is alive
      command: ping -c 2 {{ inventory_hostname }}
      delegate_to: localhost
      changed_when: false
      register: ping_result

    - name: Add host to running hosts group
      add_host: { name: '{{ inventory_hostname }}', groups: running }
      changed_when: false
      when: ping_result.rc == 0

- name: Whatever tasks you need to perform on running systems
  hosts: running
  tasks:
```
The only thing I was struggling with is the fact that the module "add_hosts" (for a reason beyond my understanding) only runs once in a batch of hosts. So I had to set **serial: 1** in the first play to ensure that "add_host" is run for every server. Not pretty, but it works.
