### ISSUE TITLE
pull Inventory from git with group_vars support

### ISSUE THREAD

**Issue by lukeshaughnessy** [ansible-semaphore/semaphore#376]
Our current inventory has variables broken out in yml files in a group_vars folder. I don't see a way of adding this to the Inventory, which appears to be a single flat file. Why not pull the inventory and folder structure from git?

**Comment by strangeman** [comment]
Why not? You can create the empty inventory (without any content) in Semaphore and use your own inventory from the repository. For example, this is my playbooks repo structure:
```
.
├── files
├── filter_plugins
├── group_vars
├── host_vars
├── inventory
├── roles
├── templates
├── tests
├── ansible.cfg
├── applications.yml
├── integration-test.yml
├── Jenkinsfile
├── lint.sh
├── README.md
├── test.yml
└── Vagrantfile
```
I pass inventory file location via Extra CLI Arguments in Task template:
`["-i", "inventory/test/", "-v", "-D"]`

**Comment by deadmalc** [comment]
Adding an option of pulling the inventory from a git repo would be really useful.

**Comment by twhiston** [comment]
actually ansible should do the heavy lifting for group_vars files as long as they are in the correct folder and named correctly for your hosts groups (or in an all.yml file), you should not really need to add them in any specific way, see https://stackoverflow.com/a/23784771 for an explanation of this. 
If you really must pass them somehow you can pass an inventory with the -i option as @strangeman suggested, so i'm going to close this.

**Comment by don-rumata** [comment]
I encountered the same problem:

`ansible v2.12.9`

`semaphore v2.8.67`

```
/tmp/semaphore/
├── group_vars
│   ├── passwd-linux-ecc.yml
│   └── test3.yml -> passwd-linux-ecc.yml
├── install-jq.yml
├── inventory
│   └── ubuntu.ini
```

If you start in manual mode, everything is fine: [![asciicast](https://asciinema.org/a/n1du5vkA84AUrTWJYI88nqfyq.svg)](https://asciinema.org/a/n1du5vkA84AUrTWJYI88nqfyq)

But through semaphore - it asks for a password:

```
2:30:30 AM
Task 2147483630 added to queue
2:30:33 AM
Preparing: 2147483630
2:30:33 AM
Prepare TaskRunner with template: Install JQ
2:30:33 AM
No collections/requirements.yml file found. Skip galaxy install process.
2:30:33 AM
No roles/requirements.yml file found. Skip galaxy install process.
2:30:38 AM
Started: 2147483630
2:30:38 AM
Run TaskRunner with template: Install JQ
2:30:39 AM
[WARNING]: Invalid characters were found in group names but not replaced, use
2:30:39 AM
-vvvv to see details
2:30:39 AM
2:30:39 AM
PLAY [Install JQ] **************************************************************
2:30:41 AM
2:30:41 AM
TASK [Gathering Facts] *********************************************************
2:30:41 AM
ok: [10.10.15.68]
2:30:41 AM
2:30:41 AM
TASK [win_file] ****************************************************************
2:30:41 AM
skipping: [10.10.15.68]
2:30:41 AM
2:30:41 AM
TASK [win_path] ****************************************************************
2:30:41 AM
skipping: [10.10.15.68]
2:30:41 AM
2:30:41 AM
TASK [win_copy] ****************************************************************
2:30:41 AM
skipping: [10.10.15.68]
2:30:43 AM
2:30:43 AM
TASK [apt] *********************************************************************
2:30:43 AM
fatal: [10.10.15.68]: FAILED! => {"cache_update_time": 1664995338, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\" install 'jq' -o APT::Install-Recommends=yes' failed: E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\n", "rc": 100, "stderr": "E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)\nE: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?\n", "stderr_lines": ["E: Could not open lock file /var/lib/dpkg/lock-frontend - open (13: Permission denied)", "E: Unable to acquire the dpkg frontend lock (/var/lib/dpkg/lock-frontend), are you root?"], "stdout": "", "stdout_lines": []}
2:30:43 AM
2:30:43 AM
PLAY RECAP *********************************************************************
2:30:43 AM
10.10.15.68 : ok=1 changed=0 unreachable=0 failed=1 skipped=3 rescued=0 ignored=0
2:30:43 AM
2:30:43 AM
Running playbook failed: exit status 2
```

`install-jq.yml`:

```yaml
---
# WORK
  - name: Install JQ
    hosts: all
    strategy: free
    serial:
      - "100%"
    tasks:

    - name: Install JQ 4 Windows
      when: ansible_os_family == 'Windows'
      become: yes
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      block:
        - win_file:
            path: '%ProgramFiles%\jq\'
            state: directory
        - win_path:
            elements:
              - '{{ ansible_env.ProgramFiles }}\jq'
            state: present
        - win_copy:
            src: \\172.16.11.8\soft\jq\jq-{{ ansible_env.PROCESSOR_ARCHITECTURE }}.exe
            dest: '{{ ansible_env.ProgramFiles }}\jq\jq.exe'
            remote_src: yes
            force: yes
      tags:
        - windows
        - install
        - jq
        - json

    - name: Install JQ 4 Ubuntu
      when: ansible_distribution == 'Ubuntu'
      become: yes
      block:
        - apt:
            name: jq
            state: latest
            install_recommends: yes
      tags:
        - linux
        - ubuntu
        - install
        - jq
        - json

    - name: Install JQ 4 Ubuntu
      when: ansible_distribution in ['Fedora', 'Generic']
      become: yes
      block:
        - yum:
            name: jq
            state: latest
            install_recommends: yes
      tags:
        - linux
        - fedora
        - install
        - jq
        - json

    - name: Install jq 4 any linux
      when: ansible_system == 'Linux'
      become: yes
      package:
        name: jq
        state: latest
      tags:
        - linux
        - jq
        - install
```
