### ISSUE TITLE
ping route is not api compatible

### ISSUE THREAD

**Issue by twhiston** [ansible-semaphore/semaphore#522]
currently the ping route is in the api spec, but it's not actually a valid api route as it returns (output from dredd)
```
statusCode: 200
headers: 
    access-control-allow-credentials: true
    access-control-allow-origin: 
    date: Wed, 11 Apr 2018 21:08:39 GMT
    content-length: 4
    content-type: text/plain; charset=utf-8
    connection: close

body: 
pong
```
I would prefer to take the api spec as the source of truth (and thus not make this an api breaking change that requires a major version bump) but if for some reason this would affect you please speak up!
