### ISSUE TITLE
Become User Key failed

### ISSUE THREAD

**Issue by kupe-dono** [ansible-semaphore/semaphore#742]
Hi again !

I've tried to configure User Access Key and Become User Access Key.
But it seems it is not used after all when I run it.
I get the following error:

```
TASK [adm-account-conformance : PASSWORDS | Update adm-test password] *************
6:10:15 PM
fatal: [myserver-test.com]: FAILED! => {"changed": false, "msg": "usermod: Permission denied.\nusermod: cannot lock /etc/passwd; try again later.\n", "name": "adm-test", "rc": 1}
```

My playbook is the following:

```yaml
- hosts: new_boxes
  remote_user: ansible
  become: true
  become_method: sudo
  become_user: root
  gather_facts: no
  roles:
    - adm-account-conformance
```

The role that I call:

```
---
- name: PASSWORDS | Check if adm-test account exists
  shell: "id -u adm-test"
  register: admtest_exists
  ignore_errors: true

- name: PASSWORDS | Check if adm-test group exists
  shell: "id -g adm-test"
  register: group_exists
  ignore_errors: true

- name: PASSWORDS | Update adm-test group
  group:
    name: adm-test
    gid: 1010
  when: group_exists.rc == 0

- name: PASSWORDS | Create adm-test group
  group:
    name: adm-test
    gid: 1010
    state: present
  when: group_exists.rc != 0

- name: PASSWORDS | Update adm-test password
  user:
    name: adm-test
    password: "{{ vault_admpwd | password_hash('sha512') }}"
    shell: /bin/bash
    uid: 1010
    groups: sudo,adm-test
    update_password: always
  when: admtest_exists.rc == 0

- name: PASSWORDS | Create adm-test account
  user:
    name: adm-test
    password: "{{ vault_admpwd | password_hash('sha512') }}"
    shell: /bin/bash
    uid: 1010
    groups: sudo,adm-test
  when: admtest_exists.rc != 0
```

Maybe I do it wrong ?

I assume that the exactly same playbook works fine in command line.
