### ISSUE TITLE
Cannot install Semaphore with Mariadb in docker

### ISSUE THREAD

**Issue by hydrosIII** [ansible-semaphore/semaphore#768]
I cannot iinstall semaphore with Mariadb  10.5.12-MariaDB, when trying to initiate it  I got:

````
Is this correct? (yes/no) (default yes): 

Config output directory (default /home/semaphore): 

Running: mkdir -p /etc/semaphore..

Configuration written to /etc/semaphore/config.json..

 Pinging db..

Running DB Migrations..

Checking DB migrations

Executing migration v1.0.0 (at 2021-10-22 19:53:43.170367937 +0000 UTC m=+0.117876247)...

time="2021-10-22T19:53:43Z" level=warning msg="\n ERR! Query: alter table task add `debug` boolean not null default false\n\n"


 [1/59]Rolling back v1.0.0 (time: 2021-10-22 19:53:43.170811289 +0000 UTC m=+0.118319596)...

Rollback SQL does not exist.


Database migrations failed!

 Error 1060: Duplicate column name 'debug'

````

My docker compose file is the following:

````
version: '2'
services:
  semaphore:
    ports:
      - 3000:3000
    image: ansiblesemaphore/semaphore:v2.7.22
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: 'xxxxxxxxxxx'
      SEMAPHORE_DB_HOST: xxx.xxx.xxx.xxx
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: cangetin
      SEMAPHORE_ADMIN_NAME: admin
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: admin
````

It also happens using the latest tag.
