### ISSUE TITLE
`Status Code 400` Returned when using API at `api/project/#/keys`

### ISSUE THREAD

**Issue by uwardlaw** [ansible-semaphore/semaphore#785]
We are using the Docker (`v2.7.22`) deployment of Ansible-Semaphore and use the Semaphore API to build additional projects and templates from Ansible playbooks. 

I would really appreciate help understanding how to read Semaphore's understanding or logs of requests it receives to the API, a way to view the raw data being received (besides taking a packet capture, which I could also do), or some suggestions on how to format the data properly for the API.

Here are two tasks we have in our playbook.

```yaml
  - name: "Create new project for Class {{ class }}"
    uri:
      url: http://{{ controlIP }}:4000/api/projects
      method: POST
      validate_certs: no
      return_content: yes
      headers:
        Content_Type: "application/json"
        Accept: "application/json"
        Authorization: "Bearer {{ api_key }}"
      body_format: json
      body:
        name: "Class {{ class }}"
        alert: false
      status_code: 201, 200
    register: project

  - debug:
      var: project

  - name: Create key of type none
    uri:
      url: http://{{ controlIP }}:4000/api/project/{{ project.json.id }}/keys
      method: POST
      validate_certs: no
      return_content: yes
      headers:
        Content_Type: "application/json"
        Accept: "application/json"
        Authorization: "Bearer {{ api_key }}"
      body_format: json
      body:
        name: "NoneKey"
        type: "none"
        project_id: "{{ project.json.id | int }}"
    register: noneKey

  - debug:
      var: noneKey
```

The first task, `Create new project for Class {{ class }}` succeeds. We use `body_format: json` and the `YAML` style body. However, the second task `Create key of type none` fails with `HTTP Error 400: Bad Request`.

```
fatal: [localhost]: FAILED! => {"changed": false, "connection": "close", "content": "", "content_length": "0", "content_type": "application/json", "date": "Wed, 03 Nov 2021 17:17:56 GMT", "elapsed": 0, "msg": "Status code was 400 and not [200]: HTTP Error 400: Bad Request", "redirected": false, "status": 400, "url": "http://192.168.100.1:4000/api/project/20/keys"}
```

I have tried four different ways of organizing the body in task two, and went as far to try and use raw data.

```yaml
 body_format: raw
   body: {\\"name\":\\"NoneKey\\",\\"type\\":\\"None\\",\\"project_id\\":\\" {{ project.json.id | int }} \\"}
```

For another use case, I have been able to build the exact key in Python. Using the Python module `requests` the `data` field in the `post` method we have (where `managementProjectID` is a number):

```python
      data = '{"name": "NoneKey", ' +                               \
                '"type": "None", ' +                                   \
                '"project_id": ' + str(managementProjectID) + '}'
```  

When we do a get for the same key that's built in a different project, we see:

```
"content": "[{\"id\":1,\"name\":\"NoneKey\",\"type\":\"None\",\"project_id\":1,\"removed\":false,\"login_password\":{\"login\":\"\",\"password\":\"\"},\"ssh\":{\"login\":\"\",\"passphrase\":\"\",\"private_key\":\"\"},\"override_secret\":false},{\"id\":2,\"name\":\"NoneKeyLP\",\"type\":\"login_password\",\"project_id\":1,\"removed\":false,\"login_password\":{\"login\":\"\",\"password\":\"\"},\"ssh\":{\"login\":\"\",\"passphrase\":\"\",\"private_key\":\"\"},\"override_secret\":false}]\n",
```

Which is the closet I could get to inspecting how Semaphore expects to receive the body data.

Issue blocking:
- https://github.com/uwardlaw/vater/issues/10

**Comment by jcmdln** [comment]
I ran into a similar issue when creating a `default` access key of type `none`, but was able to work around it by avoiding the dict->json conversion and instead writing the body like this:

```yaml
- name: Add key
  ansible.builtin.uri:
    url: "{{ semaphore_url }}/api/project/{{ project_id }}/keys"
    method: POST
    headers:
      Accept: application/json
      Content-Type: application/json
      Cookie: "{{ _semaphore_login.cookies_string }}"
    body: >-
      {
        "name": "default",
        "project_id": {{ project_id }},
        "type": "none"
      }
    body_format: json
    status_code: [200, 204]
  vars:
    project_id: 16
```

Hope this helps!

Edit: Remove reference to loop
