### ISSUE TITLE
Requests freezing

### ISSUE THREAD

**Issue by mbajur** [ansible-semaphore/semaphore#79]
Hello everyone,

i'm trying to use semaphore provisioned in virtualbox using docker + ansible (i know you have official ansible role for that but i'm trying to use docker for hosting) but for some reason, requests to sign-in are freezing and are finally failed (after a timeout i suppose). I can get to the login page but the login POST request won't work.

I've created an ansible role based on your docker-compose.yml file:

```
- name: redis container
  sudo: true
  docker:
    name: redis
    image: redis:latest
    hostname: redis
    expose:
      - 6379
    volumes:
      - /tmp/redis:/data

- name: mongodb container
  docker:
    name: mongodb
    image: mongo:latest
    command: mongod --smallfiles --directoryperdb --noprealloc
    hostname: mongodb
    volumes:
      - /tmp/mongodb:/data/db
    expose:
      - 27017

- name: app container
  docker:
    name: semaphore
    image: castawaylabs/semaphore:latest
    # state: reloaded
    # pull: always
    expose:
      - 80
    links:
      - "redis:redis"
    ports:
      - "8088:80"
    env:
      MONGODB_URL: mongodb://mongodb/semaphore
      REDIS_HOST: redis
```

I can see the containers are running fine but logs are not showing anything handy. The interesting part is that when i'm trying to send a sign-in request with curl:

    curl -X POST http://localhost:8088/auth/password -d '{"auth": "admin@semaphore.local", "password": "CastawayLabs"}' -H "Content-Type: application/json"

that request is not even in the semaphore container request logs until i kill it during the freeze. Removing the `-H "Content-Type: application/json"` removes the freeze but api is returning 400 immediately.

Any idea what's going on in here? Not sure how i can even debug that.
