### ISSUE TITLE
Extra CLI format

### ISSUE THREAD

**Issue by kupe-dono** [ansible-semaphore/semaphore#809]
Hi team,

I would like to try something like this : 
ansible-playbook -i inventory.yml playbook.yml -e '{"vm_names":[test-vm]}'

Where vm_names is a role's variable entry. But the format seems to be wrong as I get "template arguments must be valid JSON".

Edit:
This format is correct : 
[
"-e",
{"vm_names":"[test-vm]"}
]

But I get the following errors : 
5:05:45 PM Could not unmarshal arguments to []string
5:05:45 PM Listing playbook hosts failed: json: cannot unmarshal object into Go value of type string

This version seems to pass the config check:
[
"-e",
"vm_names:test-vm"
]

But semaphore doesn't override the variable vm_name initialy set to another value in the playbook.

**Comment by fiftin** [comment]
Looks like you missed quotes for `test-vm`:
```
{"vm_names":["test-vm"]}
```

**Comment by kupe-dono** [comment]
Thank you for you reply !

I get same error message :(

```
[
"-e",
{"vm_names":["test-vm"]}
]
```

```
5:44:24 PM Could not unmarshal arguments to []string
5:44:24 PM Listing playbook hosts failed: json: cannot unmarshal object into Go value of type string
```

Variable is set like /etc/ansible/roles/some-role/vars/vm-names.yml
```
---
vm_names:
  - for01-forensic-01
```

Edit: (The playbook for info)

```
---
- name: Include proxmox variables
  include_vars:
    dir: vars

- name: Check if provided VM/HOST names already exist
  find:
    paths: /etc/pve/nodes/oslo
    recurse: yes
    patterns: "*.conf"
    contains: 'name\:\s{{ item }}'
  with_items:
    - "{{ vm_names }}"
  register: vm_exists

- name: Create VM if not present
  shell: |
    vmid=$(pvesh get /cluster/nextid)
    qm clone {{ template_vm }} $vmid --format raw --full 1 --name {{ item.item }} --storage {{ storage_name }} --target {{ node_name }} > /dev/null
    echo $vmid
#    qm resize $vmid virtio0 +{{ resize_disk }}M
  with_items: "{{ vm_exists.results }}"
  when: item.matched < 1
  register: qm_output
```
