### ISSUE TITLE
Crash: Docker Volume

### ISSUE THREAD

**Issue by david-steg** [ansible-semaphore/semaphore#810]
Hello, I would like to mount the `/etc/semaphore/config.json` or the directory `/etc/semaphore` with a Docker Volume.
Doing so could I Edit some config which don't habe any Variable, like Telegram token, port etc...

But if I create the container with:
```
version: '2'
services:

  mysql:
    container_name: mysql
    ports:
      - 3306:3306
    image: mysql:5.6
    hostname: mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
      MYSQL_DATABASE: semaphore
      MYSQL_USER: semaphore
      MYSQL_PASSWORD: GF@60R5LPzlp
    volumes:
      - ./data:/var/lib/mysql

  semaphore:
    container_name: semaphore
    ports:
      - 22:22
      - 49282:3000
      - 9418:9418
    image: ansiblesemaphore/semaphore:latest
    environment:
      SEMAPHORE_DB_USER: semaphore
      SEMAPHORE_DB_PASS: GF@60R5LPzlp
      SEMAPHORE_DB_HOST: mysql
      SEMAPHORE_DB_PORT: 3306
      SEMAPHORE_DB: semaphore
      SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
      SEMAPHORE_ADMIN_PASSWORD: GF@60R5LPzlp
      SEMAPHORE_ADMIN_NAME: littlebook
      SEMAPHORE_ADMIN_EMAIL: admin@localhost
      SEMAPHORE_ADMIN: littlebook
    volumes:
      - ./config/config.json:/etc/semaphore/config.json
    depends_on:
      - mysql
```
The Container will always crash.
