### ISSUE TITLE
localhost unarchive error

### ISSUE THREAD

**Issue by vast0906** [ansible-semaphore/semaphore#908]
Make sure the required command to extract the file is installed. Command \"/bin/tar\" detected as tar type None. GNU tar required. Command \"/usr/bin/unzip\" could not handle archive

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/18095287/162358789-4db70336-287e-45a7-a566-bdcfa64db65c.png">

docker image: **ansiblesemaphore/semaphore@sha256:03d1f8684027fa8c262935df5d7604afae622f590f2b10336577f72af43cf347**

```
- name: localhost download low-code charts
  unarchive:
    src: "{{ charts_package_url }}"
    dest: "{{ lookup('env', 'PWD') }}/charts/"
    remote_src: yes
    extra_opts:
      - --strip-components=1
  run_once: true
  delegate_to: localhost
```
```

~ $ tar
BusyBox v1.32.1 () multi-call binary.

Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [--exclude PATTERN]... [FILE]...

Create, extract, or list files from a tar file

	c	Create
	x	Extract
	t	List
	-f FILE	Name of TARFILE ('-' for stdin/out)
	-C DIR	Change to DIR before operation
	-v	Verbose
	-O	Extract to stdout
	-m	Don't restore mtime
	-o	Don't restore user:group
	-k	Don't replace existing files
	-Z	(De)compress using compress
	-z	(De)compress using gzip
	-J	(De)compress using xz
	-j	(De)compress using bzip2
	-a	(De)compress based on extension
	-h	Follow symlinks
	-T FILE	File with names to include
	-X FILE	File with glob patterns to exclude
	--exclude PATTERN	Glob pattern to exclude
~ $ which tar
/bin/tar
```

```

~ $ unzip
BusyBox v1.32.1 () multi-call binary.

Usage: unzip [-lnojpq] FILE[.zip] [FILE]... [-x FILE...] [-d DIR]

Extract FILEs from ZIP archive

	-l	List contents (with -q for short form)
	-n	Never overwrite files (default: ask)
	-o	Overwrite
	-j	Do not restore paths
	-p	Print to stdout
	-q	Quiet
	-x FILE	Exclude FILEs
	-d DIR	Extract into DIR
~ $ which unzip
/usr/bin/unzip
```
