### ISSUE TITLE
become sudo does not works

### ISSUE THREAD

**Issue by bahamut657** [ansible-semaphore/semaphore#949]
```
- name: Example
  hosts: rpi-server
  become: yes
  become_method: sudo
  gather_facts: false
  tasks:
    - name: "Update APT repositories  and cache"
      apt:
        update_cache: yes
        force_apt_get: yes
        cache_valid_time: 3600
```

Seems to run the update without becoming root (using sudo)
Inventory configuration already set the "sudo credentials"

How to make it works?
I'm trying to update an RPI where sudo su (with user pi), get root with no password

Regards and well done for the nice work
