### ISSUE TITLE
Semaphore does not recognize the ssh key while cloning a GitHub repo

### ISSUE THREAD

**Issue by afeefghannam89** [ansible-semaphore/semaphore#969]
Hi,

I am still testing semaphore with the newest version, v2.8.53. I want to clone my GitHub repository using a valid ssh key. Semaphore says there is permission to clone the repository
![Screenshot 2022-06-16 at 17 40 25](https://user-images.githubusercontent.com/39904920/174109495-71781457-3274-4b76-a23f-4e8bfacd38e6.png)

But when I load the same ssh key in ssh-agent then start the semaphore, I can clone the GitHub repository.

![Screenshot 2022-06-16 at 17 45 25](https://user-images.githubusercontent.com/39904920/174111519-b05e1560-df73-49f5-a0b0-fad2d1923183.png)

I am sure that the key in both situations is the same one, Any help? Thanks

**Comment by dmtinklenb** [comment]
I'm experiencing a similar issue.   I can successfully authenticate to my Git repository with that SSH key from the command line, but when running a semaphore template, it tells me the public key is "invalid format."    

![image](https://user-images.githubusercontent.com/80288651/174388563-abeb5533-d058-4d3a-8ecb-20a6c9f06092.png)

**Comment by fiftin** [comment]
hi @afeefghannam89 , @dmtinklenb 

What database do you use? Do you filled option `access_key_encryption` in config file (it is optional, but if it is filled private key was encrypted with it)?

**Comment by afeefghannam89** [comment]
Hi @fiftin 

```
# mysql --version
mysql  Ver 15.1 Distrib 10.8.3-MariaDB, for Linux (x86_64) using readline 5.1
```
**access_key_encryption** has a default value, which I did no touch it. I think this value will be created during the setup step. No, I did not encrypt my private key with it.

**Comment by dmtinklenb** [comment]
mysql  Ver 15.1 Distrib 10.3.28-MariaDB, for Linux (x86_64) using readline 5.1


Doug Tinklenberg
Senior Systems Engineer
Wells' Enterprises, Inc.
(712) 523-5411
________________________________

The information contained in this message and/or attachments is intended only for the person or entity to which it is addressed and may contain confidential, proprietary, and/or privileged material. Any review, retransmission, dissemination or other use, or taking of any action in reliance upon, this information by persons or entities other than the intended recipient is prohibited. If you received this in error, please contact the sender and immediately delete the material from any system and destroy any copies.

**Comment by fiftin** [comment]
Sorry for delay, I trying to reproduce.

**Comment by RKonstantinR** [comment]
I have same error, db - postgres:
![image](https://user-images.githubusercontent.com/38781076/187705364-5adbf281-3952-4f3b-8708-25a1c67efaa2.png)

Config:
![image](https://user-images.githubusercontent.com/38781076/187705547-e31181ec-cf4a-4f3b-b54f-048b38282781.png)

My docker-compose.yml:
```
# The version of the docker-compose syntax must be specified, otherwise the assembly does not work
# By default, there may be a completely old landmark on the car
version: '3.5'

services:
    semaphore:
        # variables
        env_file: 
            - .env
        ports:
            - 3000:3000
        image: ansiblesemaphore/semaphore:${SEM_VERSION}
        container_name: semaphore
        environment:
            TZ: Europe/Moscow
            SEMAPHORE_DB_DIALECT: postgres            
            SEMAPHORE_DB_USER: ${DB_USER}
            SEMAPHORE_DB_PASS: ${DB_PWD}
            SEMAPHORE_DB_HOST: ${DB_HOST}
            SEMAPHORE_DB_PORT: ${DB_PORT}
            SEMAPHORE_DB: "semaphore?sslmode=disable"
            SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
            SEMAPHORE_ADMIN_PASSWORD: ${ADMIN_PWD}
            SEMAPHORE_ADMIN_NAME: ${ADMIN_NAME}
            SEMAPHORE_ADMIN_EMAIL: ${ADMIN_EMAIL}
            SEMAPHORE_ADMIN: ${ADMIN}
            # SEMAPHORE_ACCESS_KEY_ENCRYPTION: ${ACCESS_KEY}
        restart: unless-stopped

# Use a pre-created network for all services (for communication with databases deployed inside the machine, etc.)
# https://docs.docker.com/compose/networking/#use-a-pre-existing-network
networks:
    # https://docs.docker.com/compose/networking/#configure-the-default-network
    default:
        # Use a pre-created network
        external: true
        # Network Name. Command for create: docker network create main
        name: main
```
